### ISSUE TITLE
configuration doesn't work if script is run from a different directory than script's location

### ISSUE THREAD

**Issue by lafar6502** [lorenwest/node-config#170]
Hi, it seems that configuration load fails if the script is not run from its home directory.
Please write a simple script with a configuration (test.js)

var config = require('config');
console.log('config', config.get('some.config'));

and run it from somewhere else, without changing current working directory to the script's location
cd /var/logs
node /home/user/tests/test.js

and it will fail 
    throw new Error('Configuration property "' + property + '" is not defined'
          ^
Error: Configuration property "some.config" is not defined
    at Config.get (/home/ubuntu/tests/node_modules/config/lib/config.js:167:11)
    at Object.<anonymous> (/home/ubuntu/tests/test.js:3:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

this is imho an error, you can't assume script will only be run from one location

**Comment by jksdua** [comment]
Ran into the same issue - as @markstos suggested, i was expecting the config to be picked up from the app directory when running the app through pm2. Would be really useful to add this to the root documentation - even a simple link to the relevant page. The CLI error message is useful, but again could be better if it links to the exact documentation page for config files.

Happy to send a pull request if you think the above changes would be useful.

As always, thanks for the awesome library. It's been immensely helpful and part of basically all my node projects.

**Comment by lorenwest** [comment]
Hi @jksdua,

Thank your for your input. I like your suggestions, and would be happy to accept a pull request.  This is something that could help others.

**Comment by taimoor954** [comment]
i honestly did not get the documentation, how can i override by setting the $NODE_CONFIG_DIR environment variable?

**Comment by taimoor954** [comment]
> 
> 
> Ran into the same issue - as @markstos suggested, i was expecting the config to be picked up from the app directory when running the app through pm2. Would be really useful to add this to the root documentation - even a simple link to the relevant page. The CLI error message is useful, but again could be better if it links to the exact documentation page for config files.
> 
> Happy to send a pull request if you think the above changes would be useful.
> 
> As always, thanks for the awesome library. It's been immensely helpful and part of basically all my node projects.

if you could share the solution please
