### ISSUE TITLE
TOML support

### ISSUE THREAD

**Issue by jasonhansel** [lorenwest/node-config#191]
Any chance of adding support for TOML files? It would be quite useful.

**Comment by markstos** [comment]
@jasonhansel We are currently considering switching to using `node-require` / `node-interpret` for reading files in the short term, and I see that they support TOML, so TOML support would come along with that. In the longer term, we are looking at making the config file formats supported more fully pluggable. 

For now, I think you can safely fork and patch the code to support TOML with the expectation that the change will be forward-compatible. I think you should find it fairly easy to support a few file format based on existing examples. 

See https://github.com/lorenwest/node-config/issues/181 for more context.
