### ISSUE TITLE
Does not work using scripts on path due to process.cwd() call

### ISSUE THREAD

**Issue by matAtWork** [lorenwest/node-config#194]
Sadly, config doesn't work if I'm using
````
    #!/usr/bin/env node
````
...at the top of my script and adding the script to my path, as during initialisation it uses process.cwd().

At present I've patched this with the following routine, but ideally I could either specify I wanted configs loaded from a different directory, or you'd change the implementation to use the installation directory rather than the cwd.

My patch (nasty):
````
/**
 * Call a function having (temporarily) fixed the process.cwd() to the installation directory
 */
function withCWD(f) {
	var path = require('path') ;
	var installationPath = path.resolve(require.main.filename,"..") ;
	var z = process.cwd ;
	try {
		process.cwd = function() {
			return installationPath ;
		}
		var r = f.apply(null,Array.prototype.slice.call(arguments,1)) ;
	}
	finally {
		process.cwd = z ;
	}
	return r ;
}

var config = withCWD(require,'config');

````

**Comment by markstos** [comment]
The use of `process.cwd()` is documented behavior. The `NODE_CONFIG_DIR` environment can be used declare where your config files are using another means.

https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir

**Comment by matAtWork** [comment]
Thanks for the update (I did spot the NODE_CONFIG_DIR), but this doesn't work when you have a number of scripts installed in different places, each on the path. This is a pretty common use case with scripts run by the shell.

Is the use of process.cwd() really a good idea? For 'normal' command line instantiate of the form 'node ....' the installation directory and the CWD will be the same thing, but on the case where they're not, 'config' will read from (effectively) an arbitrary directory (the current one), with possible security issue for spoofing a config. The same is also true if an app does a CD - the location of where the config is read from is now also arbitrary (and therefore a security risk).

I'm of the view that loading (by default) from the installation directory avoids these issues as the directory is (effectively) fixed at installation, and cannot be changed by run-time behaviour. To avoid the situation where this breaks an existing code-base (unlikely as it only works when the installation directory and CWD are the same), perhaps this should be a documented risk with a new entry point.

**Comment by markstos** [comment]
This is a duplicate of #138.

**Comment by matAtWork** [comment]
Yep, and setting NODE_CONFIG_DIR is nicer than hacking process.cwd(), so I'll change my patch.

Not sure this adequately addresses the security issues that process.cwd() implies.

**Comment by markstos** [comment]
Since this is a duplicate of #138, I'm closing this one.
