### ISSUE TITLE
Publish 1.11.0 to NPM

### ISSUE THREAD

**Issue by evanrs** [lorenwest/node-config#195]
The current version on NPM is 1.10.0—I'd love to get some of that HJSON support.

**Comment by lorenwest** [comment]
My bad - working with private NPM repositories has this inconvenient side effect.  Sometimes you publish to the wrong repo.  Switched to the public repo, and published.  Thank you for bringing this to my attention.

**Comment by evanrs** [comment]
Thanks for the quick response!
