### ISSUE TITLE
Include in documentation please

### ISSUE THREAD

**Issue by kelvcutler** [lorenwest/node-config#199]
Please include a line or snippet talking about correctly naming your config files. 

Either list the "key-names" such as "default", [NODE_ENV], [hostname], "local" and combinations thereof, or, simply call out that using local is not a good idea to denote your local development machine (in attempts to distinguish from the remote development server).

This is incredibly frustrating to debug when working on a local machine and then deploying out to a remote dev machine - I had to go to the source code to figure out what was going on (something I'm not sure most people are comfortable doing).

**Comment by lorenwest** [comment]
Is the wiki page on [configuration files](https://github.com/lorenwest/node-config/wiki/Configuration-Files) inadequate?

**Comment by markstos** [comment]
@kelvcutler there is also a "strict mode" which specifically warns you about using a NODE_ENV value of "local":  https://github.com/lorenwest/node-config/wiki/Strict-Mode

I ran into that issue with "local" myself and added the feature.

I renamed my local environment to "laptop" to avoid the conflict. 

I recommend trying strict mode, it may catch other issues for you in the future.

**Comment by markstos** [comment]
@lorenwest I would take this report a vote towards enabling strict mode by default in a future major version. Naming a environment "local" is something people can expected to continue to do.

**Comment by lorenwest** [comment]
Agreed. The warning output and associated documentation doesn't go far enough.  

It just needs to work, or fail fast.

**Comment by kelvcutler** [comment]
Thanks for the response! Yes, that link - which I find easily now - is/should be sufficient. Somehow I just overlooked it.

The strict mode for node is not something I had thought to use. I'll look into that. Thanks again!

**Comment by markstos** [comment]
@kelvcutler Glad you got found what you needed. To be clear, the strict
mode is just for 'node-config', not all of node.js

On Fri, Feb 20, 2015 at 11:06 AM, kelvcutler <notifications@github.com>
wrote:

> Closed #199 <https://github.com/lorenwest/node-config/issues/199>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/issues/199#event-239214399>.
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos
