### ISSUE TITLE
Add method for getting optional settings

### ISSUE THREAD

**Issue by ismyrnow** [lorenwest/node-config#200]
I love this library, and have been using it for all of my projects lately. However, I was surprised by the behavior of `config.get()`. I read the discussion at #173, and I understand that throwing an exception is intentional.

I have a widespread need for optional configuration options. Here is a use-case:

```javascript
// Set some database parameters only if they are defined. Otherwise, defaults will be used.
var db = new Database({
  adapter: 'postgres',
  host: config.get('db.host'),
  port: config.get('db.port')
});
```

I am currently using my own function (which calls `config.has` and `config.get`) to provide this behavior. I would love to submit a PR to add this behavior to the library in a backwards-compatible way.

I'm open to suggestions for what to call it -- perhaps `config.getOptional`. Alternatively, I could implement a switch for the `config` module that changes the behavior of `config.get` if a developer opts-in to it.

**Comment by markstos** [comment]
@ismyrnow Here's how I manage this:

A master "default.js" holds *every* key used across the application. If there is no reasonable default value, it is set to `undefined`. For an optional field, the default value can be set to `null`.  That counts as explicit definition, so `config.get()` won't throw an error on it., allowing existing code like the above to work.

**Comment by gustavohenke** [comment]
I think the setup from @markstos is a good choice.
Not registering every key increases the chances of losing control over your configuration.

**Comment by lorenwest** [comment]
The procedure outlined by @markstos is preferred, but another method is to access the configuration directly from the config object vs. using get().  If the config variable doesn't exist it'll return undefined and not throw an exception.

That option would be useful if you didn't know the config parameter name until runtime.  That use case may be an indicator that you're using node-config as more of a database than a process configuration system.

**Comment by ismyrnow** [comment]
I like the suggestion by @markstos. I started doing that after opening this issue but I find the difference between undefined and null to be non-intuitive in a configuration file.

However, I'm thinking this will just become a best practice for our config files. I agree that it promotes configuration visibility.

Thanks for the input everyone!

**Comment by ismyrnow** [comment]
I just realized that a value of `undefined` is not valid in a JSON file. I like the approach of using that for required values, but it's not feasible if you're using the JSON format. Kind of a bummer.

**Comment by markstos** [comment]
You can mix-and-match formats if that helps. Using the `.js` file for `defaults.js` is easy enough:

```javascript
module.exports = {
  foo : undefined,
};
```

I'm also a big fan of having comments in the master config file to note what all the configuration options are for. JSON doesn't allow comments, although `node-config` allows you to fudge on that point and strips them out for you.
