### ISSUE TITLE
Insecure config

### ISSUE THREAD

**Issue by CodersBrothers** [lorenwest/node-config#204]
If we have a config file, this file can be read for a user that enter inside of machine. The best way it's run app with stdin strings like when we do a ssh connection (when we enter the password)

There are a node module called read (https://www.npmjs.com/package/read) this can be helpful in this feature. But the problem is: How we can use all this features with something like forever or PM2 mdules.

Seems really hard this situation.

**Comment by markstos** [comment]
You don't appear to reporting a bug in `node-config` so I'm closing this issue.

**Comment by CodersBrothers** [comment]
Yes it's other way to avoid the problem, ignoring
