### ISSUE TITLE
Make environment variable configurable

### ISSUE THREAD

**Issue by thokari** [lorenwest/node-config#207]
Hi, 
is there a way to configure which environment variable should be used to determine which configuration file is used? For example I do not want to use NODE_ENV, because I want that to be restricted to 'production' and 'development' only. Mainly for the reason, that some modules I depend on, e.g. 'express', also look at that environment variable, and I don't want to risk breaking them by providing unexpected values. But I still need the ability to use 'ci.json', 'staging.json', 'test-integration.json' etc. configuration files.
Would you be interested in a pull request?
Or is there a better way to do this?

**Comment by markstos** [comment]
Use [NODE_APP_INSTANCE](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_app_instance) while being aware of the [file load order](https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order).
