### ISSUE TITLE
cson dependency not up to date

### ISSUE THREAD

**Issue by dsimidzija** [lorenwest/node-config#212]
After installing both `config` and `cson`, parsing cson doesn't work out of the box because `parseSync` doesn't exist anymore in the cson package (v3.0.1).

It looks like `config` is dependant on an older version of cson (v1.6.1), which is why it still works in tests.

**Comment by lorenwest** [comment]
node-config lazy loads custom parsers, including cson.  The right thing to do is to load it and detect which version is loaded, and either do `parseSync` or whatever else you have to do for the same thing.

A pull request that introduces this logic would be welcome, because it would be both backward and forward compatible.

**Comment by dsimidzija** [comment]
Tried to do it, but I got two failed CSON tests on a fresh clone, before changing anything, which is weird.. Are they working for you on a fresh clone?

**Comment by lorenwest** [comment]
That's probably because you have a newer version of the cson library.  If
you run the tests from the config directory, and the older cson library is
under the node_modules directory, the tests should pass.  That's how it's
run in Travis, which runs the tests on commit.

**Comment by dsimidzija** [comment]
Finally figured out what's going on. Traced the problem to coffee-script@1.8.0 as dependency of cson@1.6.2; it breaks in coffee-script.js:133 because of the missing `Script.createContext`, which has been moved to `vm.createContext` in one of the 0.11.* versions of node. So the stale dependency of `cson` brings an old version of `coffee-script` which makes the whole thing break on stable node (v0.12.2 on my system).

Not sure how I feel about the whole thing.. :)

Any suggestions?

**Comment by markstos** [comment]
Would it help to get the CSON project to fix their stale dependency?

    Mark

On Sun, May 3, 2015 at 7:26 AM, Dusko Simidzija <notifications@github.com>
wrote:

> Finally figured out what's going on. Traced the problem to
> coffee-script@1.8.0 as dependency of cson@1.6.2; it breaks in
> coffee-script.js:133 because of the missing Script.createContext, which
> has been moved to vm.createContext in one of the 0.11.* versions of node.
> So the stale dependency of cson brings an old version of coffee-script
> which makes the whole thing break on stable node (v0.12.2 on my system).
>
> Not sure how I feel about the whole thing.. :)
>
> Any suggestions?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/issues/212#issuecomment-98471779>
> .
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos

**Comment by dsimidzija** [comment]
Do you mean as an update for the 1.6.x release? This seems unlikely now that it's gone up to 3.x. and a lot of changes were done there.

I tried playing with config a bit, [this change](https://github.com/dsimidzija/node-config/commit/a1c13304d30a7222d262fdf5cc06693d788e7972) passes all the tests on node v0.8.28, v0.10.38 and v0.12.2, **and** it also works with cson@1.6.1, but there is a caveat as you can see by the test change; the newer version is parsing cson arrays correctly, and not as objects, so there is a bit of an incompatibility. As far as I can tell, this is the only difference.

The test could maybe be changed to assert that `config.Customers.lang.length === 2` if you'd want them to pass with old cson as well, but that's too hackish imho.

**Comment by lorenwest** [comment]
I'm having a hard time following the details of this thread, mostly because
I don't use cson or coffee.

In the end, if a hack is necessary so we don't have to change the
compatibility version, it's ok to put it in.  Especially since it can be
removed on a subsequent compatibility version change.

-Loren

**Comment by dsimidzija** [comment]
Ah, right, I know that feeling :) Here's a simpler version :)

If you want to play it safe, you can merge just the `config.js` changes, this should work with old and new version of cson package, in exchange you're left with that bit of crappy code..at least until the next major release of node-config with breaking changes.

Alternatively, if you want to update the cson dependency now (merge the whole commit), you'd be introducing a better parser for cson (correct handling of arrays), but it's potentially breaking for existing users if they have arrays in cson files.

Personally I'd choose the second option because if someone updates their cson, it's a breaking change either way (and you don't have control over that anyway), and with the second option you have the benefit of being ready for node v0.12.2.

Well crap, this was much simpler in my head.

**Comment by dsimidzija** [comment]
Actually, there's a simpler version.

The `config.js` change enables node-config to work with both old (1.6.2) and new (3.0.1) cson.

The only choice is whether you want to update your dev dependency and change the failing test or not, since the dependency is only used for tests really. If you update, you're ready to run tests on latest stable node.

Also, sorry for spamming you. :(

**Comment by lorenwest** [comment]
From your comments it sounds like the best thing is to put in the hack, update dev dependencies to the newer cson, and change the `.travis.yml` file to include node 0.12

The hack will allow existing installs with prior cson libraries to work, and as long as the newer cson library listed in dev dependencies is compatible with earlier versions of node.js, then all the tests should pass.

If you submit a pull request with the new `.travis.yml`, an updated devDependencies, and your changes to config.js, that pull request will be automatically run through travis and validate these assumptions.
