### ISSUE TITLE
Handling Unicode BOM

### ISSUE THREAD

**Issue by johndkane** [lorenwest/node-config#215]
The Node.js Tools for Visual Studio json template creates a Unicode UTF-8 file having a Byte Order Mark (BOM) http://en.wikipedia.org/wiki/Byte_order_mark This is valid Unicode but apparently BOM is unneeded, it is left to the programmer to handle, and the fs.ReadFileSync method also leaves it to the programmer to handle as discussed here: https://github.com/joyent/node/issues/1918 

The node-config code currently doesn't handle BOM. This results in "Error: Cannot parse config file: '../config/default.json' SyntaxError:Unexpected token ∩╗┐" as described in this SO post:
http://stackoverflow.com/questions/30110659/node-config-cannot-parse-config-syntaxerror-unexpected-token

Apparently BOM is an issue in general as a package has been created to strip it out for UTF-8 https://www.npmjs.com/package/strip-bom

I'd like to update node-config to handle BOM in an agreeable manner, and am opening discussion here. 

My first proposal is simply to add the following code line after the call to FileSystem.readFileSync in the util.parseFile function. This line of code is taken from the fs joynet discussion linked above: 

      fileContent = fileContent.replace(/^\uFEFF/, '');

**Comment by lorenwest** [comment]
That sounds reasonable.  If you want to put this in, add a file to the test directory that has some BOM characters in it, and a test that loads that file.  Verify the test fails before adding the line, then add the line and verify the test passes.

Then submit a pull request and we'll get the code into the package.  Plus, you'll get your picture on the node-config home page as a contributor :)

**Comment by lorenwest** [comment]
Published in config@1.14.0
