### ISSUE TITLE
Provide a `reload` function

### ISSUE THREAD

**Issue by MrBoolean** [lorenwest/node-config#224]
I use the `config` package on several projects. Its really easy to use! Love it! 

Unfortunately, there is no function to reload the configuration from the source. I use `config` on `gulp` and the `express` application. The `gulp` task `dev` generates an instance of my server. To generate serveral `angular` modules the `config` dependency is also required on the `gulpfile.js` file. So there is just one instance for `gulp` and the server.

One of my tasks takes care of changes under `config/**/*`. Once there is a change my `angular` modules become regenerated. But the configuration provided by `config` is still the same.

So it would be great to provide a new function called `reload` (or somehow else) to reload the configuration.

```javascript
var config = require('config');

gulp.task('dev', function () {
  // ...

  // provides the data from config.get('app') to an angular module
  gulp.watch(['config/**/*'], ['angular:config']);

  // ...
});
```

**Comment by lorenwest** [comment]
Hello Mr. 10,

There is a long history of reload functionality in node-config, ending up where we are today.  To get an idea of this issue, take a look at this thread: https://github.com/lorenwest/node-config/issues?utf8=%E2%9C%93&q=is%3Aissue+reload

There are ways to reload configurations, and native support has a long and sorted history.

Let me know if you have questions.  

-Loren

**Comment by markstos** [comment]
Every Node module can be easily reloaded. I think it's best for developers to know how to use the universal method rather than to have many modules re-implement the feature. You can see us using in the test suite:

https://github.com/lorenwest/node-config/blob/master/test/6-strict-mode.js#L91

It boils down to removing `config` from the module cache. Set the environment variables as you like and then `require` it normally:

```javascript
   delete require.cache[require.resolve('config')];
   var config = require('config');
```
   
It appears that this pattern has already been packaged in an NPM module if you wish to use it:

https://www.npmjs.com/package/require-uncached

**Comment by MrBoolean** [comment]
Hmmm... `require-uncached` won't work. All submodules required by `config` are also cached. 

Checkout: MrBoolean/node-config-uncached

**Comment by lorenwest** [comment]
Thanks for providing the add-on.  Feel free to add an `addons` page to the wiki with a link to this.

**Comment by benag** [comment]
Is this atomic and safe while the server is running and using the config module?

**Comment by sascha1337** [comment]
this is core basic feature please give us a real solution instead a hack like this

**Comment by lorenwest** [comment]
Hello @sascha1337 

You might want to read the thread and understand the issue before telling us what is or is not a basic feature.

-Loren
