### ISSUE TITLE
How to set the source folder for the config files?

### ISSUE THREAD

**Issue by bluejamesbond** [lorenwest/node-config#229]

**Comment by lorenwest** [comment]
Hi Matthew,

The [`NODE_CONFIG_DIR` environment variable](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir) is what you're looking for.  Information on it's usage and other helpful information is on [the wiki](https://github.com/lorenwest/node-config/wiki).

Best of luck,
-Loren
