### ISSUE TITLE
need to start from the root folder?

### ISSUE THREAD

**Issue by zzswang** [lorenwest/node-config#230]
It is ok if I run command under the root folder:

``node index.js``

but it failed to find the correct config directory while:

``node /opt/app/index.js``

But it really needs to start from /, when it is running in a docker container.

Any idea?

**Comment by markstos** [comment]
In your Dockerfile, sounds like you need to set [WORKDIR](https://docs.docker.com/reference/builder/#workdir)

Or try:

```
cd /opt/app && node ./index.js
```

I'm going to go ahead and close this since it's not reporting a bug in `node-config`.
