### ISSUE TITLE
Compatibility with browserify?

### ISSUE THREAD

**Issue by bluejamesbond** [lorenwest/node-config#233]
Anyway to transform the config properties for use on client-side?

**Comment by lorenwest** [comment]
I've considered it but haven't actually tried.  Not sure how browserify deals with `fs` commands that read configuration values from files, or what that means when running on the browser.  If you have a use case and are interested in trying, I'd be interested in hearing how it goes and working with you to achieve your goals.

**Comment by bluejamesbond** [comment]
@lorenwest I am still fairly new the browserify but I was thinking a lightweight transform should do it. In the client side users can do something like the following:

```js
var testConfig = config('AllConfig.testConfig');
```

The transform (like the one implemented for [workerify](https://github.com/shama/workerify)) would then convert during bundling to actual string value.
```js
var testCofnig = 'myTestConfigValue'
```

What do you think?

**Comment by markstos** [comment]
If the `fs` and other node.js-specific calls were wrapped in methods, then `node-config` could ship with a sub-class that overrides those methods to pull the configuration from somewhere the browser can access. 

I'm not necessarily  advocating for `browserify` support, but thinking out loud about how it might work. 

The design pattern I've used is to use `node-config` on the backend, but mark one part of the config as `config.frontend`. Then if you visit the URI `/config.js` the backend serves this portion of the configuration as a JSON to the frontend.  Thie approach allows us to have one configuration between the backend and frontend, with sensitive configuration still only visible to the backend, not the frontend.

**Comment by bluejamesbond** [comment]
I have written a small transform that incorporates @markstos idea. You can find it here: https://github.com/bluejamesbond/node-configify

**Gruntfile.js**
```js
var configify = require('node-configify');
...
{
    // ...
	browserify: {
		options: {
			transform: [configify]
		}
	}
	// ...
}
```

**ClientSide.js**
```js
var config = require('config');
global.window && console.log(config.get('Client.testProperty')); // prints `hello!`
```

**config/default.json**
```js
{
  "Client": {
  	"testProperty": "hello!"
  }
}
```

**NOTE:** Only the `Client` level properties can be accessible from the client-side code (which is bundled by browserify)

If you agree with this method, I can help incorporate this into your repo.

**Comment by lorenwest** [comment]
Great combination of config and browserify!  

One thing I'd change is to consider `client` a deployment target, just like `qa`, `test`, or `production`.  That way your app would get all configurations from `default.js`, augmented with specific configurations from `client.js`.  

This would allow a single application to run in many targets, `client` being one of them.  The only thing in `client.js` would be the differences from `default.js` (passwords removed, etc).

Would you want this to be a part of `config`, or would you like to publish it on your own as `configify` or `node-configify`?  I'd be happy to point people to `configify` from this repo - in the readme and/or the wiki.

**Comment by bluejamesbond** [comment]
@lorenwest The `client` object is pulled directly via your library so you can have different `client` objects for each configuration and `node-config` should pull it correctly. Is that what you meant? And, I can go ahead and publish it. I am planning on keeping the same naming convention as this library - `node-configify` on Github and `configify` on npm (hopefully that is available).

**Comment by lorenwest** [comment]
I see now.  I was considering client as a target vs. different client targets (dev, qa, etc).  I think your approach is more flexible, allowing multiple deployment targets for the Client section of the configuration.

As for watchify, adding this line before your `require('config')` line should do the trick:

```
delete require.cache[require.resolve('config')]
```

**Comment by bluejamesbond** [comment]
@lorenwest I have pushed a version into npm and updated the README accordingly. Also, I don't think we can support watchify in order to provide compatibility with server-side rendering frameworks such as React. If the server configs and the client-configs do not match, React (for instance) throws errors. So, I don't think this feature can be supported until we get feedback from users and see what they want.

**Comment by lorenwest** [comment]
Perfect.  Did you want to make a change to this repo's readme or a wiki change to point to your library?

**Comment by bluejamesbond** [comment]
@lorenwest Yea that would be great. Feel free to do that if you would like.

**Comment by markstos** [comment]
This seems like an interesting to idea, but I have to admit I couldn't understand that module does from the README. Perhaps for some the simple description that it is a "Browserify transform" will be sufficient, but it could be helpful to spell out exactly how it's transforming the `node-config` module. Which behaviors are being changed? What are the new replacement behaviors?

**Comment by bluejamesbond** [comment]
@markstos Thanks for the feedback. This was just a quick push to npm. I will add more information in the coming days. Closing the issue now.
