### ISSUE TITLE
Feature Request: Folder support for configuration files.

### ISSUE THREAD

**Issue by JemiloII** [lorenwest/node-config#234]
I'd just like to be able to split my config files into folders.

So example structure:
```
/root
  /lib
  /config
    /database
      default.json
    default.json
```

If i wanted to access the database/default.json, it would be config.database. This way I can manage smaller configuration files rather than monolithic ones. :)

**Comment by lorenwest** [comment]
How would you specify directory load ordering?

**Comment by lorenwest** [comment]
Personally I'm not a fan of having configurations scattered all over the filesystem.  We have a way to change the config folder via an environment variable, and as sure as I'm writing this, if we allow multiple config folders, the next feature request would be to specify the folder override as a list of folders. We could force multi-folder support to always be deep (from the one config folder), but that would be thought of as a limitation.  It's a slippery slope into a dark place.

**Comment by markstos** [comment]
Agreed. We already have a lot of flexibility/complexity with the possibilities from the file load order as well as multiple environment environment variables, including `$NODE_CONFIG_DIR`:

https://github.com/lorenwest/node-config/wiki/Configuration-Files
