### ISSUE TITLE
Host name should not be case-sensitive

### ISSUE THREAD

**Issue by growell** [lorenwest/node-config#235]
When looking up configuration files, the host name should not be case-sensitive. For example, (on a Linux box) if $HOSTNAME is "myhost", it should still use  the "config/MYHOST.json" configuration file. Currently (v1.14.0), it will ignore that file - since it's not called "config/myhost.json".

**Comment by lorenwest** [comment]
Case sensitivity is a (ahem) sensitive issue. For node-config to support case insensitive filenames, it would have to load all filenames from a directory and perform case insensitive matches with filenames it was expecting.

Making any changes with regards to case sensitivity would not only be a fair amount of work, it would break backwards compatibility making it a non-starter.

**Comment by markstos** [comment]
@growell Why should host name matching be case-insensitive? Is there a related RFC that requires it or declares it a best practice?

**Comment by growell** [comment]
Yes, case-insensitive host names is a convention. (URL host names are, by specification, case-insensitive.)

I ended up switching to another module and implementing what I expected on top of that one.
