### ISSUE TITLE
Retain full hostname when resolving basename.

### ISSUE THREAD

**Issue by vicary** [lorenwest/node-config#236]
I guess a single person would usually name his computers like this `first_name.work`, `first_name.mac.home` and `first_name.pc.home`... etc.

This line make it very easy to collide, I think it's better to use the whole name instead.
```javascript
hostName = hostName ? hostName.split('.')[0] : null;
```

**Comment by lorenwest** [comment]
Hello @vicary.  It appears that this would change the file load order of existing installs. Backward compatibility is required for any pull request to be considered for merging.  

See the wiki page: https://github.com/lorenwest/node-config/wiki/Future-Compatibility

**Comment by lorenwest** [comment]
Your use case is reasonable, and if there's a way to support it without breaking backward compatibility it would be useful to have node-config support it.

**Comment by vicary** [comment]
Would swapping the loading order in my PR works?

**Comment by lorenwest** [comment]
Not sure what you're attempting here, but the result would not work.  It changes the order of the partial hostname (the one in use today) until after the `local` versions.  Maybe you'd get what you need by adding `fullHostname, fullHostname + '-' + NODE_ENV,` before `local` in the `baseNames` array.  I haven't put too much thought into that, but it would be less disruptive than changing the load order of existing installs.

**Comment by vicary** [comment]
I used a new approach on the loading order.

1. Assuming when `!hostName` they are meant to be ignored.
2. Because hostnames can be without dots, I skipped the "full hostname" when it is the case.

**Comment by lorenwest** [comment]
This approach looks good.  Would you mind adding a test to make sure it's doing what you intend, and so it will fail if someone breaks it in the future?  The last part is changing the documentation on the wiki to reflect the added hostname format.

**Comment by vicary** [comment]
Sorry I was too busy last week, I am not very familiar to with vows so I'll leave it. Updated the [wiki page](https://github.com/lorenwest/node-config/wiki/Configuration-Files) for the new behaviour.

**Comment by lorenwest** [comment]
Published this feature today as v1.15 - thanks for the addition!
