### ISSUE TITLE
Empty yaml config file produces warnings

### ISSUE THREAD

**Issue by Jokero** [lorenwest/node-config#238]
From docs:
```
If NODE_ENV is set in the environment, we check if there any file matching that name 
in the config/ directory
```

So I have empty file:
```
config
  test.yaml
```
And test app:
```javascript
process.env.NODE_ENV = 'test';
require('config');
```
Warnings (although config file exists):
```
WARNING: NODE_ENV value of 'test' did match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
```

**Comment by lorenwest** [comment]
That is correct.  The warning suggests the test is on file existence but the test is actually on the presence of configurations found in a file.  You could add a configuration in that file, relax the strict mode, submit a pull request changing the text of the warning to match the actual test, or a pull request to change the test to match the text of the code.

**Comment by markstos** [comment]
I think we do want the check for actual configurations in the file, not just the existence of the file, because it's a stronger check. For example, a file may exist, but have invalid syntax, so returns no data structure. The current check catches that case.

**Comment by Jokero** [comment]
@markstos I agree with syntax check. But what if I don't have any configuration for environment? I created empty file for future configuration and now don't want to place anything useless to file. I think it's common situation

**Comment by markstos** [comment]
@Jokero That situation came up in my case. I created a JSON file containing `{ "supportedEnv" : true }`.

The app ignores this key/value pair, but it meets the check for `node-config` and conveys to the developer a sense of why it's there.

**Comment by Jokero** [comment]
@markstos OK. So for `json` files I can use only `{}` and for `yaml` use any comment `# ` to disable warnings

**Comment by markstos** [comment]
That sounds right. As long as the structure returned is valid.

On Mon, Aug 3, 2015 at 4:39 AM, Dmitry Kirilyuk <notifications@github.com>
wrote:

> @markstos <https://github.com/markstos> OK. So for json files I can use
> only {} and for yaml use any comment # to disable warnings
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/issues/238#issuecomment-127164598>
> .
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos

**Comment by markstos** [comment]
A refinement to our "Strict mode" documentation explaining the  empty file behavior would be welcome. https://github.com/lorenwest/node-config/wiki/Strict-Mode Including a sample of a valid file that could be copy/pasted would be welcome, too.

**Comment by Jokero** [comment]
Before:
If `NODE_ENV` is set in the environment, we check **if there any file** matching that name in the `config/` directory. **If there's actually no problem**, create a file name matching the desired `NODE_ENV` value: `{NODE_ENV}.json` and include the contents '{}', which is an empty valid JSON object.

After:
If `NODE_ENV` is set in the environment, we check **if there any not empty file with valid syntax** matching that name in the `config/` directory. **You can** create a file **with** name matching the desired `NODE_ENV` value: **for example,** `{NODE_ENV}.json` and include the contents '{}', which is an empty valid JSON object.

Good?

**Comment by markstos** [comment]
@Jokero That was helpful, Thanks. I've made the edit now on the wiki page.
