### ISSUE TITLE
showWarnings as default please

### ISSUE THREAD

**Issue by Laro88** [lorenwest/node-config#240]
I have been fighting with a unit test issue, and being new to node.js and config I overlooked the change of scope when unit testing - basically config does not load my config file when executing unit tests.
My tests are in ./test and the config files are in ./config.

```javascript
//Line 1655
// Produce warnings if the configuration is empty
var showWarnings = true;//!(util.initParam('SUPPRESS_NO_CONFIG_WARNING'));
```
For some reason the !(util.InitParam results in false on my laptop and then config becomes silent.
I have blamed Chai, VS2013 & NTVS and the root cause is in config :-(

I think it would be appropriate to dump warnings if something goes wrong in util as seems to be the case right now.

**Comment by lorenwest** [comment]
The warning message for no configs found is on by default.  You have to have an environment variable or command line argument called SUPPRESS_NO_CONFIG_WARNING for the empty config warnings to be suppressed.

If the issue is in the util package as you suggest, the fix is to find that issue and fix it, not to hard code `showWarnings = true`.

Can you isolate the problem with the util package?

**Comment by markstos** [comment]
Closing due to lack of feedback. Please re-open if a bug in `config` is isolated.

**Comment by Laro88** [comment]
Apologies for not giving feedback in due time.
the SUPRESS_NO_CONFIG_WARNING is NOT the problem, it is !undefined when debugging, so this is not the case.
The problem is actually:
When using config in unit testing in VS2013 Mocha then the tests are in .\test\utXYZ.js and the config files for running unit tests must be in .\test\config  such as .\test\config\utconfig.js
I did not have this .\test\config folder with a config for the unit tests.
However when running the unit tests Object.keys(config).length is 4 - and that is the number of config files I have in my .\config folder :-)

So no config is loaded in unit testing and the error is not reported as Object.keys(config).length === 0 becomes false.

**Comment by lorenwest** [comment]
Are you asking us to troubleshoot your tests, or is this a failure of the `node-config` tests? The `node-config` tests aren't run using mocha.

**Comment by lorenwest** [comment]
If you're using `node-config` while testing your application and believe there is a bug in `node-config`, please give us more information than just that Object.keys(config).length is incorrect.  Such as - what are the values of those keys?  If you believe there is a bug in `node-config` please include instructions on reproducing the bug.

**Comment by markstos** [comment]
If you run the tests from the top of the project directory and not from the `tests/` directory, it shouldn't be a problem. You can also set [NODE_CONFIG_DIR](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir) in your tests to make sure it finds the right `./config` folder.

**Comment by Laro88** [comment]
Apologies offered, I am unable to reproduce the problem.
I have removed/renamed folders, files and I do in all scenarios getthe warnings of no config file found as expected. I honestly haven't got a clue as to why they were not printed when I observed the problem.

markstos: NODE_CONFIG_DIR solves my issue and is now put into the test setup.

Thank you both.
