### ISSUE TITLE
Node_ENV not trimed ?

### ISSUE THREAD

**Issue by bixibu** [lorenwest/node-config#241]
Hello

On windows, executing : 
``> set NODE_ENV=test && node server.js``

results on an error (and my environment not being recognized) :
``>WARNING: NODE_ENV value of '"test" ' did not match any deployment config file names.``

It seems like the space before the ``&&`` is interpreted instead of trimed. Command only works if I type the following, but it's quite ugly : 
``> set NODE_ENV=test&& node server.js``

Maybe I am missing something ? or is it a bug? 

Thanks anyways

**Comment by lorenwest** [comment]
Yes, it's a bug in the operating system.

I'd be willing to accept a pull request if you want to keep using that O/S.  Alternately you could put those two statements on individual lines.

**Comment by bixibu** [comment]
Yeah thanks, after a little search, it's a common problem. Closing that ;)
