### ISSUE TITLE
Error when NODE_APP_INSTANCE === 0

### ISSUE THREAD

**Issue by DaAwesomeP** [lorenwest/node-config#244]
PM2 has an option to automatically cluster the right amount based on your server's cores with the `-i 0` option. However, `node-config` pulls up an error and quits the app. This would preferably be a nonfatal error that would simply continue without looking for the cluster-specific config files.

**Comment by markstos** [comment]
What was the error?

**Comment by DaAwesomeP** [comment]
```
WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
```

**Comment by markstos** [comment]
The warning is there to protect from silent failure where NODE_APP_INSTANCE
has a typo. Just create an empty valid 0.json file to express your intent
that the mode is known. Or disable strict mode and live dangerously.

**Comment by DaAwesomeP** [comment]
Thank you for your swift response. Creating a `default-0.json` file with simply `{}` in it did the trick. 

Would you mind adding a note about this somewhere? I can't be the only one using PM2 clustering with `-i 0` (it's the recommended option for clustering).

**Comment by lorenwest** [comment]
This thread is as good as a wiki page.  Nobody will actually look for the error on a wiki, they'll just google the problem, and they'll have as much chance of getting to this thread than a wiki page.

This problem won't get any better with more app instances.  You will need multiple .json files, one per app instance.  I'm wondering - is there a breadcrumb that PM2 leaves around so we can identify this as the PM2 issue, and either ease up on the error or provide a better message? Some other environment variable that PM2 manages?

**Comment by DaAwesomeP** [comment]
> This problem won't get any better with more app instances. You will need multiple .json files, one per app instance.

Not quite. My VM server is dual core, so it creates instances `0` and 1`. I didn't need a `default-1.json`.

> I'm wondering - is there a breadcrumb that PM2 leaves around so we can identify this as the PM2 issue, and either ease up on the error or provide a better message? Some other environment variable that PM2 manages?

Here's their wiki page for it: [PM2 Cluster Mode](http://pm2.keymetrics.io/docs/usage/cluster-mode/). There's probably some non-specifically cluster environment variable or API function to check.

**Comment by markstos** [comment]
You probably didn't need a `default-1.json` file because you were using the `exec` mode, not the `fork` mode.

In general there's a potential conflict here because PM2 also uses the NODE_APP_INSTANCE environment variable, which won't match how `node-config` users are using it all cases. In my case, I use the value for a customer name. 

PM2 uses this value primarily to increment the port number it seems. I use PORT for that and increment it.

**Comment by Kitanotori** [comment]
So, what is the fix to this problem? I'm running my Node.js app in cluster mode and I'm also getting the "WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names" -error. Is node-config incompatible with pm2?

**Comment by markstos** [comment]
@Kitanotori The answer is earlier in the thread:

https://github.com/lorenwest/node-config/issues/244#issuecomment-137632953

**Comment by Kitanotori** [comment]
@markstos Creating an empty file to fix the problem seems like a hack to me. I decided to avoid unnecessary complexity by just putting my configurations in an ordinary Node.js module.

**Comment by DaAwesomeP** [comment]
I've moved on from PM2. I usually deploy my applications with application hosting. If your app works with PM2 and you're using standard programs alongside it (i.e. popular databases), then there isn't a need for it really. I usually use Passenger now to simulate a multi-instance load-balanced configuration because it's much easier to manage, sets up the whole shebang, and is much closer to a real application host.

**Comment by Kitanotori** [comment]
@DaAwesomeP The thing is that I'm using Couchbase, and practically none of the hosting services provide support for it but instead favor MongoDB, which I find nice but lacking in features compared to Couchbase.

**Comment by DaAwesomeP** [comment]
@Kitanotori A simple search returns:
[Couchbase on Heroku](https://elements.heroku.com/addons/kurobase)
[Couchbase on OpenShift](http://blog.couchbase.com/2015/december/couchbase-on-openshift-3)
[Couchbase on AWS](https://aws.amazon.com/marketplace/pp/B0085EC3N0)
[Couchbase on Azure](http://blog.couchbase.com/hosting-couchbase-server-in-windows-azure-part-1)

Application hosting is also significantly cheaper than full-on dedicated hosting.

This has beocme really off-topic, but I really found PM2 not to be a permanent solution. It works well for home and small setups (i.e. Raspberry Pi), but not really anything that needs 24/7 monitoring and performance/uptime analytics. Passenger offers the analytics with a paid-option (I only use it for testing), but it configures the whole server as the PaaS would be.

**Comment by Kitanotori** [comment]
@DaAwesomeP How is the service provided by Keymetrics different from Passenger? https://keymetrics.io/

Btw, I'm already using Couchbase on AWS, but assumed that we were talking about PaaS solutions. That Kurobase for Heroku seems to be still in alpha, i.e. not a realistic solution for a production system. OpenShift might be worth considering, but the previous time I tried it, it seemed overly complicated compared to just launching a Couchbase CentOS image in AWS.

**Comment by DaAwesomeP** [comment]
@Kitanotori Keymetrics solves my PM2 problems. It's just another PaaS that happens to run on PM2. I'd never heard of it before. Passenger doesn't cloud host for you. OpenShift I would agree is annoying. That's just my two cents.

**Comment by markstos** [comment]
@Kitanotori I currently use the simpler `forever` module for process management. I plan to switch to `systemd` for process management when we upgrade to Ubuntu 16.04 as a base.

`node-config` is compatible with pm2. They just both happen to use a environment variable with the same name. Creating a specific file stops the `node-config` warning in this case.

**Comment by sminogue** [comment]
I am having this problem and have tried the above empty file solution to no avail. I make use of node-config in my project so a /config/default.json file exists in my project.

WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.

is whats in my logs and as mentioned above my application craps out after this warning. Attempting to add a default-0.json file into /config doesnt do anything for me, I think because its loading default.json first based on the node-config documentation. 

What am I missing? I'm sure its me not understanding the "fix" in this thread.

**Comment by markstos** [comment]
@sminogue I don't know what you are missing. The `default-0.json` worked for everyone else in the thread.

Try following [Examping Config Sources](https://github.com/lorenwest/node-config/wiki/Examining-Configuration-Sources) to confirm which config files are being loaded.

**Comment by telemmaite** [comment]
`default-0.json` with `{}` inside **does not** work for me either.

**Comment by markstos** [comment]
Since the solution works for some people and not others, there must be some environmental difference between those and it works for and those and it doesn't. Therefore, if it doesn't work for you, create a minimal test case environment to confirm you can reproduce the issue. If you can reproduce it, post the detailed reproduction steps here.  If you *can't* reproduce the issue with a minimal test case environment, then something else in your environment must be part of the issue.

**Comment by markelog** [comment]
Creating empty configs to workaround this confuses developers, creates additional complications and overall not elegant solution.

It's unfortunate that you refused to do this in the proper way :/

**Comment by krisfarr** [comment]
Hi guys,

I have this setup:

/opt/server
/opt/server/app
/opt/server/mailer
/opt/server/prerender


/opt/server/app/config 
/opt/server/mailer/config 
/opt/server/prerender

/opt/server/pm2.json (contains pm2 env & "NODE_CONFIG_DIR"  for each app)

All works wonders until an app crashes ... then I get  WARNING: NODE_APP_INSTANCE and apps fail to reload. Found this behaviour quite odd. 

Where should the empty default-0.json file be placed? PM2 root (/opt/server/) or for each app?

Why is it using the 'production' and 'default' setting?

Thanks!

**Comment by krisfarr** [comment]
For those having issues with PM2 have a look at these settings:

http://pm2.keymetrics.io/docs/usage/application-declaration/

NODE_CONFIG_DIR
CWD

**Comment by koalex** [comment]
So what is the final solution for this issue?

**Comment by lorenwest** [comment]
Did you read the thread? There are several solutions to several different issues. If none of the solutions work, you may be experiencing a different issue. This thread is dead, so create a new one with a repro case if none of the above solutions work for you.

**Comment by vmarchaud** [comment]
**PM2 Maintainer here**
You have a way to avoid this problem with pm2 2.6 (see [docs](http://pm2.keymetrics.io/docs/usage/environment/#specific-environment-variables)) : 

> You may have problems with node-config with the NODE_APP_INSTANCE name,
 so you can rename it with instance_var options :
```javascript
module.exports = {
  apps : [
      {
        name: "myapp",
        script: "./app.js",
        watch: true,
        instance_var: 'INSTANCE_ID',
        env: {
            "PORT": 3000,
            "NODE_ENV": "development"
        }
      }
  ]
}
```

**Comment by markstos** [comment]
Thanks @vmarchaud !

**Comment by incebellipipo** [comment]
After nearly six months i have the same problem on Windows Server 2016. After seeing so many closed issues on this, i'm not so sure if the problem persist or i'm asleep a bit. Wheres what i did, what i can not achive:
1. fresh new installtion of pm2
2. a node application which can work via `npm start`
3. and the [configuration above](https://github.com/lorenwest/node-config/issues/244#issuecomment-320778070)

What i have is an app restating every 5 seconds.

If i don't create `default-0.json` it gives the error. If i create this `default-0.json` just keeps restarting. Did i find a bug deserves a new issue, or did i just misconfigure my system?

**Comment by Ikxyz** [comment]
**I had the same error, this solved it for me. hope it helpful**


`pm2 kill`
`pm2 start app.js`

**Comment by krishnaUIDev** [comment]
> **I had the same error, this solved it for me. hope it helpful**
> 
> `pm2 kill`
> `pm2 start app.js`

It didn't solve my issue. Looks like if pm2 didnot find config path its giving this error.

**Comment by webarthur** [comment]
I just include in my process.json the **NODE_CONFIG_DIR** entry:

```
{
  "name" : "app",
  "script" : "/root/app/index.js",
  "env" : {
    "NODE_ENV": "production",
    "NODE_CONFIG_DIR": "/root/app/config/"
  }
}
```

It work's for me. I adapted this solution from:
https://stackoverflow.com/questions/27585779/nodejs-sample-app-failing-to-startup-unable-to-find-config

The node-config documentation about **NODE_CONFIG_DIR**:
https://github.com/node-config/node-config/wiki/Configuration-Files#config-directory

@krishnaUIDev
