### ISSUE TITLE
Create *.d.ts definition file and register it in DefinitelyTyped repository

### ISSUE THREAD

**Issue by RWander** [lorenwest/node-config#247]
Please create the *.d.ts definition file and register it in DefinitelyTyped repository (https://github.com/borisyankov/DefinitelyTyped) like this: https://github.com/borisyankov/DefinitelyTyped/tree/master/configstore. It will be very useful for typescript developers.

**Comment by RWander** [comment]
I have created the definitions and made [pull request](https://github.com/borisyankov/DefinitelyTyped/pull/5799).

**Comment by lorenwest** [comment]
Is there anything that the lorenwest/node-config repo. needs to merge, or is this only for the borisyankov/DefinitelyTyped repo?

**Comment by RWander** [comment]
Only the borisyankov/DefinitelyTyped repo. So you can close this issue. I hope my pull request wil be merged to borisyankov/DefinitelyTyped.

**Comment by lorenwest** [comment]
Ok - thanks.

**Comment by Strate** [comment]
This is pretty old, but nowadays typescript support typedefinitions [packaged together with a library](https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html). Is it possible to bundle typescript definitions, would you accept a PR?

**Comment by lorenwest** [comment]
Which object would you create a typedefinition for? The config object is the only one we manage, and that's different on each system. Is there something I'm missing?

**Comment by Strate** [comment]
Just to move https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/config/config.d.ts to this repo,  providing "official" support for this.

**Comment by markstos** [comment]
I'm not currently using TypeScript, but more type-safety seems like a good idea. From reviewing the file, it appears that it would be low maintenance to maintain this. I'm in favor of adding it (but @lorenwest will decide).

**Comment by lorenwest** [comment]
I'm in favor of type safety as well, and will merge a pull request if someone creates one. I don't know enough about TS to fully understand the problems introduced by creating an object that doesn't conform to the config.d.ts file. The config object this library creates has many more elements than those listed in the [config.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/config/config.d.ts) file.
