### ISSUE TITLE
Can't found the config file when the app started from another directory!

### ISSUE THREAD

**Issue by yassine-khachlek** [lorenwest/node-config#250]
When i launch an application from another directory rather than the application directory, the config module is not able to found the config file.

Example when it work:
cd ~/app_directory
node bin/www

Example when it's not working:
node ~/app_directory/bin/www

Is there a way to make the config module refer to the config file with an absolute link to avoid that?

**Comment by markstos** [comment]
Yes, set NODE_CONFIG_DIR, as documented here: https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir

@lorenwest This is a Frequently Asked Question. I suggest we add some documentation about it to the main README file. What do you think?

**Comment by lorenwest** [comment]
The README file is more of an introduction page, whereas the wiki is there for these details when you're using node-config.


@yassine-khachlek - Which pages did you review when learning node-config?  Would this information have come in handy in the context of reading about config files?  Would you have been confused if this environment variable were introduced in the README?  Where would you like to see this?

**Comment by yassine-khachlek** [comment]
Thanks for the fast reponse, problem resolved. I haven't readed the wiki :), just missed it. But for important detail like this, i think it should be present in https://www.npmjs.com/package/config, it's there where every body start to know how to use it.
