### ISSUE TITLE
Initialize module with NODE_CONFIG_DIR?

### ISSUE THREAD

**Issue by klinquist** [lorenwest/node-config#251]
Hi @lorenwest, thanks for a great module.

I currently use it for an internal module, so I set process.env.NODE_CONFIG_DIR to "node_modules/<internalModuleName/config"

This is hacky and may prevent any primary node application that uses this internal module from using config.

I *also* want to use it in a SUB internal module.

All of these issues could be fixed if I could initialize the module with the config dir instead of setting it in NODE_CONFIG_DIR.

var config = require('config')({NODE_CONFIG_DIR: __dirname + "/config"});  would be awesome.

I could submit a quick PR, would this be of interest to you?

**Comment by lorenwest** [comment]
Hello @klinquist, would this pattern work for you?

```javascript
process.env.NODE_CONFIG_DIR= __dirname +'./config';
var myConfig = require('config');
```

Unfortunately we aren't able to add a constructor argument to node-config as you've suggested, because loading the module loads the configs.  Running a constructor function would require the module to be loaded, and by then it's too late.

**Comment by klinquist** [comment]
Hi @lorenwest, that works for one... but not for sub-modules...

I was coding while I saw your reply come in :).

Are there any issue with returning a function that returns the constructor instead of returning the constructor directly?     (There probably are, but my PR seems to be working for me)

https://github.com/lorenwest/node-config/pull/252

**Comment by lorenwest** [comment]
There's a good discussion of the issues revolving sub-modules and having different configurations for submodules here: https://github.com/lorenwest/node-config/issues/201

Would the resolution listed in https://github.com/lorenwest/node-config/issues/225 serve your needs?  We still haven't had a PR on that one, and I'm unlikely to get to it soon, so anyone that wants to chip in is welcome to...

**Comment by markstos** [comment]
This looks like a variation of the "submodule configuration" issue. Closing this since we have #201 and #225 and there's no further follow-up from the OP here.
