### ISSUE TITLE
config.get('barf.blah') triggers `TypeError: Cannot redefine a property of an object with external array elements`

### ISSUE THREAD

**Issue by alash3** [lorenwest/node-config#253]
Hi, I'm trying something simple I've done before and I'm getting a crazy error that really surprises me:

```
.../node_modules/config/lib/config.js:534
    Object.defineProperty(object, propertyName, {
           ^
TypeError: Cannot redefine a property of an object with external array elements`
```

All I'm doing is calling get on the config object:

`config.get('barf.blah');`

Any idea what is going on? I imagine that my application is mutating the config somewhere after it has been accessed by .get, because this error goes away if I set the environment variable `ALLOW_CONFIG_MUTATIONS=true` when booting the app. It would be great if I could easily find out where this was happening...

Any pointers would be much appreciated. Thanks!

**Comment by alash3** [comment]
Also noteworthy, I *can* use `config.get('barf.blah');`. It returns true and the application does not crash. Note also that I am using babel.

**Comment by lorenwest** [comment]
It appears that ```barf.blah``` may be an ES6 typed array - something like this:
```
let x = new Uint8Array([1, 2])
```
Is that the case?

**Comment by lorenwest** [comment]
The error is happening on the first ```get()```, which unless you set the ```ALLOW_CONFIG_MUTATIONS=true``` is attempting to make the values of all elements in the config object immutable.

If it runs across one of these typed arrays, apparently V8 doesn't like to make them immutable.  Search for ```Cannot redefine a property of an object with external array elements``` for more information on the issue.

Babel may be turning a simple array (something I try to stay away from in configs) into an ES6 typed array.  

Are you using NodeJS 4?

**Comment by alash3** [comment]
I am running v0.12.7; I do have an array in my config though.

**Comment by markstos** [comment]
@alash3, what file format if the related configuration stored in?

**Comment by alash3** [comment]
js - I'm not doing any defers or anything; I'm actually switching everything to JSON to try and avoid a race condition of the config getting evaluated, made immutable, and accessed.

**Comment by markstos** [comment]
Interesting. Let us know if the issue persists once the config files are in JSON format.  Note that `node-config` allows JS-style comments in the JSON config files. We strip out the comments before checking to see if we can parse them as valid JSON.  

(Though I use .js files for config files as do many others, and I think this is the first we've heard of this exception being triggered). 

If you are able to create a reduced-test-case which triggers the issue that you could add to our test suite, that would be helpful.

**Comment by alash3** [comment]
Yeah, absolutely. Thanks for the quick response to this. I will try to put together an example of it happening.

**Comment by alash3** [comment]
Found out what is causing the error. Take a look:

https://github.com/alash3/node-config-bug

I have to run now, but I can circle back in a bit. Thanks again.

**Comment by lorenwest** [comment]
Hi @alash3, thanks for putting that together.  I downloaded it and see the problem.  The ```client-sessions``` library is placing a few things into the config object:
```
{ session: 
   { cookieName: 'session',
     requestKey: 'session',
     duration: 86400000,
     activeDuration: 300000,
     secret: 'shhhhhh',
     cookie: 
      { ephemeral: true,
        httpOnly: true,
        secure: false,
        secureProxy: false },
     encryptionAlgorithm: 'aes256',
     signatureAlgorithm: 'sha256',
     encryptionKey: <SlowBuffer 49 dd bc 83 eb bb 0f b2 05 04 8e 87 ef 98 cd 64 36 3d b1 a0 9c 9e 3a fd cb 42 a3 7b 9e 04 71 57>,
     signatureKey: <SlowBuffer 9c ac 0b aa b3 fd 06 ba b6 09 7d 4b e5 0c 8d 74 0c 7c a3 26 53 ee 41 65 e1 dd 7c 33 20 0a 45 b6> },
  daemons: { http: { enabled: true }, https: { enabled: true } } }
```

The ```SlowBuffer``` items placed into config aren't able to be made immutable.

Do you think we should change node-config to ignore these errors (allowing these items to be mutable), or is there another object you could be putting the SlowBuffer objects into other than the config object?

**Comment by alash3** [comment]
Thanks for looking into that, I incorrectly thought that client-sessions might be doing the key derivation asynchronously and mutating the config object after the fact.

It is possible to explicitly set the encryption and signature keys for client-sessions with a regular Buffer object. Do you know if regular Buffer objects can be made immutable? Reading up on the docs about Buffer and SlowBuffer, it sounds like they are basically the same thing, but I'm not sure if the un-pooled factor is involved. Just curious  - if you know off the top of your head, what does node-config use to make objects immutable? If you don't know, no worries, I can find it!

In response to your question, I do not recommend silently allowing these to be mutable while the rest of the config object is made immutable. However, if possible, it would be great to know what part of the config is not able to be made immutable, so that it can be dealt with as needed. The error message I was getting gave no indication it had to do with client-sessions, or a SlowBuffer object. Even that hint would be really helpful.

**Comment by markstos** [comment]
@alash3: I agree on that point that it would nice if detected the elements
that we can't make immutable, and provided a more helpful diagnostic
message in that case.

On Thu, Oct 22, 2015 at 12:40 PM, alash3 <notifications@github.com> wrote:

> Thanks for looking into that, I incorrectly thought that client-sessions
> might be doing the key derivation asynchronously and mutating the config
> object after the fact.
>
> It is possible to explicitly set the encryption and signature keys for
> client-sessions with a regular Buffer object. Do you know if regular Buffer
> objects can be made immutable? Reading up on the docs about Buffer and
> SlowBuffer, it sounds like they are basically the same thing, but I'm not
> sure if the un-pooled factor is involved. Just curious - if you know off
> the top of your head, what does node-config use to make objects immutable?
> If you don't know, no worries, I can find it!
>
> In response to your question, I do not recommend silently allowing these
> to be mutable while the rest of the config object is made immutable.
> However, if possible, it would be great to know what part of the config is
> not able to be made immutable, so that it can be dealt with as needed. The
> error message I was getting gave no indication it had to do with
> client-sessions, or a SlowBuffer object. Even that hint would be really
> helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/issues/253#issuecomment-150283514>
> .
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos

**Comment by roccomuso** [comment]
I'm having a similar behavior, trying to do: <code>config.has('platform.host')</code>


        throw new Error('Configuration property "' + property + '" is not defined');
    
        Error: Configuration property "host" is not defined
        at Config.get (/home/ubuntu/Desktop/prove-tempo/node_modules/config/lib/config.js:178:11)
        at Object.<anonymous> (/home/ubuntu/Desktop/prove-tempo/lettura-config.js:9:24)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Function.Module.runMain (module.js:441:10)
        at startup (node.js:139:18)
        at node.js:968:3


Is it a desired effect?

**Comment by markstos** [comment]
Rocco,

What you are experiencing with config.has is different. `config.has` is
documented to return onl try or false, not throw exceptions:

https://github.com/lorenwest/node-config/wiki/Common-Usage#testing-for-config-values

If `config.has` is not working as expected, please file a new bug report
that includes a failing test to illustrate your case.


On Fri, Apr 29, 2016 at 6:50 AM, Rocco Musolino <notifications@github.com>
wrote:

> I'm having a similar behavior, trying to do: config.has('platform.host')
>
>     throw new Error('Configuration property "' + property + '" is not defined');
>
>     Error: Configuration property "host" is not defined
>     at Config.get (/home/ubuntu/Desktop/prove-tempo/node_modules/config/lib/config.js:178:11)
>     at Object.<anonymous> (/home/ubuntu/Desktop/prove-tempo/lettura-config.js:9:24)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3
>
> Is it a desired effect?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/issues/253#issuecomment-215682971>
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos

**Comment by markstos** [comment]
Rocco,

But from what you pasted, it appears may be you called `config.get`, not
`config.has`.    `config.get` *is* supposed to throw exceptions on
undefined keys, as it indicates a problem with the configuration. Set the
value to null if you want it to be defined-but-empty and not throw an
exception

On Fri, Apr 29, 2016 at 10:22 AM, Mark Stosberg <mark@rideamigos.com> wrote:

> Rocco,
>
> What you are experiencing with config.has is different. `config.has` is
> documented to return onl try or false, not throw exceptions:
>
>
> https://github.com/lorenwest/node-config/wiki/Common-Usage#testing-for-config-values
>
> If `config.has` is not working as expected, please file a new bug report
> that includes a failing test to illustrate your case.
>
>
> On Fri, Apr 29, 2016 at 6:50 AM, Rocco Musolino <notifications@github.com>
> wrote:
>
>> I'm having a similar behavior, trying to do: config.has('platform.host')
>>
>>     throw new Error('Configuration property "' + property + '" is not defined');
>>
>>     Error: Configuration property "host" is not defined
>>     at Config.get (/home/ubuntu/Desktop/prove-tempo/node_modules/config/lib/config.js:178:11)
>>     at Object.<anonymous> (/home/ubuntu/Desktop/prove-tempo/lettura-config.js:9:24)
>>     at Module._compile (module.js:409:26)
>>     at Object.Module._extensions..js (module.js:416:10)
>>     at Module.load (module.js:343:32)
>>     at Function.Module._load (module.js:300:12)
>>     at Function.Module.runMain (module.js:441:10)
>>     at startup (node.js:139:18)
>>     at node.js:968:3
>>
>> Is it a desired effect?
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/lorenwest/node-config/issues/253#issuecomment-215682971>
>>
>
>
>
> --
>     Mark Stosberg
>     Senior Systems Engineer
>     RideAmigos
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos

**Comment by roccomuso** [comment]
@markstos thank you for the quick reply. Yeah I've misunderstood something that I've figured out just 2 minutes after having published my comment. That's why I've deleted it.

**Comment by dcolens** [comment]
FYI: I'm getting this error with v1.0.22 and not v1.0.21, it happens in a module that uses extendDeep.
```
/src/node_modules/config/lib/config.js:1420
        Object.defineProperty(mergeInto, prop, Object.getOwnPropertyDescriptor(Object(mergeFrom), prop));
               ^

TypeError: Cannot redefine property: url
    at Function.defineProperty (native)
    at /src/node_modules/config/lib/config.js:1420:16
    at Array.forEach (native)
    at util.extendDeep (/src/node_modules/config/lib/config.js:1400:9)
```

**Comment by jlabonski** [comment]
Seems to be rearing its ugly head for me as well.

`server.js:51` is the first call to `config.get()`.

Running node 7.10.0, config 1.26.1.


```
> redacted@0.1.0 start /Users/jlabonski/projects/redacted/rest
> node server.js

/Users/jlabonski/projects/redacted/rest/node_modules/config/lib/config.js:543
      Object.defineProperty(object, propertyName, {
             ^

TypeError: Cannot redefine property: 0
    at Function.defineProperty (<anonymous>)
    at Config.util.makeImmutable (/Users/jlabonski/projects/redacted/rest/node_modules/config/lib/config.js:543:14)
    at Config.util.makeImmutable (/Users/jlabonski/projects/redacted/rest/node_modules/config/lib/config.js:551:14)
    at Config.util.makeImmutable (/Users/jlabonski/projects/redacted/rest/node_modules/config/lib/config.js:551:14)
    at Config.util.makeImmutable (/Users/jlabonski/projects/redacted/rest/node_modules/config/lib/config.js:551:14)
    at Config.util.makeImmutable (/Users/jlabonski/projects/redacted/rest/node_modules/config/lib/config.js:551:14)
    at Config.get (/Users/jlabonski/projects/redacted/rest/node_modules/config/lib/config.js:187:12)
    at Object.<anonymous> (/Users/jlabonski/projects/redacted/rest/server.js:51:39)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/jlabonski/.nvm/versions/node/v7.10.0/bin/node" "/Users/jlabonski/.nvm/versions/node/v7.10.0/bin/npm" "run" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redacted-rest@0.1.0 start: `node server.js`
npm ERR! Exit status 1
```

**Comment by fantapop** [comment]
I think i ran into something similar.  in my config file which is js I was using ```fs.loadFileSync()``` to load one of the values.  The fact that this was returning a Buffer seemed to cause issues with ```util.makeImmutable```.  

I was originally setting ```"ALLOW_CONFIG_MUTATIONS": true```  to bypass this issue until I dug a little deeper and found that if I coerced the value to a string, it didn't fall to the same issues.

for reference, here was the stack trace I was seeing on the first call to config.get()

```
TypeError: Cannot redefine property: 0
    at Function.defineProperty (<anonymous>)
    at Config.util.makeImmutable (/Users/chris/Development/redacted/node_modules/config/lib/config.js:543:14)
    at Config.util.makeImmutable (/Users/chris/Development/redacted/node_modules/config/lib/config.js:552:14)
    at Config.util.makeImmutable (/Users/chris/Development/redacted/node_modules/config/lib/config.js:552:14)
    at Config.get (/Users/chris/Development/redacted/node_modules/config/lib/config.js:187:12)
```

**Comment by leoj3n** [comment]
It looks like [`tls.createSecureContext`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) which is part of the options object accepted by [`https.createServer`](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) will accept a `cert` or `key` of type `<string> | <string[]> | <Buffer> | <Buffer[]>` which means we can coerce the Buffer to a String like so in `development.js`:

```js
const fs = require('fs');
const path = require('path');

module.exports = {
  key: fs.readFileSync(path.resolve(__dirname, '../ssl/key.pem')).toString('utf8'),
  cert: fs.readFileSync(path.resolve(__dirname, '../ssl/cert.pem')).toString('utf8'),
};
```

This is working for me with `https.createServer`:

```js
https
  .createServer(
     {
      key: config.get('key'),
      cert: config.get('cert'),
    },
    app
  )
  .listen(config.get('port'), () => {});
```

**Comment by lorenwest** [comment]
This is a good discussion on usage of the library. As it's not a bug, let's move further discussion to [StackOverflow](https://stackoverflow.com/questions/tagged/node-config), and keep github issues confined to bugs and feature requests.
