### ISSUE TITLE
Customize file loader order

### ISSUE THREAD

**Issue by mikehaas763** [lorenwest/node-config#254]
I've searched and found somewhat related issues such as #201 and the issues it is linked to.

I'm building up a reusable npm package to be used internally for a build process. A consumer of the build process would just npm install --save-dev org-build-process and set up a basic gulpfile that uses modules in the package.

To configure the build process I would like the consumer to also be able to create the config files in the root of their project (not in the config dir). I would also like to have the names changed and loaded according to some sort of parameter input which may be an environment variable or may be something defined in a code path.

With the following files, config.json would be loaded in any case and then depending on the parameter input a corresponding .{env}.json would get loaded and merged to override the defaults. Does node-config support this use case today?

* config.json
* config.dev.json
* config.qa.json
* config.qa2.json
* config.prod.json

**Comment by lorenwest** [comment]
You may be able to do this with node-config through creative use of environment variables or by forking node-config, but I don't recommend it.

Consistency is important with configurations.  If anyone other than yourself is to work with your app, having a consistent place to store your configurations and a consistent naming pattern will allow that person to find their answers using google vs calling you at 3am.

Node-config hovers around 125,000 installs per month.  Lots of people understand node-config, and know just where to look for configurations and the environment variables to use.

**Comment by mikehaas763** [comment]
Thanks I appreciate the detailed answer. I'll have to find another solution being that it doesn't do it out of the box.

> Lots of people understand node-config, and know just where to look for configurations and the environment variables to use.

Totally fair and I get that. I'm trying to use node-config within my own library though and whether node-config or something else is being used is of no concern to the consumers of my lib.

> Consistency is important with configurations. If anyone other than yourself is to work with your app, having a consistent place to store your configurations and a consistent naming pattern will allow that person to find their answers using google vs calling you at 3am.

Which is why I'm setting up my lib to *consistently* look for config files in the root of a consumer's project :smile:. Just because node-config has a convention doesn't mean it's the only convention.
