### ISSUE TITLE
Weird behaviour when using local.json

### ISSUE THREAD

**Issue by Hanspagh** [lorenwest/node-config#255]
I currently use a 4 environments dev, prod, test, and local-test. If a create a config file called local-test or even local. This overrides all other configurations files and forces my application to use local.json even when I set an other node_env. If I remove local or rename to something else etc. stage everything is working as intended.

**Comment by markstos** [comment]
`local` has a special purpose in `node-config` and should not be used as NODE_ENV value. See 
https://github.com/lorenwest/node-config/wiki/Configuration-Files to check the file load order and see that local is used for overrides. 

I ran into a version of this myself, and ended up renaming my "local" file to "laptop" to avoid the conflict.

**Comment by Hanspagh** [comment]
Cool, thanks for the heads up.
