### ISSUE TITLE
wish: config file generation tool

### ISSUE THREAD

**Issue by markstos** [lorenwest/node-config#257]
We have a complex configuration and we set up new instances with unique configurations frequently. 

I'd like a tool that makes it easy to spit out new configuration file with minimal overrides of the default file.  This might be a CLI or web app. 

I envision a kind of "quiz" format that prompts a user for several required and optional fields, perhaps allowing the inclusion of several common configuration alternatives.

We may end doing something custom for our use case, but it seems there's a general utility as well, to move configuration file generation from a developer's task to something that could be done by a support team or sales team.

I'll work on this some myself if I have time.

**Comment by lorenwest** [comment]
Hey Mark,

I suggest creating this in an independent NPM module, and linking to it from this module. Like express, if it becomes a core part of the module it can be included from here.

-Loren

**Comment by markstos** [comment]
@lorenwest, you are right. Closing this here.
