### ISSUE TITLE
Escaped Quotes in JSON break

### ISSUE THREAD

**Issue by adityabansod** [lorenwest/node-config#259]
Hi there --

This recent PR (https://github.com/lorenwest/node-config/pull/258) caused escaped quotes inside of a JSON value to break parsing.

e.g. 

```json
"patientApptOffer": "<a href=\"http://localhost:3000/offers/reply?id={{system.contact.value}}\">Test String</a>",
```

gets parsed to 
```json
"patientApptOffer": "<a href=\"http:
```

which then blows up when `JSON.parse` gets its hands on it.

**Comment by lorenwest** [comment]
@elliotttf - Do you think I should pull back the escaping changes, or do you think you could get a change in to resolve this?

**Comment by lorenwest** [comment]
@adityabansod - would you mind adding a pull request for a test that fails in this scenario?

**Comment by adityabansod** [comment]
sure thing

**Comment by adityabansod** [comment]
here you go: https://github.com/lorenwest/node-config/pull/260
