### ISSUE TITLE
Nested config access

### ISSUE THREAD

**Issue by tomalex0** [lorenwest/node-config#262]
Is this possible in current scenario?
```
{
 "url" : "localhost",
"api" : {
   "test" : "config.url"
 }
}
```
then

`config.get("api.test")  = localhost`

**Comment by markstos** [comment]
It possible, but only when using JavaScript files for configuration. See:

https://github.com/lorenwest/node-config/wiki/Configuration-Files#javascript-module---js

**Comment by lorenwest** [comment]
I'm not sure what Mark's answer refers to, that looks like valid json or javascript.  However, if your question was more about the line
```
config.get("api.test") = localhost;
```
and if you're trying to set `api.test
