### ISSUE TITLE
Invalid value being returned for the key - watch

### ISSUE THREAD

**Issue by tusharmath** [lorenwest/node-config#269]
config: 

```coffee
module.exports =
  webpack:
    watch: false
```

trying to read the watch property returns a function instead of the the value  - `false`

**Comment by markstos** [comment]
What file format is that? It appears to be something that compiles to JavaScript. Have you checked the JavaScript that was generated. A more complete code example would be helpful.

The only way I'm aware that a function could be returned would be if a `defer` was used, and as an edge case, this value was process before the `defer` function was evaluated.  However, there would need to be other configuration files involved to trigger that besides what you've shown here. 

Try using different configuration file format, like a plain JavaScript file with a `.js` extension, and see if that triggers the issue.

**Comment by tusharmath** [comment]
@markstos Added a failing test.

**Comment by lorenwest** [comment]
This is a good catch.  The watch function was deprecated in node-config over a year ago, and I feel it's time for a major revision update - at least to remove deprecated functionality.

**Comment by lorenwest** [comment]
For context: Node-config has a handful of [Reserved Words](https://github.com/lorenwest/node-config/wiki/Reserved-Words) and `watch` is one of them.  Many of them are either deprecated or moved into a single `util` namespace.  Version 2.x will only have `get`, `has`, and `util` as reserved words.

**Comment by markstos** [comment]
+1 on a major release to remove deprecated functionality.

**Comment by markstos** [comment]
Releasing version 2 to deprecate this remains planned. Closing this.

**Comment by markstos** [comment]
Fixed in #2018 by removing the `.watch` method: https://github.com/lorenwest/node-config/pull/495
