### ISSUE TITLE
How to parse environment variables as boolean values?

### ISSUE THREAD

**Issue by yjwong** [lorenwest/node-config#272]
Hi,

I have the following `custom-environment-variables.json` defined.

```javascript
{
  "testMode": "TEST_MODE"
}
```

In my app, I have the following (test.js):

```javascript
'use strict';
let config = require('config');
console.log(typeof config.testMode);
```

When running `env TEST_MODE=false node test.js`, the code returns 'string', so it appears that everything passed in via custom environment variables are interpreted as just plain strings. Is there a way to let `node-config` handle the conversion? 

Thanks!

**Comment by lorenwest** [comment]
Environment variables are always strings, so this isn't a bug where `node-config` isn't correctly maintaining the type.  

As for adding type conversion to this library, I feel it's better suited for libraries designed for type conversion. This library is about managing configurations.

**Comment by markstos** [comment]
There are several npm packages available that provide functions that handle converting boolean-like strings to true boolean values. Using one of those is recommended. Here are some examples:

  * https://www.npmjs.com/package/yn
  * https://www.npmjs.com/package/to-bool
  * https://www.npmjs.com/package/to-boolean

**Comment by yjwong** [comment]
No worries, thanks for the links. The other workaround I've found was also to declare the boolean environment variables as JSON (using __name and __format), since `true` and `false` are accepted as tokens by the JSON parser (and are technically valid based on RFC 7159).

**Comment by knksmith57** [comment]
Apologies for unearthing a ~6 month old issue, but for posterity's sake, here's a full example of using environment variables & @yjwong's json trick to override boolean values:

```yaml
# config/default.yaml
my_option: true
```

```yaml
# config/custom-environment-variables.yaml
my_option:
  __name: 'MY_OPTION'
  __format: 'json'
```

```js
// index.js
const config = require('config')

if (config.get('my_option')) {
  console.log('do TRUE thing')
} else {
  console.log('do FALSE thing')
}
```

```sh
❯ node index.js
do TRUE thing

❯ MY_OPTION=false node index.js
do FALSE thing

❯ MY_OPTION=true node index.js
do TRUE thing
```

HT to @yjwong for this awesome find; it definitely saved my skin!

**Comment by markstos** [comment]
It's an important part of the trick that `my_option` is defined in `config/default.js`. If it was not calling `config.get` on it would throw an exception.

**Comment by letmaik** [comment]
FYI, I regularly trip over this and typically change my code to something like `if (config.get('var') === '1')` and make sure I use `"1"` everywhere. But I'd rather use booleans in the config files and whatever else in the environment variables, like `"1"` or `"0"` or `"true"`. The work-around above implements this perfectly, and I think this whole `__format` thing should be made more prominently and maybe another format added which is called `bool`.  It currently seems to be an undocumented feature that could break any time, so I can't use it in production code.

**Comment by markstos** [comment]
I don't think the use use `__name` and `__format` was even meant to a public feature. I see now someone [documented it on the wiki  last year](https://github.com/lorenwest/node-config/wiki/Environment-Variables/_compare/c8ee9e5bfb9bef609f5b8ba4c088cd468a9a80ff...aa9cc0b57d1d6493590fde1ba631b4ac793acea1). @lorenwest I'm in favor of removing that documentation.

**Comment by stalniy** [comment]
@markstos 

@leachiM2k added docs for `__name` and `__format` and as they are in docs (and only in one place inside code) I don't see any reason why it can't be public or why it should be an internal feature :)

**Comment by leachiM2k** [comment]
Hello, the only reason to use lodash-lodash notation was to avoid clashes with user defined config keys. Read it here: https://github.com/lorenwest/node-config/issues/211#issuecomment-97430064

Of course this feature was meant for the public use.

**Comment by jofftiquez** [comment]
For future readers.

Instead of using true or false just use `process.env.PROD='0'` and `process.env.PROD='1'` then parse 'em like `!!+process.env.PROD` the result will be boolean.

**Comment by dougrday** [comment]
It's simple with regular expressions:

const isTestMode = /true/i.test(process.env.SOME_BOOLEAN_VAR);

**Comment by stalniy** [comment]
@dougrday it's even simpler to test using equality ;)

`process.env.VAR === "true"`
