### ISSUE TITLE
Defaulting process.env.NODE_ENV to 'development'

### ISSUE THREAD

**Issue by loudwinston** [lorenwest/node-config#273]
Currently this package will use 'development' as the default for `NODE_ENV` if none is set in `process.env.NODE_ENV`

I'm curious what the reason for this is.  This behavior causes some problems with my team - when developing locally, we don't want to load the `development.js` that's used for our development environment because it has completely different values.  We've worked around this by having our values appropriate for local development in `development.js`, and creating `{hostname}-development.js` files for our development servers, but this seems like a suboptimal solution.

Perhaps we're doing something wrong?

**Comment by markstos** [comment]
My recommendation is to your build tool, like `gulp` or `grunt` to set the environment variable you want to use locally.  For example, my team uses `NODE_ENV=laptop` for local development.  Our default `gulp` command sets up the environment, starts the server and watches for changes. We also have a `gulp test` command which sets up a testing configuration and runs the tests. 

Would something like that work for your team?

**Comment by loudwinston** [comment]
Note that the differences between our local and development environments are due to disparity between the networks that our workstations and development servers run on.  We're trying to resolve that, which might make this issue moot for our case.  

However I'm still curious if anyone else has had similar problems and what the best approach is.  

I had the thought that there could be

**Comment by loudwinston** [comment]
@markstos Yeah that might work.  Let me discuss it with my team.  

Thanks for your quick reply!
