### ISSUE TITLE
Cannot use config with AWS Lambda

### ISSUE THREAD

**Issue by cyberwombat** [lorenwest/node-config#275]
I am working on an AWS lambda that makes use of the config module for node. The lambda log reports this error:

```
Unable to import module 'index': Error 
at Function.Module._resolveFilename (module.js:338:15) 
at Function.Module._load (module.js:280:25) 
at Module.require (module.js:364:17) 
at require (module.js:380:17) 
at Object.<anonymous> (/var/task/index.js:1:63) 
at Module._compile (module.js:456:26) 
at Object.Module._extensions..js (module.js:474:10) 
at Module.load (module.js:356:32) 
at Function.Module._load (module.js:312:12) 
at Module.require (module.js:364:17)
```
I have made the module as simple as possible:
```
require('config');

exports.handler = function(event, context) {
   context.done();
};
```
Removing the require statement makes it work. Other modules do not cause any issues. I have also tried changing config versions with no progress.

Here's the [module](https://github.com/trinketapp/aws-lambda-create-thumbnail) I was working off - evidently this used to work at some point.

Ideas?

**Comment by markstos** [comment]
Before the `require` line, try adding this:

```
process.env.NODE_CONFIG_DIR='/var/task/config';
```

And make sure you have valid config files in the "config/" directory of your project.

**Comment by cyberwombat** [comment]
After more testing I cannot use any 3rd party package with lambdas it seems. They all fail the same way so closing.

**Comment by markstos** [comment]
I'm sure what your particular situation is, but AWS explicitly supports using Node.js modules in Lamba functions: 

https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/

If it's not working for you, consider contacting AWS support.

**Comment by lorenwest** [comment]
If you're using Lambda to control your Amazon Echo, you're the winner.

**Comment by cyberwombat** [comment]
Solved. OSX makes `node_modules` readable only by the user so AWS cannot read it. Permissions need to be changed recursively in order for it to work. Not sure if all setups would do the same but I am using a `nvm` which may be the culprit.

**Comment by dmuth** [comment]
The directory has changed, so here's a more robust way to make the Node.js config module work under AWS Lambda:

```
process.env.NODE_CONFIG_DIR = process.env["LAMBDA_TASK_ROOT"];
```

-- Doug

**Comment by eduardonunesp** [comment]
The problem with my setup was because the zip wasn't configured for recursive, so de node_modules going empty. Don't forget to zip as `zip -r pack.zip *`

**Comment by markstos** [comment]
Or use a tool that runs zip for you, so you don't have to remember. I recommend `aglex`, but not there are some open bug reports. It could use more contributors. 

https://www.npmjs.com/package/aglex

http://mark.stosberg.com/blog/tech/review-of-nodejs-lambda-serverless/
