### ISSUE TITLE
Config file being loaded when it shouldn't

### ISSUE THREAD

**Issue by qspencer** [lorenwest/node-config#277]
Hi,

I have multiple config files in my "config" directory and the environment variable "NODE_ENV" is not set (nor are any of the other environment variables config supports). According to "getConfigSources" my node app is loading "default.json, development.json, and local.json". Based on the [documentation] (https://github.com/lorenwest/node-config/wiki/Configuration-Files) I understand why it's loading "default.json" and "local.json" but it seems like it shouldn't be loading "development.json". My system name doesn't start with "development" and when I run my app I just do "node <appname>.js". There are other config files that aren't being loaded so it's not like it's somehow loading all config files. Any insights into this issue would be appreciated.

**Comment by lorenwest** [comment]
Although it's not documented on the wiki, according to https://github.com/lorenwest/node-config/blob/master/lib/config.js#L633 the default for NODE_ENV is development.

If you don't want it to load the development.json file, just set NODE_ENV to anything else.

**Comment by markstos** [comment]
I added a note to
https://github.com/lorenwest/node-config/wiki/Configuration-Files to
document that the NODE_ENV defaults to `development`.

Even if we document elsewhere, it's useful to note here as well, as it is
related to the file-load order, which people may come to this page to learn
about or debug.

On Mon, Dec 21, 2015 at 12:26 PM, Loren West <notifications@github.com>
wrote:

> Closed #277 <https://github.com/lorenwest/node-config/issues/277>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/issues/277#event-497655242>.
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos
