### ISSUE TITLE
Question: Can I dynamically get access to configuration from different environments?

### ISSUE THREAD

**Issue by adelura** [lorenwest/node-config#281]
I mean something like this:

production.json
``` json
{
  "port": 3000
}
```

development.json
``` json
{
  "port": 4000
}
```

app.js
``` js
var config = require('config');

var productionConfiguration = config.util.getConfiguration('PRODUCTION');
var developmentConfiguration = config.util.getConfiguration('DEVELOPMENT');

console.log(productionConfiguration.get('port')); // 3000
console.log(developmentConfiguration.get('port')); // 4000
```

**Comment by lorenwest** [comment]
Sure.  It's shown on the [Examining Configuration Sources](https://github.com/lorenwest/node-config/wiki/Examining-Configuration-Sources) wiki page.

**Comment by adelura** [comment]
Thank you for quick response. Unfortunately it doesn't work as expected. When I run:

app.js
``` js
var config = require('config');
console.log(config.util.getConfigSources());
```

I have and output with only one configuration
``` js
[ { name: 'C:\\devrand\\config\\config\\development.json',
    original: '{\r\n    "port": 4000\r\n}',
    parsed: { port: 4000 } } ]
```

It seems reasonable to see two. This is strange, what do you think about it?

**Comment by markstos** [comment]
@lorenwest from my reading of the page you linked to, the experience of @adelura as I would expect. As I understand the docs for `getConfigSources()`, it shows the origin of the current configuration, but not all possible configurations. 

The only way I know to load a different configuration is to delete node-config from the module cache and load it again. The [node-config-uncached](https://github.com/MrBoolean/node-config-uncached) module helps with this.

To use it for your use case, set the environment variables for the first environment, and load node-config. Then reset the environment variables to reference the second configuration you want,  and load an "uncached" version of node-config.  I have not tested this. 

If it works, consider submitting to a PR to the `config-uncached` project to update the README there to note that possible use case.

**Comment by adelura** [comment]
@markstos Thanks, it works.

> If it works, consider submitting to a PR to the config-uncached project to update the README there to note that possible use case.

I would rather update [Examining Configuration Sources](https://github.com/lorenwest/node-config/wiki/Examining-Configuration-Sources) wiki page. And reference there to the module mentioned by you.

I think that the starting point, for someone who is trying achieve my case,  is a wiki of main repository, but not related ones.

**Comment by markstos** [comment]
@adelura OK. We also have a "Plugins" page which mentions the other module:

https://github.com/lorenwest/node-config/wiki/Plugins
