### ISSUE TITLE
default.json being read rather than NODE_ENV value

### ISSUE THREAD

**Issue by PorridgeBear** [lorenwest/node-config#283]
I am deploying via Capistrano. I have config/default.json and config/uat.json both equivalent in structure with uat.json specifying some custom vars. When the script is being started up it is taking the code path that is configured by default.json's values and not uat.json.

In Capistrano's config I create a custom environment var NODE_ENV=uat. When Capistrano deploys it executes my node script using /usr/bin/env:
```
/usr/bin/env cd /var/www/myapp/releases/20160112134909/ && forever start -p /var/www/myapp/shared/ --pidFile /var/www/myapp/shared/server.pid myapp.js
```
Running /usr/env/bin in the CLI shows correctly:
```
NODE_ENV=uat
```
as does echo $NODE_ENV.

I created a test.js file on the same server and within it added:
```
 console.log(process.env.NODE_ENV) 
```
This, too, outputs uat.

So all in all this seems right from the NODE_ENV side but uat.json is not being merged over default.json.

Tips/advice appreciated!

**Comment by PorridgeBear** [comment]
I just ran 
```
node myapp.js
```
to test directly running outside of forever and this appears to have taken the uat.json.

So the issue appears to be perhaps how forever is running things though unclear why.

**Comment by lorenwest** [comment]
To be clear, default.json is always read and uat.json will be merged over
default.json if NODE_ENV=uat.  Maybe the variable wasn't exported?

export NODE_ENV=uat

Other than that, I'd recommend sending NODE_ENV to console.log in your app
to see what it thinks it is.

**Comment by markstos** [comment]
Issue appears to be external to node-config, so closing this. 

Re-open if there appears to be a node-config bug.
