### ISSUE TITLE
Setting value to File Path

### ISSUE THREAD

**Issue by vipreshjha** [lorenwest/node-config#285]
I have a all my configurations in default.json . Now there are some setting values which are very big I want these values to be loaded from different file  for e.g. 
{
  "serving" : {
     "partnerIP" : {
        "partner1: {
            "ips" : ["127.0.0.1",  "127.0.0.1","127.0.0.1"]
         }
      }
  }
}
Now in the above e.g. there are other other settings also apart from the partner-IP setting and the partner-IP setting is big list, I want the value of this list to come from other file whose path or name I specify as its value and the configuration loads the value from the file and gives to me as one unified view.
So for eg. I can have partner1-ips.json as 
{
"ips" : ["127.0.0.1",  "127.0.0.1","127.0.0.1"]
}

And then in default.json
{
  "serving" : {
     "partnerIP" : {
        "partner1: {
            "ips" : partner1-ips.json
         }
      }
  }
}

Of course the "ips" property can be marked with special flag which indicates it value to be loaded from different file.
Is this possible currently?

**Comment by markstos** [comment]
Our [Configuration Files](https://github.com/lorenwest/node-config/wiki/Configuration-Files) page documents all the different config files we load and in what order. That's one possibility for splitting up your config files.

We don't have built-in support for adhoc file loading and have no plans to add it. 

What we *do* support is using JavaScript config files with a `*.js` extension. In those, you can do anything you can do in  Node.js, including loading further configuration data from other JSON files. That sounds like it may be the best fit for your case.
