### ISSUE TITLE
Environment Variables substitution clearing parent object values

### ISSUE THREAD

**Issue by nickythorne** [lorenwest/node-config#286]
I'm using the custom environment variable feature to pull datasource credentials from pre-defined environment variables. However, I'm experiencing unexpected behavior when the config object get's merged with the JSON object defined in the env variable.

Currently, it seems that the parent object properties get truncated when the child object is merged. For example:

_default.json_
`{
  "dataSource" : {
	"type": "mongodb",
    "credentials" : {}
  }
}`

_custom_environment_variables.json_
`{
  "dataSource" : {
    "credentials" : {
      "__name": "MONGODB_CONFIG",
      "__format": "json"
    }
  }
}`

The _default.json_ configuration defines a `config.dataSource.type` property which gets deleted when `config.dataSource.configuration` is assigned the environment object.

**Comment by lorenwest** [comment]
The type property shouldn't be deleted.  Could it have something to do with the missing comma between `"mongodb"` and `"credentials"`?

**Comment by markstos** [comment]
No further follow-up from OP-- closing.
