### ISSUE TITLE
Question: what's the simplest way to split one huge config file to several small ones?

### ISSUE THREAD

**Issue by umaxfun** [lorenwest/node-config#287]
Hello,

I have a problem of project config file becoming really huge, around 500 lines for now. It is split into tens of objects regarding various components: one for general db access, one for elasticsearch, one for rabbit, one per complex project component and so on. E.g.:
```json
{
  "integrations":{
    "db":{
      "host":"dbhost.example.com",
      "port":"12345",
      "some": "value",
      ...
    },
    "rabbit":{
      "host":"rabbithost.example.com",
      "port":"12346",
      "some": "value",
      ...
    },
    "some_more_data":{
      ...
    },
   ...
  },
  "env":{
  {
    "one_kind_of_ioc":{
      ...
    },
    "another_kind_of_ioc":{
      ...
    }
  }, ...
}
```

It would be great to split them to some 10 files like data_access.json, one_kind_of_ioc.json, another_kind_of_ioc.json and so on and have a default.json file like this:
```json
{
  "integrations": {
    "db":"$include data_access.json"
  },
  "env": {
    "one_kind_of_ioc": "$include one_kind_of_ioc.json",
    "another_kind_of_ioc": "$include another_kind_of_ioc.json"
  }
}

```

A must here is this mystical $include directive to respect naming conventions about NODE_APP_INSTANCE and all other config file selection rules.

**Comment by markstos** [comment]
node-config will load a number of files in a specific order, as documented here:
https://github.com/lorenwest/node-config/wiki/Configuration-Files

Beyond that, you are on your own. 

My "default.js" has grown to over 1,600 lines. 

Frankly, I like having a master config file with everything in it. It has a main section for the top level configuration, and then sections like `config.email = { ... }` and `config.database = { ... }`;

With one big file, to find a section, you open the file and grep it. With one several files, to find a section,  you can grep all the files to find the section you want, then open one.  Similar effort either way.

With JavaScript based include files, you can use the built-in filesystem access to load and include other files if you'd like.
