### ISSUE TITLE
allow custom loading

### ISSUE THREAD

**Issue by jchip** [lorenwest/node-config#290]
I'd like to make modules that can use node-config to load internal configs base on NODE_ENV.

so my app do this:

```
process.env.NODE_CONFIG_CUSTOM_LOADING=true;
var config = require("config").default;
```

in a module:

```
var config = require("config").load( "../config" );
```

**Comment by lorenwest** [comment]
This is easy to do without modification:

default.js
```
module.exports = {
  someConfig: require('../custom-config.json'),
  someOtherConfig: require('./another-custom-config.json')
}
```
Would that do what you're after?

**Comment by jchip** [comment]
I want to use node-config's NODE_ENV composing in the module also.

**Comment by lorenwest** [comment]
This shouldn't reduce the `NODE_ENV` composing capabilities.  For example, with the `default.js` shown above, if your `NODE_ENV=production` your production.js would still be able to override, even load external overrides:

production.js:
```
module.export = {
  someConfig: require('../custom-production-overrides.json'),
  someOtherConfig: {
    host: "some-production-override-host.com"
  }
```

**Comment by jchip** [comment]
node-config automatically look for config under CWD/config or NODE_CONFIG_DIR.  What I'd like to do, is have a separate config dir in my module, with its own config dir, that has `default.js`, `production.js`, and `development.js`, and in my module's code, use node-config to load those config files, by doing in a JS file in `lib`:

`var config = require("config").load( __dirname + "../config")`

which returns a config that's different than the default one loaded from `NODE_CONFIG_DIR`.
