### ISSUE TITLE
Checking configuration file for missing entries?

### ISSUE THREAD

**Issue by jpetitcolas** [lorenwest/node-config#291]
Hi there,

We have regularly some issues on our production server, when we forget to update our production configuration file with newest keys. I'm wondering if you have any method or existing tools to check automatically a remote configuration to the local one, ensuring all keys are present?

Thanks for your help! :)

**Comment by markstos** [comment]
Here some patterns that we use:

 * `config/default.js` contains every single key used in every single configuration. If there is no sensible default, but the key is required the value is set to `undefined`. Unlike setting the value to `null`,   calling `config.get(undefined)` will throw an error, allowing you to find a mistake immediately. (We also track exceptions and get email notifications about them). 
 * We also have test in our test suite that loads every configuration and checks that particular critical keys are present.
* Keep *All configurations* in one place, under source control. Have config changes peer reviewed along with other changes
* Sensitive "Production only" only values are kept in environment variables. As exception, those values exist only in production, but at least for us are rare compared to the common case.
