### ISSUE TITLE
Regression: handling of null vs undefined values. 

### ISSUE THREAD

**Issue by markstos** [lorenwest/node-config#293]
The question here is about whether `null` and `undefined` should be treated the same in `config.has` and `config.get`.

The earliest mention I can find of `config.has` is back in [issue #109](https://github.com/lorenwest/node-config/issues/109). Unfortunately, this didn't address the issue, as the language use was 'exists', which is ambigous as to whether it might mean `undefined`, `null` or both.

However, the [original code](https://github.com/lorenwest/node-config/commit/029ee727d660886c2f9a4b37c8b2113ad6ef001c) and in-line documentation were clear about the intent. `config.get` only threw an exxception for definedness and `config.has` only checked for that.  The in-line documentation still says: *"This will return the specified property value, throwing an exception if the configuration isn't defined. "* (Even though this doesn't match the behavior anymore.

Our current user-facing documentation is inconsistent on the issue. The README is clear that only *undefined* keys trigger an exception: *"config.get() will throw an exception for undefined keys to help catch typos and missing values. Use config.has() to test if a configuration value is defined."*

[Our wiki page for "Common usage"](https://github.com/lorenwest/node-config/wiki/Common-Usage#using-config-values)
 doesn't mention that `get` can throw exceptions and documents `has` the vague language of "exists" rather than something more precise.

The issue was discussed recently in [#278](https://github.com/lorenwest/node-config/issues/278) where I was clear with a user about what I /thought/ the correct behavior is: That `undefined` is used represent that a value truly is `undefined`. It's a good choice to put in a default.js file for a value that /must/ be overrriden.  `null`  is used to represent that a value has explicitly been defined but with an empty value. In other words, `null` can satisfy that a value is required without providing a value.

But over time, both `get` and `has` were updated to treat `undefined` and `null` the same.

[`config.get` was patched to also throw on null values](https://github.com/lorenwest/node-config/commit/2258d0ad894a4b004ff4f5ce1a2db9b228c7b2b7).

A few hours later, I [patched `has`](https://github.com/lorenwest/node-config/commit/45d3592d34ae4fa0bbd8fac73fd860c55c4782d0) for consistency.

I now consider these changes I regression. I think the behavior should be:

 * config.get should only throw on undefined values.
 * config.has should should return false only if a property is undefined.
 * All docs: in-line, README and wiki should be consistent is describing this, and the use of the vague `exists` word should be removed.

Even if we ultimately disagree about the correct behavior, let's at least use this ticket to make sure all our docs about this are clear and consistent.

CC: @robludwig who was involved in patching `config.get` for the behavior change.

**Comment by markstos** [comment]
@robludwig grab me to show me what I was missing. `get` and `has` were patched to change now they handle /input/-- the config key names-- not the config key /values/ that I was concerned about. They were  patched so these cases now throw nice errors:

  `config.get(null)`
  `config.get(undefined)`

And these cases return false:

 `config.has(null)`
 `config.has(undefined)`

That's good behavior. The code expects a config *key* to look up, and none was provided. 

I'm not sure the docs touch these cases at all. 

So the updated proposed scope of this ticket is just to make sure all our docs are consistent and complete about how null and undefined values are handled for `get` and `has`.

**Comment by robludwig** [comment]
I've updated the docs [here](https://github.com/lorenwest/node-config/wiki/Common-Usage#using-config-values). I believe the information is now accurate, please let me know if that's not the case.
