### ISSUE TITLE
How to use external source for configuration

### ISSUE THREAD

**Issue by joe-w** [lorenwest/node-config#297]
The documentation on getting configuration from external source is rather brief.
I'm trying to support external configuration for a cluster of servers, such that I can modify configuration centrally without needing to redeploy files to the servers.

I'd like to fetch configuration from an external source, so my local file only has bootstrap config - including, for example, the URL of the external config, and then I would fetch the more complete external config.

My question is what would be the necessary calls to extend the config.
It looks like to get proper behavior I'd need to call extendDeep() and attachProtoDeep(), push myself on configSources[], etc.

Would seem to be something that should be provided as a utility function, since otherwise I need to understand the internals.

And even then, this means my remote config overrides even local, explicit, command-line options, though that's really not my intent. I'd really like to somehow supply a function to provide a config that can be inserted into the loadFileConfigs() logic.

If anyone else is doing this already, I'd appreciate some pointers.
Thanks.

**Comment by lorenwest** [comment]
Early in the life of the node-config project we played with remote configuration and configs that changed throughout the lifecycle of the app.

We found to do this well required an increasing level of complexity. You will face issues of push vs. pull, central vs. distributed data, replication, server uptime, leader election, etc. We decided to keep node-config doing what it does well - static configurations that change between deployments, but remain stable throughout the life of the app.

My current favorite combination is node-config for deployment configs, and consul.io for remote configs that may change over the lifecycle of the app.  Once you read the consul.io ovreview you'll realize the pitfalls of remote configurations, and will appreciate using an industrial strength server.

**Comment by joe-w** [comment]
Thanks for the quick and informative response.
Guess we'll have to give this more thought. 😃

--> Joe W

**Comment by markstos** [comment]
I agree with Loren.  The simplest route is to have automation which generates static configuration files which `node-config` then uses. If  you need configs that change over the lifetime of the app, then supplement `node-config` with another tool that specializes in that.

**Comment by markstos** [comment]
#276 is a related conversation about loadFileConfig if you want to check it out.
