### ISSUE TITLE
Should I do require("config") in every file or pass down the config object?

### ISSUE THREAD

**Issue by pkyeck** [lorenwest/node-config#298]
Title says it all ... was wondering how I should do it. Any downsides on `require` in every file?

**Comment by markstos** [comment]
There is now downside to  `require('config')` in every file. Node.js caches the result of the require, so it's "cheap" after the first one.

**Comment by albertovasquez** [comment]
I just wanted to clarify, that @markstos meant no downside.  I took a double take when I first saw his post thinking he said there is now a downside :)

**Comment by markstos** [comment]
@albertovasquez you are correct. Thanks. I've updated my comment to reflect what I meant, and we'll now delete the follow the comments to avoid confusion.
