### ISSUE TITLE
Any timelines for version 2?

### ISSUE THREAD

**Issue by tusharmath** [lorenwest/node-config#300]
The reserved words are quite an issue. As per this doc — https://github.com/lorenwest/node-config/wiki/Future-Compatibility#version-20---not-before-july-2015 it would be release soon. Are there any updated timelines  for it?

**Comment by lorenwest** [comment]
I'm not quite sure how to respond to this. Not before July 2015 surely doesn't suggest a deliverable timeline, if there were such a thing in open source.

You seem to be a prolific open source contributor, how do you respond when someone makes demands for a feature or deliverable of your modules?

**Comment by tusharmath** [comment]
I sincerely apologies for my above comments. This was supposed to be more of a followup on #269 and #270. I would be more than glad to send a pull request with the changes.

**Comment by markstos** [comment]
Closing this, because the question about the timeline was answered. As @lorenwest said, pull requests for features on the roadmap are welcome.

**Comment by tusharmath** [comment]
I tried to make a pull request but unfortunately all the code is in one big huge monolithic file. Would it be alright if the project is first broken into multiple smaller utils? That way adding features would be much easier.

**Comment by lorenwest** [comment]
Yes, that would be a welcome change, as long as the spirit of the reorg was for reorg purposes only. That would make subsequent PRs easier to understand. The more you communicate your ideas and involve others in the discussion, the better chances of it being a smooth inclusion.
