### ISSUE TITLE
Submodule config loading

### ISSUE THREAD

**Issue by sushantdhiman** [lorenwest/node-config#303]
I have two express applications, they both contains `config` like this

```js
--App A
----config
----server
------index.js // require('App B index.js')
--App B
----config
----server
------index.js  // gets config from App A :(
```
If I try to include `App B`.`index.js` inside `App A`.`index.js` , `App B` code will load `config` from `App A`.

Is it possible for each application to still use their own config folder rather than inheriting from parent ?

**Comment by lorenwest** [comment]
At this time you can only have one config directory. This is a fairly often requested feature, so I'm hoping to either get the time to build it, or have it contributed.

**Comment by naholyr** [comment]
Workaround idea:

```js
process.env.NODE_CONFIG_DIR = path.join(__dirname, '..', 'config')
```

on top of both your ``server/index.js`` files. If you don't ``require('config')`` dynamically but only at startup, it should do the trick, nope?

**Comment by sushantdhiman** [comment]
Thats how I am managing it right now

``` process.env.NODE_CONFIG_DIR =  '../config' ``` worked for my case.

Although I have submitted a PR which will be able to retrace any parent `config` without changing ``` process.env.NODE_CONFIG_DIR ``` for each folder hierarchy
