### ISSUE TITLE
Migration to JS standard

### ISSUE THREAD

**Issue by tusharmath** [lorenwest/node-config#305]
Hi,
[StandardJS](http://standardjs.com/) is a pretty decent tool for avoiding all the bikeshedding related to linting JS projects.

I observed that there is no `.eslintrc` in the project nor are there any guidelines as to what is being currently followed. It would be great if we could just simply migrate to standard because adding changes right now creates way too many linting errors on my IDE (webstorm) and I am sure it happens with other devs as well.

Thanks.

**Comment by markstos** [comment]
This is the first time this has come up. You are welcome to create a PR that passes all the StandardJS checks so we can see what the differences look like.

**Comment by tusharmath** [comment]
Alright, this is a lot of work, let me give it a shot.

**Comment by vroudge** [comment]
Hello,

Just dropping by to say that StandardJS is not the standard at all as of now. The JS community has outbursted a lot against the owner of the repo which tries to imply that some choices on the JS coding style he's done in his repo are NOT standard at all. Wink wink semicolons.

One should refer to https://github.com/airbnb/javascript, for instance, or any other styleguide and its linter, that are consider much more knowlegeable in the industry.

Thanks for config, by the way, love it.

**Comment by tusharmath** [comment]
@vroudge I can not disagree with you here. feross/Standard apparently is more popular and its easy to get started with it because of the variety of tools that are already available. I think a better solution would be to add a `.eslintrc` file instead for this project.

**Comment by vroudge** [comment]
Airbnb-styleguide, for instance, is muuuuuuch more popular than Standard. No possible doubt, just check the npm packages for ESLint downloads/month, or just the stars on the github repo. :+1:

**Comment by tusharmath** [comment]
@vroudge I had not seen the stars/forks on github. Nevertheless, you have solid point and that's why I created https://github.com/lorenwest/node-config/pull/310.
