### ISSUE TITLE
Keeping 'deployment' separate from 'NODE_ENV'

### ISSUE THREAD

**Issue by mcmagi** [lorenwest/node-config#308]
Allow an application to specify a 'deployment' value using a different env variable instead of NODE_ENV.  (suggestion: NODE_APP_DEPLOYMENT)  This value can default to NODE_ENV if NODE_APP_DEPLOYMENT is not defined for backward compatibility or simpler projects.

I've been using node-config to manage the configuration of a large-scale node project deployed to multiple environments across several regions.  I've found the separation between 'deployment' and 'instance' to be incredibly useful, allowing me to segregate environment config via NODE_ENV from region particulars via NODE_APP_INSTANCE.  However the problem I've run into with using NODE_ENV in this way is that there are some environments where I want express.js to behave in 'production' mode (e.g. load-test or staging) without using the production environment config.

For example, it would be nice if I could do something like this:
  NODE_ENV=production
  NODE_APP_DEPLOYMENT=staging
  NODE_APP_INSTANCE=us
Which would then load from staging-us.EXT / staging.EXT instead of production-us.EXT / production.EXT.

The change looks rather simple, and I have an example of what I think it would be here (sans unit tests): https://github.com/mcmagi/node-config/commit/f6f279688106a03f41c41d4ab03cc55158a1f63f

**Comment by lorenwest** [comment]
Hi @mcmagi,

```NODE_ENV``` is the common environment variable for the very reason that other packages (specifically express.js) use it to mean the same thing. In your case where you want it to mean something different for different packages, I recommend doing something like this in your bootstrap script:

```
var prior_node_env = process.env.NODE_ENV;
process.env.NODE_ENV = process.env.NODE_APP_DEPLOYMENT;
var config = require('config');
process.env.NODE_ENV = prior_node_env;
```
As long as this is the first invocation of `require('config')`, your configs will be read from NODE_APP_DEPLOYMENT as you wanted.

Introducing additional environment variables comes with overhead, not only of writing the code and tests, but in communicating the nuance of the reason for using a non-well-known environment variable for deployment environment.
