### ISSUE TITLE
Load config files at the module it was created on

### ISSUE THREAD

**Issue by adonisv79** [lorenwest/node-config#311]
I am not sure if this feature exists or not, however using this module on our module, we have encountered that once our module is consumed by an app or another module, it is looking at the root app for the config information.

-Consumer Node App/Module
      |--config
      |        |--default.js (only this gets loaded)
      |
      |--node_modules
      |       |--config
      |       |--my_module
      |       |            |--config
      |       |            |        |--default.js (this does not get loaded)
      |       |            |
      |       |            |--node_modules
      |       |            |            |--config 
      |       |            |

I noticed in code that what happens is node-config looks at process.cwd() so even if the line of code triggering the first call to require('config') is the index.js of my_module, the config folder being looked into will be that of the root (Consumer Node App/Module). so for the time being I made a too adon-config as a basic tool for simple config handling that allows cascading loading of modules in cases where a module project will contain configuration files of its own which needs to be used by another module (which they can override), I will prefer if this module has that feature though so I just reuse this.

**Comment by markstos** [comment]
Hello,

Did you check out the other open issues before filing a new one?  Does one
of the existing open issues address what you are interested in?


   - Read submodule defaults from their own config directory (PR welcome)
   #225
   - Add env var to search additional config directories in order to
   override values found in $NODE_CONFIG_DIR #276
   - Submodule config loading #303
   - Find a solution to the multiple-instance problem for submodule
   defaults #226
   - Add env var to search additional config directories in order to
   override values found in $NODE_CONFIG_DIR #276




On Wed, Apr 20, 2016 at 9:43 PM, Adonis Lee Villamor <
notifications@github.com> wrote:

> I am not sure if this feature exists or not, however using this module on
> our module, we have encountered that once our module is consumed by an app
> or another module, it is looking at the root app for the config information.
>
> -Consumer Node App/Module
> |--config
> | |--default.js (only this gets loaded)
> |
> |--node_modules
> | |--config
> | |--my_module
> | | |--config
> | | | |--default.js (this does not get loaded)
> | | |
> | | |--node_modules
> | | | |--config
> | | |
>
> I noticed in code that what happens is node-config looks at process.cwd()
> so even if the line of code triggering the first call to require('config')
> is the index.js of my_module, the config folder being looked into will be
> that of the root (Consumer Node App/Module). so for the time being I made a
> too adon-config as a basic tool for simple config handling that allows
> cascading loading of modules in cases where a module project will contain
> configuration files of its own which needs to be used by another module
> (which they can override), I will prefer if this module has that feature
> though so I just reuse this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/issues/311>
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos

**Comment by markstos** [comment]
No further response from OP. Appears likely to be dupe, so closing. 

Re-open if there's something here which is not covered by one of the other mentioned tickets.
