### ISSUE TITLE
TypeError: mergeFrom.__lookupGetter__ is not a function (PR welcome)

### ISSUE THREAD

**Issue by thetalecrafter** [lorenwest/node-config#313]
Node v6 removed the non-standard `__lookupGetter__` method from `Object.prototype`. This causes an application with a default and environment specific config to immediately crash.

`Object.getOwnPropertyDescriptor(mergeFrom, prop).get` is the standard way to access the getter, and `Object.defineProperty(mergeInto, prop, Object.getOwnPropertyDescriptor(mergeFrom, prop))` would properly copy it over.

**Comment by markstos** [comment]
Thanks the report. A pull request that works with old and new Node versions would be welcome.

#314 is another Node v6 bug that we'd like to fix soon.

**Comment by thetalecrafter** [comment]
I'll prepare a pull request.
