### ISSUE TITLE
'Cannot parse config file' when using node v6 (PR welcome)

### ISSUE THREAD

**Issue by pwwolf** [lorenwest/node-config#314]
There was a [change in v8](https://github.com/v8/v8/commit/35b6ca2528173896b26217c1067efc468c9ee75d#diff-8fb2cf24b71a21c5b45a289bcb71ed2e) to add positions to error messages to the JSON parsing.

If, for example, there's a comment in the JSON file, it used to cause an error with message "Unexpected token / in JSON".  However, now the message is "Unexpected token / in JSON at position 4".

That's causing node-config to be unable to parse JSON files with comments because it no longer matches the error message correctly: https://github.com/lorenwest/node-config/blob/master/lib/config.js#L968

**Comment by markstos** [comment]
Thanks for report! It sounds like this will be easy to fix to support both the old and new error messages. A PR is welcome, or we'll get it as time permits.

**Comment by pwwolf** [comment]
Created https://github.com/lorenwest/node-config/pull/316
