### ISSUE TITLE
config filename containing substring 'development' overrides development config file

### ISSUE THREAD

**Issue by jeffswitzer** [lorenwest/node-config#317]
I have the following set:
NODE_ENV=development

I have the following config files:
default.json
development.json
production.json
local-development.json

local-development.json ends up getting used even though development.json should be the selected config file.

If I change the name from local-development.json to local-dev.json then development.json is picked correctly.

**Comment by lorenwest** [comment]
That is correct. https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order

**Comment by jeffswitzer** [comment]
Sorry I had missed that. Thanks for responding.
