### ISSUE TITLE
local.json is not documented (doc-patch welcome)

### ISSUE THREAD

**Issue by madhur** [lorenwest/node-config#325]
I faced an issue where my app is reading from `local.json` first even though `default.json` is present. I thought it would be required to have `NODE_ENV=local` to activate the local profile. But in my case it was active even though `NODE_ENV=default`.

I do not see any documentation around it.

Can you let me know why is it happening? I can give a link to sample project if required.

**Comment by markstos** [comment]
`local.json` is always processed and this is documented here: 

https://github.com/lorenwest/node-config/wiki/Configuration-Files

Is there another place where it would be helpful to document this?

**Comment by madhur** [comment]
Thanks. It would be helpful to mention in `https://github.com/lorenwest/node-config/blob/master/README.md` . It felt mysterious something like that happening.

**Comment by markstos** [comment]
Thanks. I'm Re-opening the issue because I agree that we could stand to highlight some more information directly in the README. That's the typical place that people look for key information.

**Comment by madhur** [comment]
:+1:

**Comment by cypherq** [comment]
I was checking if there is good place for this note but I can't spot any proper one. IMO it should be listed clearly here:

https://github.com/lorenwest/node-config/wiki/Configuration-Files

That `local` files are processed always & before any other.

**Comment by markstos** [comment]
@cypherq As I mentioned in my first comment on the ticket, the processing of "local" files *IS* mentioned on https://github.com/lorenwest/node-config/wiki/Configuration-Files

```
local.EXT
local-{instance}.EXT
local-{deployment}.EXT
local-{deployment}-{instance}.EXT
```

This ticket was about possibility highlighting more in the README. I see the README already has a link directly to the "Configuration Files" page.

Lacking any other proposals in the last several months, I'm closing this.
