### ISSUE TITLE
[Question] NODE_ENV conflict with express

### ISSUE THREAD

**Issue by artholl** [lorenwest/node-config#328]
Hello,
We are using express in our nodejs application and node-config.

While looking at best-practice performances for express in production, http://expressjs.com/en/advanced/best-practice-performance.html, we can see

> Things to do in your environment / setup
Here are some things you can do in your system environment to improve your app’s performance:
Set NODE_ENV to “production”

Isn't this point kind of conflicting with the use of the {deployement} value in node-config ? We have a preproduction and a production whose config differs shortly but we would like NODE_ENV to have the same value ( NODE_ENV=production ). What is the best practice in your opinion?

**Comment by lorenwest** [comment]
It's unfortunate that environment variables are global, and in that situation namespace clashes are inevitable. In most cases this similar use of NODE_ENV is a good thing, and when it's not there's a simple workaround.

Example of using `CONFIG_ENV` vs. `NODE_ENV` for configuration. Make sure this code is in the first module loaded by your app:

```
var saveEnv = process.env.NODE_ENV
process.env.NODE_ENV = process.env.CONFIG_ENV
var config = require('config')
process.env.NODE_ENV = saveEnv
```

Alternately, I wouldn't mind entertaining a pull request where node-config looked first for `NODE_CONFIG_ENV` and uses that over `NODE_ENV` if set.
