### ISSUE TITLE
"Cannot redefine property" error using util.extendDeep to extend a config

### ISSUE THREAD

**Issue by rpaterson** [lorenwest/node-config#329]
Using the `Config.util.extendDeep(...)` utility errors when you're extending using config objects and there's an override.  This issue was introduced in v1.21.0 and does not error in previous versions.

default.json:

``` json
{
    "conf": {
        "key": "value"
    },

    "overrideConf": {
        "key": "override value"
    }
}
```

Code:

``` Javascript
const CONFIG = require('config');
console.log(
    JSON.stringify(
        CONFIG.util.extendDeep(
            {},
            CONFIG.get('conf'),
            CONFIG.get('overrideConf')
        )
   )
);
```

In earlier versions that would have output `{"Key":"override value"}` but in v1.21.0 it throws an error:

```
TypeError: Cannot redefine property: key
    at Function.defineProperty (native)
    at /home/rpaterson/programming/test/node_modules/config/lib/config.js:1434:18
    at Array.forEach (native)
    at util.extendDeep (/home/rpaterson/programming/test/node_modules/config/lib/config.js:1414:9)
    at repl:1:52
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
```

**Comment by matthewadams** [comment]
I'm having the same issue.  If there is no configuration values provided by the app via configuration files or via environment variables as specified by `config/custom-environment-variables.json`, `config` processes my defaults as given to `CONFIG.util.extendDeep(...)` & `CONFIG.util.setModuleDefaults(...)` just fine.  The moment I add environment variables or configuration files that would override the module defaults, I get the same error as @rpaterson.

**Comment by matthewadams** [comment]
Looks like it was introduced in version `1.20.2` (see output below).  If I roll back my project to `config@1.20.1`, everything's jim-dandy.

```
$ for v in 1.21.0 1.20.4 1.20.3 1.20.2 1.20.1 1.20.0; do echo $v ; npm i --save config@$v ; node index.js ; done
1.21.0
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
config@1.21.0 node_modules/config
└── json5@0.4.0
/Users/matthew/temp/config/test/node_modules/config/lib/config.js:1434
          Object.defineProperty(mergeInto, prop, Object.getOwnPropertyDescriptor(Object(mergeFrom), prop));
                 ^

TypeError: Cannot redefine property: key
    at Function.defineProperty (native)
    at /Users/matthew/temp/config/test/node_modules/config/lib/config.js:1434:18
    at Array.forEach (native)
    at util.extendDeep (/Users/matthew/temp/config/test/node_modules/config/lib/config.js:1414:9)
    at Object.<anonymous> (/Users/matthew/temp/config/test/index.js:4:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
1.20.4
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
config@1.20.4 node_modules/config
└── json5@0.4.0
/Users/matthew/temp/config/test/node_modules/config/lib/config.js:1420
          Object.defineProperty(mergeInto, prop, Object.getOwnPropertyDescriptor(Object(mergeFrom), prop));
                 ^

TypeError: Cannot redefine property: key
    at Function.defineProperty (native)
    at /Users/matthew/temp/config/test/node_modules/config/lib/config.js:1420:18
    at Array.forEach (native)
    at util.extendDeep (/Users/matthew/temp/config/test/node_modules/config/lib/config.js:1400:9)
    at Object.<anonymous> (/Users/matthew/temp/config/test/index.js:4:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
1.20.3
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
config@1.20.3 node_modules/config
└── json5@0.4.0
/Users/matthew/temp/config/test/node_modules/config/lib/config.js:1422
          Object.defineProperty(mergeInto, prop, descriptor);
                 ^

TypeError: Cannot redefine property: key
    at Function.defineProperty (native)
    at /Users/matthew/temp/config/test/node_modules/config/lib/config.js:1422:18
    at Array.forEach (native)
    at util.extendDeep (/Users/matthew/temp/config/test/node_modules/config/lib/config.js:1400:9)
    at Object.<anonymous> (/Users/matthew/temp/config/test/index.js:4:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
1.20.2
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
config@1.20.2 node_modules/config
└── json5@0.4.0
/Users/matthew/temp/config/test/node_modules/config/lib/config.js:1420
        Object.defineProperty(mergeInto, prop, Object.getOwnPropertyDescriptor(Object(mergeFrom), prop));
               ^

TypeError: Cannot redefine property: key
    at Function.defineProperty (native)
    at /Users/matthew/temp/config/test/node_modules/config/lib/config.js:1420:16
    at Array.forEach (native)
    at util.extendDeep (/Users/matthew/temp/config/test/node_modules/config/lib/config.js:1400:9)
    at Object.<anonymous> (/Users/matthew/temp/config/test/index.js:4:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
1.20.1
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
config@1.20.1 node_modules/config
└── json5@0.4.0
{"key":"override value"}
1.20.0
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
config@1.20.0 node_modules/config
└── json5@0.4.0
{"key":"override value"}
matthew@newt:~/temp/config/test
$
```
Uploaded [test.zip](https://github.com/lorenwest/node-config/files/308191/test.zip) based on @rpaterson's code

**Comment by rpaterson** [comment]
Done.  Thanks!

**Comment by rpaterson** [comment]
Failing for me on Node 4.4.2, but I think it will fail the same on any reasonably recent version of Node.

**Comment by markstos** [comment]
This seems like it was likely caused by this commit:

https://github.com/lorenwest/node-config/commit/3b221d756ba198b6c74a37ae9f5556b2a72909f5

Interestingly, the author of that commit is no longer on Github. 

@rpaterson Are you interested in trying your hand a fix passes the test case you just create?

**Comment by rpaterson** [comment]
Looked at it a little... I don't think it's caused by 3b221d7.

**Comment by rpaterson** [comment]
I haven't had more time to look at it sadly.

**Comment by markstos** [comment]
The way I understand the example, you are feeding the output of a `config.get()` call to `JSON.stringify()`. What's returned by `config.get()` is an object with several methods, not just a plain data structure. This kind of complex object is not meant to be able to easily stringified, nor is that a design goal for this project.  You can confirm that the provided example works if you use this idiom to first strip off the extra methods from the data structure return before feeding it to `JSON.stringify()`:

```
const CONFIG = require('config');
console.log(
    JSON.stringify(
        CONFIG.util.extendDeep(
            {},
            JSON.parse(JSON.stringify(CONFIG.get('conf'))),
            JSON.parse(JSON.stringify(CONFIG.get('overrideConf')))
        )
   )
);
```

For a use case like this, the recommended solution is help #223 get implemented, which is about adding a method to return a plain-old-javascript-object (POJO). The result will be the same as `stringify/parse` idiom above, but will be clearer to read.

`extendDeep` is not design to recursively merge complex objects with methods attached-- that's a hard problem in JavaScript.  Making sure you are passing simple data structures to `extendDeep` is the way to go.

**Comment by markstos** [comment]
Put another way, I don't see the current behavior as a regresion, I see it as triggering an unsupported case of trying to pass complex objects to `extendDeep` when it wasn't designed for that. The object returned by `config.get()` apparently just recently got complex enough to trigger this error.

**Comment by markstos** [comment]
This also appears to be related to Issue  #338 and the follow-up PR #340

**Comment by rpaterson** [comment]
JSON.stringify() isn't my real application - I just wrote that as an example.  That said the suggested workaround of passing the results of `Config.get(...)` through `JSON.parse(JSON.stringify(...)` before calling `Config.extendDeep(...)` is probably good enough for me.  Thank you!

**Comment by rpaterson** [comment]
Actually I take it back - JSON parse/stringify isn't a valid workaround for my case, because I'm actually expecting some of the objects passed to `Config.util.extendDeep(...)` to have functions and for those to get merged the same as other properties :-(

I did find another workaround though - setting the environment variable `ALLOW_CONFIG_MUTATIONS=Y` makes the error go away.

**Comment by rpaterson** [comment]
Another workaround (even better in my case) - use `Config.util.cloneDeep(...)`:
```Javascript
const CONFIG = require('config');
console.log(
    JSON.stringify(
        CONFIG.util.extendDeep(
            {},
            CONFIG.util.cloneDeep(CONFIG.get('conf')),
            CONFIG.util.cloneDeep(CONFIG.get('overrideConf'))
        )
   )
);
```

**Comment by dcolens** [comment]
https://github.com/lorenwest/node-config/commit/db2e1357565bba3665a257e9da7187b9e668cbb9 is the root cause of this issue, reverting it, fixes the problem.

Based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__lookupGetter__, replacing `Object.getOwnPropertyDescriptor(Object(mergeFrom), prop)` by `Object.getOwnPropertyDescriptor(Object(mergeFrom), prop).get` on https://github.com/lorenwest/node-config/blob/master/lib/config.js#L1467 seems to fix it.

**Comment by kilianc** [comment]
I would love to see a fix landing soon for this, I have the same problem.

`util.extendDeep(config, otherObject)` throws this error on a boolean value.

**Comment by markstos** [comment]
I'm closing this issue because it's stale, but am not certain if it's resolved in the latest release. If it's still an issue, please comment.
