### ISSUE TITLE
Can't find files in Azure?

### ISSUE THREAD

**Issue by graham-sportsmgmt** [lorenwest/node-config#332]
I was getting this fatal error in my Azure Web Site:

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:D:\home\site\wwwroot\bin\config

When I added NODE_CONFIG_DIR and set it to D:\home\site\wwwroot\config everything works fine, so the problem is solved.

Why does config need this set in Azure in order to work?  I'm developing in Windows and deploying using git.

(btw thank you so much for this amazing module)

**Comment by markstos** [comment]
Because Azure must be setting the current working directory to something other than you expect.

The AWS Lambda service has a similar challenge.

**Comment by graham-sportsmgmt** [comment]
Thanks for letting me know.  Perhaps a quick note in the docs might save others some time?

**Comment by markstos** [comment]
We have a wiki you are welcome to improve:
https://github.com/lorenwest/node-config/wiki

On Mon, Jun 20, 2016 at 11:31 PM, Graham Hunter <notifications@github.com>
wrote:

> Thanks for letting me know. Perhaps a quick note in the docs might save
> others some time?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/lorenwest/node-config/issues/332#issuecomment-227331803>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABk5YZdA8mGtleBaIYoFOwf3yfanD0hks5qN1svgaJpZM4I5FtX>
> .
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos
