### ISSUE TITLE
read env var and parse for numeric/boolean type

### ISSUE THREAD

**Issue by jackielihf** [lorenwest/node-config#334]
Env vars is type of string. The default config vars are replaced by those vars of string type. But I want to get numeric or boolean type from "config" module.

**Comment by lorenwest** [comment]
The config module doesn't include the complexity of defining data models for configurations. In other words, it accepts whatever data type you give it, without converting to a known data type.

If you configure a value as a string, it will be a string. Anything configured by environment variable or application parameter will be a string. If you need it to be something else, you'll have to convert it after issuing the config.get().
