### ISSUE TITLE
config.getAll() or similar

### ISSUE THREAD

**Issue by joh-klein** [lorenwest/node-config#339]
I know there is `config.util.getConfigSources())` but is there a way to only get an output that shows the merged config? Including env and argv substitutions?

**Comment by lorenwest** [comment]
Not sure what you're asking for here. The final merged config *is* the final merged config, and console.log() is a great way to get an output of that.

**Comment by markstos** [comment]
Closing as a dupe of #223.

In that issue, you'll find more discussion and description of what we are looking for in a PR that we would accept.
