### ISSUE TITLE
[request for wiki clarification/suggestion] External config mgmt tools with node-config

### ISSUE THREAD

**Issue by lsb** [lorenwest/node-config#341]
I was reading https://github.com/lorenwest/node-config/wiki/External-Configuration-Management-Tools and it is brief and I was hoping to ask a question about it. I was wondering about "deployment-specific override files"; how reasonable is it to use node-config and do something like symlink /etc/{appname}/config.json to config/local.json to allow the config mgmt app to avoid writing into the app's local directory?

I'd be happy to add this to that wiki page if you think it's a valuable suggestion.

**Comment by lorenwest** [comment]
I'd like to understand this use case a bit more. Is your config. management app not able to write into the app dir, or would you just prefer it didn't? If you're going to link config/local.json, doesn't that require the config mgmt app to write that link?

**Comment by lsb** [comment]
The soft link might get checked into version control (like `config/local.json` is a file with a mode of 120000 and contents of `/etc/app/config.json`), and then /etc/app/config.json gets laid down (potentially by a Docker file mount or something). Is that the way you'd do it? Or do you recommend ensuring all configuration stays within the app's directory, like the node modules are self-contained in the app's directory?

**Comment by markstos** [comment]
@lsb Your solution sounds like it would work: to check a symlink into source control that gets resolved different depending on the environment.

It sounds though like your configuration is not centralized: That different config files exist in `/etc/app/config.json` in a number of environments.

`node-config` recommends the opposite approach: Putting all your configuration in one place-- the `./config` directory, where it is easily understood and managed. Environment variables are used to express which configuration to load in a different context.

If you have *dynamic* configuration, such as dynamic host names or dynamic database names, `node-config` is not usually used for that. However, there are docs on the wiki about using `config/customer-environment-variables.json` to map dynamic values stored in environment variables into config values. 

Or in summary: the approach you described is possible, but not recommended.  I started my career using the approach you describe, where the development configuration was stored only in development and the production configuration was stored only in production. 

Besides the problems I had keeping multiple configurations in sync in multiple locations, I had a real problem the day I accidentally deleted the production configuration and there was no version of in source control!  That only had to happen once to make me a convert of a centralized, source-controlled configuration pattern.

The one class of items I *do* keep  in environment variables is sensitive items like encryption keys and passwords. That allows only the subset of developers with access to the production systems to be able to access customer data, for example.
