### ISSUE TITLE
Question: How does config.util.getEnv differ from process.env?

### ISSUE THREAD

**Issue by sandinmyjoints** [lorenwest/node-config#342]
When will the values returned by these differ, if ever?

**Comment by lorenwest** [comment]
`config.util.getEnv()` is a function that returns the value of one of a list of known config environment variables. It always returns a value, even if it is the default. `process.env` isn't a function at all. It's an object containing a mapping of shell environment variables set when the process began.

There are many ways to set, default, and override the environment variables that node-config uses. `config.util.getEnv()` always returns the value of that variable used by node-config.

**Comment by sandinmyjoints** [comment]
OK, thanks for the clarification.
