### ISSUE TITLE
config.get('item.y') has extra properties on it

### ISSUE THREAD

**Issue by Icehunter** [lorenwest/node-config#344]
I've usually used the following to get my configs:

```javascript
const config = require(`./config/${process.env.NODE_ENV || 'local'}/config.json`);
```

There would of course be extra folders/etc/etc.

I've recently started using your module and it's great! The only issue I've stumbled across is the compatibility between this and Hoek/Bell from Hapijs.

Hoek does a clone using getOwnPropertyNames like so:
https://github.com/hapijs/hoek/blob/master/lib/index.js#L67

Which is called from here in Bell:
https://github.com/hapijs/bell/blob/master/lib/index.js#L82

Now if I console.log both a pure JS config and config.X or config.get('X'); and check if they are === it always comes back as "true".

If I console.log config.X or config.get('X'); it will only show the object I want to see.

If I console.log config itself I get not only my configuration items and settings but the config exports/properties as well.

So my questions are:

1) Should the config JS object be flattened to the root of the config library?
2) Can something be done to ensure interoperability with Hoek/Bell?
3) Is there anything I'm missing in this issue request that would help further?

Thanks!

**Comment by lorenwest** [comment]
1) no
2) yes, if someone wants to issue a pull request that doesn't break backwards compatibility
3) probably

**Comment by markstos** [comment]
The config object is supposed to have extra properties on it. If you want to get a "plain object" version, see #223. As noted there, a pull request is welcome.
