### ISSUE TITLE
Support HOCON for configuration. (PR welcome)

### ISSUE THREAD

**Issue by 20zinnm** [lorenwest/node-config#348]
It's be awesome if we could use HOCON for our configuration files.

Thanks!

**Comment by lorenwest** [comment]
Anyone interested in adding this support has a good pattern to use for testing and lazy loading.

**Comment by markstos** [comment]
[HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md) sounds similiar to [JSON5](https://www.npmjs.com/package/json5) which we already support.

**Comment by 20zinnm** [comment]
HOCON is actually extremely dynamic, more than JSON5. It shifts the burden from the person to the machine; granted, that makes it more complex to parse. I do know libraries and such exist, like https://github.com/typesafehub/config <https://github.com/typesafehub/config>, but I’m not aware of a native JavaScript implementation. It’s a JSON superset so it can’t be too hard.

**Comment by iMoses** [comment]
This is can be solved by addressing #181

**Comment by markstos** [comment]
Closing this in favor of #181.
