### ISSUE TITLE
Bug: Config is being used from other directories!

### ISSUE THREAD

**Issue by JemiloII** [lorenwest/node-config#349]
So this is more of an annoyance than anything, as what happens is not intended or assumed behavior. Having multiple projects with node-config on the same machine, node-config will default to the first run config.

Example
`/home/user1/project1/config`
`/home/user2/project2/config`

project1 is run first, then when project2 is run, it is bound to using project1's config. Since this is 2 different users, we could just set the `NODE_CONFIG_DIR` environment variable. Something we shouldn't have to do, but alas it is a solution.

But what happens if it is the same user?

Example
`/home/user1/project1/config`
`/home/user1/project2/config`

Well now it gets messy we have to add the environment variable while running our application.

`NODE_CONFIG_DIR=/home/user1/project1/config node /home/user1/project1/app.js`
`NODE_CONFIG_DIR=/home/user1/project2/config node /home/user1/project2/app.js`

This is really non ideal and then forces users to include extra files, code, or modules to tackle this issue.

It would be nice, if after checking the environment variable, for config to just default to it usual location rather than looking up a location in cache.

**Comment by markstos** [comment]
I'm confused. The title says "Bug", but it's not clear from the description where `node-config` is working differently than it's documented. Then the closing statement is "it would be nice", which sounds like more a feature request.
 
 * node config returns a singleton. As is usually with the case when you `require()` a module, the result is cached. So the second time you `require()` the `config` module you are going to get the original config in the same process. 

Did you search for other related bug reports. Starting with #225, there are several other bug reports it links to which seem related. 

Re-open this issue if there's a clear bug or feature request that's distinct from the ones already filed.

**Comment by JemiloII** [comment]
This is a bug, the other issue you linked is for sub modules. This is not for sub modules. There are two separate  projects in different locations. None of which are parents of the other. If you start one project's application, you're forever bound to it's config, even when shutting it down. If it was a submodule, it would make sense, however, since these are not submodules and live in completely different directories, this is a massive bug.

**Comment by markstos** [comment]
I can't see how the config could be shared into different process. Please add a test to the test suite which demonstrates it, or other sample code or exact reproduction steps, using simple "hello world" apps.
