### ISSUE TITLE
hostname.json is not getting loaded

### ISSUE THREAD

**Issue by malhotraa** [lorenwest/node-config#353]
Since October 21st, my hostname.json is not getting picked up by node-config. I tried printing out the hostname:

`console.log('HOSTNAME: ' + config.util.getEnv('HOSTNAME'));`

Output:

_HOSTNAME: undefined_

Not sure why HOSTNAME is undefined as the $HOSTNAME env var is clearly defined when I type echo $HOSTNAME in my command line.

I am using node-config v1.21.0 with node v6.5.0.

**Comment by markstos** [comment]
Did you upgrade `node-config` on October 21st? If not, this could not be a node-config bug. It must be environmental. 

Reading the source of node config, https://github.com/lorenwest/node-config/blob/9c9aeeeac416e392012c6c25080500893f8afdcf/lib/config.js for mentions of hostname,

it appears to confirm that if hostname is unset when you call `getEnv()`, it must be unset in your environment. 

Closing as not-our-bug. If you can contribute a test to the test suite which illustrates there's a bug in node-config regarding this, please re-open.
