### ISSUE TITLE
Missing Published version 1.22.0 in npm registry

### ISSUE THREAD

**Issue by mlasak** [lorenwest/node-config#354]
Newest version available via the npm registry is 1.21.0 currently. Would be nice if the current 1.22.0 could land. Thanks.

**Comment by lorenwest** [comment]
This is the strangest thing. I published 1.22 on 10/25. I tried re-publishing it just now, and it says it's already published. Logging into npmjs shows 1.21 as the latest version. What gives?

I'll artificially bump it to 1.23, publish that, and we'll see what happens.

**Comment by lorenwest** [comment]
Ok - just published 1.23 on 11/2. Let's see if the reviewers approve this version :)

**Comment by lorenwest** [comment]
`npm info config` shows the latest version at 1.23, but npmjs.com still has it at 1.21. I probably should have checked `npm info` before publishing another version. 

@mlasak how did you determine that 1.22 hadn't been published?

**Comment by markstos** [comment]
I checked the version a couple of other ways, and they both see 1.21 as the latest version as well. You can specify trying to install an invalid version, and `npm` or `yarn` will give you a list of valid versions in the repo:

    npm install config@boom -- reports 1.21 as latest versions
    yarn add config@boom -- reports 1.21 as the latest version. (Uses npmjs.com via proxy, so same result was expected)

The `version` in package.json is definitely updated. I'm not sure what could have gone wrong.

**Comment by lorenwest** [comment]
Apparently I can no longer be relied upon to remember to point my ~/.npmrc from a private registry to the public registry before publishing node-config.

Lucky for me, [there's a fix for that](https://github.com/lorenwest/node-config/blob/master/.npmrc). If only the fix for remembering things were as simple...

**Comment by mlasak** [comment]
Thanks a lot, the registry seems to have the newest version now, although npmjs.com is still behind (cache?). On a fresh system ```npm install config``` will fetch the 1.24.0 now, which is good. Thanks for your work!
