### ISSUE TITLE
custom filenames possible?

### ISSUE THREAD

**Issue by bonesoul** [lorenwest/node-config#359]
i'd like to load my configs from;

db.default.toml
db.development.toml
db.production.toml
webserver.default.toml
webserver.development.toml
webserver.production.toml

**Comment by markstos** [comment]
Use a build tool like Grunt or Gulp to rewrite your file names into the format `node-config` expects. There is already significant flexibility and complexity in the file load system. Supporting all the variations of file naming schemes that people might not use is not practical.

You might also use symlinks to make permanent relationships between your names and the node-config names. Or you could consider adopting the naming scheme that node-config expects.

**Comment by lorenwest** [comment]
To add to @markstos comment, the value of establishing a standard for config file locations can't be understated. As more companies move to nodejs, it makes sense to have these standards to lower training costs and reduce risk. When things go wrong in live systems, configurations are often the first place to check, and having consistency can reduce confusion and save time.

In some cases, snowflakes are a thing of beauty. Not in config file location.
