### ISSUE TITLE
How to work with other lib to handle json

### ISSUE THREAD

**Issue by Hidfeel** [lorenwest/node-config#360]
I try to find some way to make `config` work with [`shortstop`](https://github.com/krakenjs/shortstop) in order to add some special handle for json , before `Config.get()` it.
But I don`t find where to start, anything to add a hook or prehandle  after json file loaded.

**Comment by markstos** [comment]
We support JavaScript as a file type. In a JavaScript file, load the JSON files you want, process them with shortstop and return the final config structure you want with `module.exports`.
