### ISSUE TITLE
Multiple configurations for testing

### ISSUE THREAD

**Issue by manojlds** [lorenwest/node-config#362]
Is there anyway I can override the config use by the system under test for different test cases?

**Comment by manojlds** [comment]
Perusing the code, I saw that there is `ALLOW_CONFIG_MUTATIONS`. But setting this also doesn't allow me to change config per test.

Something like `config.property1 = { key: "value" };` doesn't seem to have an effect.

Any pointers?

**Comment by lorenwest** [comment]
Upon reviewing the code that uses `ALLOW_CONFIG_MUTATIONS` it seems like it does the intended job of allowing mutations.

If you feel you've found a bug, please submit a pull request including a new test that fails. This will give someone (yourself maybe?) an opportunity to understand the failure condition and resolve the issue.

**Comment by markstos** [comment]
Use the `config-uncached` add-on for switching configurations during testing.

https://github.com/MrBoolean/node-config-uncached
