### ISSUE TITLE
Environment not working as expected?

### ISSUE THREAD

**Issue by aserrano1971** [lorenwest/node-config#364]
Hi:

I've noticed that if variable doesn't exist in production config the library override it with development one.

This is the sample I've done to test it.
In the first sample the PORT is defined in production.json and It's displaying well but in the second case I've renamed it to PORTs to catch the system one in a production server.

The idea is to define PORT as unix environment variable in a production server because I don't have access to this server and the sysadmin must change it.

Instead of that the library is overriding it with the development one.

Really I don't know if this is correct or not.

*****
Console display:
PORT: 8080
PORT ENV: undefined
NODE_ENV: production
SERVERCONFIG IS: { PORT: 9000 }
THE PORT IS: 9000

here the production.json is changed to PORTs
  aserrano$ node server.js 
PORT: 8080
PORT ENV: undefined
NODE_ENV: production
SERVERCONFIG IS: { PORT: 7000, PORTs: 9000 }
THE PORT IS: 7000
*****
Source Code

var express = require('express');
var config = require('config');

const util = require('util');

//PUERTO A USAR...USAMOS VARIABLES DE ENTORNO EN PRODUCCIÓN....O NO....PERO ASÍ
//DEBE DE FUNCIONAR EN HEROKUAPP
var port = process.env.PORT || 8080;

console.log("PORT: " + port);
console.log("PORT ENV: " + process.env.PORT);
console.log("NODE_ENV: " + process.env.NODE_ENV);
console.log("SERVERCONFIG IS: " + util.inspect(config.get('serverConfig'), {showHidden: false, depth: null}));

if(config.has('serverConfig.PORT')) {
    port = config.get('serverConfig.PORT');
}

console.log("THE PORT IS: " + port);

***
default json
{
  // DEVELOPMENT CONFIG
  "serverConfig": {
    "PORT": 7000
  }

}
***
production json...the first one
{
  // PRODUCTION CONFIG
  "serverConfig": {
    "PORT": 9000
  }

}
***
production json...the second one
{
  // PRODUCTION CONFIG
  "serverConfig": {
    "PORTs": 9000
  }

}

**Comment by markstos** [comment]
The behavior is correct because according to your own example you put "// DEVELOPMENT CONFIG" in "default json". 

The purpose of a "default" configuration file is to provide defaults. If you didn't want that behavior, you should have put your development configuration in a "development.json" file and only put things in default.json that you wanted as defaults in all environments.
