### ISSUE TITLE
Add support for TypeScript in config files

### ISSUE THREAD

**Issue by cypherq** [lorenwest/node-config#366]
Will you consider simple path for TypeScript support in config files? I have TS in project and `node-config` is expecting `*.js` files. I went into source and found that it can also accept ie. `*.coffe` files so I thought it won't be too much away from your  internal project agreements.

I've changed only two lines.

  - Simply require `*.ts` file if extension matches (if project is configured to use Ts it will be parsed anyway by TS compiler): 

    https://github.com/lorenwest/node-config/blob/master/lib/config.js#L855
    `if (extension === 'js' || extension === 'ts') {`

  - Allow `*.ts` extension:

    https://github.com/lorenwest/node-config/blob/master/lib/config.js#L688
    `var extNames = ['js', 'ts', 'json', 'json5', 'hjson', 'toml', 'coffee', 'iced', 'yaml', 'yml', 'cson', 'properties', 'xml'];`

If you're happy with such solution I can easily prepare PR.

**Comment by lorenwest** [comment]
Hi @cypherq,

I'd be happy to merge an enhancement that brings in typescript. If you do this, make sure to follow the lead from other extensions - lazy loading, wiki page entry, and associated tests.

Isn't typescript transpiled? Wouldn't a default.ts get transpiled into default.js that `node-config` can use? My thoughts are the .ts to .js conversion are done at build time vs. at runtime. Is it common to have a typescript transpiler/interpreter a part of the runtime application?

Thanks,
-Loren

**Comment by cypherq** [comment]
During development I'm using `nodemon` with `ts-node`, something like this:

```
NODE_ENV=development nodemon --exec ./node_modules/.bin/ts-node -- ./index.ts
```

So `node-config` can't see *.ts files - if I'll left it as *.js I can't run it with TypeScript environment. I'll prepare branch this week, following all case you mentioned.

**Comment by monkpit** [comment]
@cypherq any update on this?

**Comment by wendellm** [comment]
Also when using webpack its customary that the ts file does not get transpiled

**Comment by cypherq** [comment]
**Related PR:**
https://github.com/lorenwest/node-config/pull/399
