### ISSUE TITLE
Wish: support Electron environment

### ISSUE THREAD

**Issue by dw1284** [lorenwest/node-config#368]
This issue seems to be related to the fact that **process.cwd()** doesn't return what you think it does when running via Electron. Replacing **process.cwd()** with **require('Electron').app.getAppPath()** fixes the issue, but that only works if you have Electron included as a dependency. Maybe add an if check to determine if Electron is present, and if so, use the getAppPath() function, otherwise use the regular process.cwd() function.

**Comment by markstos** [comment]
We would be open to running in the Electron environment. First, we need a way to explicitly detect that we are in the electron environment. How does one detect they are running in the electron environment? Can you provide examples of modules that handle this case in both regular Node.js and the Electron environment?

This enhancement request is very closely related to #367.  The same approach should be used in both cases. 

The `node-config` maintainers are using `node-config` inside Electron but we consider reviewing a PR if someone gets this working.

**Comment by dw1284** [comment]
**Update:** Loren indicated, in this thread https://github.com/lorenwest/node-config/pull/369, that this fix isn't going to be implemented.

Loren did supply a legit work-around. You can find it in https://github.com/lorenwest/node-config/pull/369, however, I threw together a new module which wraps node-config and implements the work-around for you. This new module supports electron out of the box:

https://www.npmjs.com/package/electron-node-config

You can use the new module, or implement Loren's work-around yourself. Your choice.

I'm closing this since we now have multiple ways to deal with the issue, and there are no plans to change node-config as far as I can tell.

Thanks everybody.
