### ISSUE TITLE
Unable to load configuration file in docker environment

### ISSUE THREAD

**Issue by 2007ay** [lorenwest/node-config#370]
Hi Guys,
I am using config node module to load my node environment variable based on the NODE_ENV value like development or production, In my local  every thing is working , but the issue occurs when I try  to run the already build docker image , Its throwing below error.

SGLT83:storyvew-node ashish$ docker run -it -p 10020:10020 sv-node-dev
WARNING: No configurations found in configuration directory:/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/src/node_modules/config/lib/config.js:180
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "ElasticSearch" is not defined
    at Config.get (/src/node_modules/config/lib/config.js:180:11)
    at Object.<anonymous> (/src/config/environment/index.js:14:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /src/global_objects.js:1

//path : apps/config/development.json

My development.json is looks like
{
    "ElasticSearch": {
        "hosts": ["xxxx"],
        "log_level": "info",
        "requestTimeout": 60000
    },
    "EXPRESSJS": {
        "HTTPHEADER_SIZE": "50mb"
    }
}

and  apps/config/environment/index.js is

/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4, maxerr: 50 */
/*global require, module, process*/

var config = require('config');

module.exports = {
    NODE_ENV: process.env.NODE_ENV,
    ElasticSearch: config.get('ElasticSearch'),
    headerSize: config.get("EXPRESSJS.HTTPHEADER_SIZE")
};

Thanks in advance

**Comment by lorenwest** [comment]
Hi @2007ay ,

This error happens because your working directory isn't the directory that the package.json lives in at the top of your application. The working directory must be the one that contains the /config directory.

Try using the `WORKDIR` command in your dockerfile to specify the working directory of your application.

Let me know if that works for you.

**Comment by 2007ay** [comment]
@lorenwest  Awesome !.. thanks a lot its working . One more question how to set NODE_ENV variable in docker do you have any idea.

**Comment by lorenwest** [comment]
https://docs.docker.com/engine/reference/builder/#env
