### ISSUE TITLE
issue with webpack

### ISSUE THREAD

**Issue by srt0422** [lorenwest/node-config#374]
Including this package breaks my webpack build.  I haven't been able to get it working so I switched to a different library.

**Comment by lorenwest** [comment]
Closing - not a sincere attempt at opening an issue for improvement. 

If you need to rant, take it to twitter.

**Comment by srt0422** [comment]
@lorenwest Sorry, not trying to rant.  The intent of my post was to find out if there's a work around for webpack.

**Comment by lorenwest** [comment]
There's plenty of information about webpack in this repository. Discussions, resolutions, people with success stories, NPM package additions, etc. You could start here: https://github.com/lorenwest/node-config/issues/345

**Comment by srt0422** [comment]
Thanks.  I did make an effort to find an existing solution before posting, but after several hours on google I posted thinking there wasn't anything else on this, since I can usually find things through google.  I would've thought google would find anything on github related to my search, but I must not have been using the right search terms.

**Comment by srt0422** [comment]
By the way, I'm just new to webpack, node, and basically everything to do with it.  I posted under the false impression, that there was no webpack compatibility, and I thought the authors might want to know that there's a need there.  Wasn't ranting.  Thanks again for the help.
