### ISSUE TITLE
regression in unit tests with v1.25.0

### ISSUE THREAD

**Issue by seanpk** [lorenwest/node-config#378]
This morning we started seeing this error in my mocha tests:
```
Error: global leak detected: CONFIG_SKIP_GITCRYPT
```

(mocha is run with the `--check-leaks` flag)

with v1.24.0 all is well

Is that new global intended?

**Comment by lorenwest** [comment]
Good catch - thanks for reporting. We'll get a patch out soon.

**Comment by seanpk** [comment]
@lorenwest - thanks!

**Comment by markstos** [comment]
The's already a PR and discussion in progress in #377.

**Comment by markstos** [comment]
@seanpk Actually, yes, a new variable called CONFIG_SKIP_GITCRYPT which is handled consistently with how other similar node-config variables are handled. So it's not clear that it's a "leak".   The work in #377 is not about a global variable leak, but  there are failures when CONFIG_SKIP_GITCRYPT is *not* set, which was not the intent.

@lorenwest Perhaps we should rollback the 1.25 git-crypt support while these issues are worked out? 

CC: @cunneen

**Comment by lorenwest** [comment]
I tried unpublish, but npm won't let me unpublish config@1.25.0 (maybe because it's the latest version?). Working on getting a 1.26 out, but would prefer if it fixed 1.25 vs. just rolling it back.

**Comment by lorenwest** [comment]
This really was a leak. The variable wasn't defined at the top of the file like others following that pattern. Fixing in 1.26, and will get it out shortly.

**Comment by lorenwest** [comment]
Just pushed 1.25.1 to patch this issue. @seanpk - Would you mind re-running the test using 1.25.1 in your test harness to validate the fix?

**Comment by seanpk** [comment]
@lorenwest - everything is good with 1.25.1 👍 
Thanks for getting this resolved so quickly!
