### ISSUE TITLE
Wish : Make documentation on external sources configuration

### ISSUE THREAD

**Issue by Elpayet** [lorenwest/node-config#382]
Hi, 

Playing around with docker and cloud VMs is great but we are struggling to deploy our config files from a single secured place, like a database for instance. The documentation I found in the wiki is very limited and unclear. Could you please explain in the wiki how to achieve distant config retrieval with config ? at least an example would be a major improvement.

Regards,

**Comment by markstos** [comment]
This is not a topic that comes up all that frequently. The pattern I would chose for myself is to have a tool that writes out JSON files in the project `./config` directory, and have `node-config` read those in when the app starts. 

`node-config` is designed around immutable data structures and is *not* intended for values that may change while the app is running, such as values that are looked up on a database on demand. 

If your app is is a web-app, ever time the web server is started, you could have it re-generate the config files just before the app starts up.

**Comment by Elpayet** [comment]
Hello,

Thank you for your reply. I get the point on the immutable character of config. I didn't realized it worked that way. I will push the config files at every deployment with another method.

Regards,
