### ISSUE TITLE
how can i suppress "NODE_ENV value of 'test' did not match any deployment config file names." warnings?

### ISSUE THREAD

**Issue by nrser** [lorenwest/node-config#386]
i have mocha tests being run in a spawned process with `NODE_ENV=test` and i'm getting these warnings in the output:

```
WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
```

i checked out #309 and read the source... it doesn't seem like there is any way turn them off?

**Comment by markstos** [comment]
The answer is on the linked web page, under the section about the specific warning you got.

**Comment by nrser** [comment]
you mean creating a file for it to find? i understand that would stop the warning. i wanted to know if there was a way to simply suppress it's display without changing the configuration.

**Comment by markstos** [comment]
No, there's not a second method. Just create the file.

**Comment by morphatic** [comment]
I found another workaround. In my `package.json` file where I set up my test script, I changed it to the following:

```javascript
{
  ...
  "scripts": {
    "test": "NODE_ENV= jest",
    ...
  },
  ...
}
```

This prevents `jest` (or `mocha` in your case) from setting the `NODE_ENV` variable to "test" which in turn means that the `config` package won't look for the `config/test.json` file. Take special note that **there is a space between `NODE_ENV=` and `jest` in that script**. Alternatively you could set `NODE_ENV` to something else, but the `config` package would look for a JSON file with that name in the `config/` directory and you'd be back to the place you started.

**Comment by capan** [comment]
I know this is not the best practice but I've wrapped the warning logs in **config.js** with an if to get rid of the warning messages;

```
 if (prefix !== 'WARNING: ') {
      console.error(prefix + msg);
      console.error(prefix + seeURL);
    }
```
