### ISSUE TITLE
Can't find a way to change the default json configuration file path

### ISSUE THREAD

**Issue by joeyzhao0113** [lorenwest/node-config#388]
Is there a way to define configuration json files from directory other than `config`? I did't find a way to configure the parameter for below function:

```
util.loadFileConfigs = function(configDir){
...
```

**Comment by markstos** [comment]
Besides NODE_CONFIG_DIR? https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir

Closing this, since it's not a bug report or feature request.
