### ISSUE TITLE
Override/Remove Config

### ISSUE THREAD

**Issue by felixheck** [lorenwest/node-config#390]
Hi there!

Is there a way to override some value or rather remove them?
For example:

``` js
// default.js

module.exports = {
    foo: {
        bar: 42
    }
}
``` 

And I don't wanna have `foo.bar` in e.g. the `development` environment.
The following is (of course) not working:

``` js
// development.js

module.exports = {
    foo: {}
}
``` 

Have I to delete the nested key/property manually with `lodash` or something like that?
Or is there a smarter solution?

Thanks.

**Comment by markstos** [comment]
Your attempted syntax doesn't work because `node-config` does deep merging of configs.  Try either:

     foo : undefined

Or 

    foo :  { bar : undefined }

Or you could use the [defer](https://github.com/lorenwest/node-config/wiki/Configuration-Files#javascript-module---js) syntax:

    foo: defer( () => undefined )
