### ISSUE TITLE
Get variable for ENV

### ISSUE THREAD

**Issue by orgertot** [lorenwest/node-config#391]
Hey,
So is there the possibility to get a variable for a specific Environment without setting it in the node process?

like config.get("dbHost","test") or something like that?

Thanks

**Comment by markstos** [comment]
Unless you looking for the [custom environment variable](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables) support, it sounds you are asking if you can read an environment variable that hasn't been set, which doesn't make sense.

**Comment by lorenwest** [comment]
You asked if you can get a variable not set in the node process, which was pointed out makes no sense.

If instead you meant to ask if we could expose environment variables via `config.get()`, the answer would be no. Configurations and environments are different things, and they should be kept separate.
