### ISSUE TITLE
Possibility to specify an interceptor or a proxy for each property invoked

### ISSUE THREAD

**Issue by ribeaud** [lorenwest/node-config#400]
I am currently facing following situation: I have some encrypted passwords in my configuration file. These passwords are spotted following a pattern like for instance `ENC(<config-value>)`.

I would like to be able to specify a **proxy** (or an **interceptor**) which would then handle such cases. In my previous example, the proxy would just spot such pieces and do the right conversion.

In **Java** world, there is this neat library named [Jasypt](http://www.jasypt.org/encrypting-configuration.html) which does such a thing.

Just let me know what do you think. Maybe, there is an obvious way I am not aware of to do so without to have to implement such a feature...

Wish you a wonderful day. Kind regards,

christian

**Comment by markstos** [comment]
@ribeaud what about making a sub-class or wrapper-class for node-config that does the decryption for you?

With your idea of a `proxy` or `interceptor`, what do you think the syntax for using `node-config` with it would look like?

**Comment by ribeaud** [comment]
Hi Mark. I do not want to subclass the config or to use a wrapper. I should just be able to specify a _method_ (the `proxy` or `interceptor`) which then will be invoked for each config value. This would be my very _generic_ idea.

Or we could do it more specifically: we define a pattern, for instance `ENC(<config-value>)`. This pattern identifies pieces which should be decrypted on-the-fly by `node-config`. Users set some `crypto` parameters as `node-config` options which will be used for the decryption of such config values.

Saying that, I am realizing that this is maybe no longer the job of a simple configuration library like `node-config`, rather the job of a new library combining somehow `node-config` and `crypto`.

I read the doc on [Securing Production Config Files](https://github.com/lorenwest/node-config/wiki/Securing-Production-Config-Files) but I found it too complicate. I want to commit my passwords, **but** encrypted. I do not want to go over some setup steps (and I do not want my users to do so neither).

What do you think? You have much more **JS** experience than me, and a better command of
`node-config`. Thanks in advance for any feedback and your time. Cheers and have a nice week-end.

Cheers,

christian

**Comment by markstos** [comment]
@ribeaud I think there are multiple good options to secure configuration. `git-crypt` is one option. Another is to *not* commit the most sensitive keys, and instead only make them available in the production environment by environment variables.   Committing pre-encrypted into git is another option which seems viable, but I have not dug into that option.  What comes to mind is a solution that looks like this untested pseudo-code

```javascript
// In new module for node-decryption
var config = require('config');
var decrypt = require('some-decryption-module');

var wrapper = config;
wrapper.get = function (val) {
          // Some logic to check if the value is encrypted
          if (decrypt.isEncrypted(val)) {
               return decrypt.decrypt(val)
         }
         else {
              return config.get(val);
        }
}

module.exports = wrapper;
```

Then, your application would load this class where it currently loads `node-config`. 

A cleaner design might use the newer syntax for  classes, sub-classes and `super`:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super
 
A proxy/intercepter pattern might also be viable. `node-config` could offer an empty "hook point" for filtering content after files are read and before it's processed.  Modules could then register functions to run at this "hook point". `node-config` would check if any callbacks were registered at this hook point and if found, run them in modern. 

This is how some plugin systems are implemented and is a bit like the Express middleware design.

`node-config` would like to support multiple encyption options but not be tied to a particular pattern, so solutions that are re-usable across different patterns are off particular interest. Solutions that exist outside the `node-config` core are also of particular interest.

**Comment by ribeaud** [comment]
@markstos for the time being, I followed your suggestion and created a new package [crypto-config](https://github.com/ribeaud/node-crypto-config).

Actually, we do not even have to agree on a function name: **any** function doing some transformation could be used as _hook point_. This _hook point_ could be used for encryption or for something else (we are then back to my first general idea).

Things which should be further considered:
- In  [crypto-config](https://github.com/ribeaud/node-crypto-config), I am only considering **string** values. Property values could be **string** or **integer**. Objects or array will be recursively introspected.
- Advantages/disadvantages of lazy resolution of the properties. In your _pseudo-code_, you are lazily resolving the property values. I preferred to do it eagerly. No real reason here, I was just faster do it like this.

If you guys decide to implement this _hook point_, then kindly let me know. My package will become then obsolete... :grimacing:

Cheers and have a nice day,

christian

**Comment by alexindigo** [comment]
@ribeaud Maybe this module could be of help, it has hooks support – https://github.com/alexindigo/configly#custom-hooks – let me know if it would work for you.

**Comment by markstos** [comment]
Closing, since crypto-config seems like a good-enough resolution here.
