### ISSUE TITLE
Feature Query: Set new config in memory

### ISSUE THREAD

**Issue by zusamann** [lorenwest/node-config#406]
This is a very useful and easy to use library for loading configuration files. But my query is, is it possible to set new configuration while the app is running.

In many cases like authentication over an external service, you get some token back, which you then need to store in memory and use it later on.

Will it be possible to have something like this? `config.set('key', 'value')`
It could increase the utility of the package and also make it less confusing to develop apps without having to use both a `config` and a `registry` of some sort to store temporary in memory config.

**Comment by markstos** [comment]
We will not not support mutable configurations.  There are a couple of patterns you can use with node-config:

  1. Do what you need to do and write it to a config file before node-config loads it.
  2. Modify a value by directly accessing the `config` object before the first call to `config.get()`, when the structure becomes immutable. This feature is intentionally present to allow you to do things like change different config values on the fly for testing. 

Related tickets: #186  #347 #382

**Comment by zusamann** [comment]
ok thank you for the quick response
