### ISSUE TITLE
Chain inheritance

### ISSUE THREAD

**Issue by krutijan1** [lorenwest/node-config#407]
Hi, is there possibility to declaratively reference config file from which to inherit from ? If I understand it right, right now all config files can override default.json configuration. The case is following. Lets say user has production.json and development.json files, each is overriding default.json file, and lets say, now user wants to reuse environment based configuration in another file called scheduler.json. Scheduler.json should inherit development.json when NODE_ENV=development, and production.json when NODE_ENV=production. Current solution is to provide scheduler-dev.json and scheduler-prod.json which contains duplicate configuration, or am I overlooking something ?

Thanks

**Comment by lorenwest** [comment]
Node config doesn't support declarative inheritance chains, but if you're concerned about duplicating configurations across common environments, you can use .js format and load common configurations directly:
```
  scheduler: require('./scheduler.js'),
```
