### ISSUE TITLE
Bug: Overriding one Regex with another fails

### ISSUE THREAD

**Issue by XadillaX** [lorenwest/node-config#410]
default:

```javascript
{
    foo: /foo/;
}
```

local:

```javascript
{
    foo: /bar/;
}
```

the `foo` won't be overwritten by local.

it ran into https://github.com/lorenwest/node-config/blob/4e1db3afb174878cf5920a38107a6f5e86b745b5/lib/config.js#L1469.

**Comment by markstos** [comment]
Thanks for the report. It would also be helpful to have a failing test contributed to the test suite as well as a patch.

You could be the next one to have your photo added to the Contributors section: https://github.com/lorenwest/node-config/blob/master/README.md#contributors

**Comment by XadillaX** [comment]
PR committed.

**Comment by XadillaX** [comment]
I think this issue could be closed now.
