### ISSUE TITLE
Docker Secrets

### ISSUE THREAD

**Issue by lee5i3** [lorenwest/node-config#414]
Any possibility to support docker secrets?

It is really just reading the setting from a file in /run/secrets

Example:
/run/secrets/port (contains 8080)
/run/secrets/mongo_url (contains my mongo connection string)

**Comment by markstos** [comment]
As a special case, Docker secrets are unlikely to be supported in the node-config core. You can use a JavaScript config file type and just read these files to load them into your configuration.

If you like your solution, you can publish it as an NPM module that people can use as a companion to node-config. It could then be documented on the wiki: https://github.com/lorenwest/node-config/wiki/Plugins

**Comment by lee5i3** [comment]
https://github.com/lee5i3/config-secrets

It isn't the best implementation, but it'll work

**Comment by markstos** [comment]
Thanks for the contribution.
