### ISSUE TITLE
Wish: Programmatically specify the configuration directory

### ISSUE THREAD

**Issue by aymericbeaumet** [lorenwest/node-config#415]
I would like to programmatically specify the directory from which to fetch the configuration, to do so I now leverage the [config.util.loadFileConfigs](https://github.com/lorenwest/node-config/blob/ed1e0605daec45c195a4ed39da15d9033d64a387/lib/config.js#L636) helper:

```javascript
import config from 'config';

const loaded = config.util.loadFileConfigs('/tmp/config');

export default {
  get: config.constructor.prototype.get.bind(loaded),
  has: config.constructor.prototype.has.bind(loaded),
};
```

This seems like a tricky way to do it for two reasons:
- I have to require the `config` package, which tries to find the configuration in the `process.cwd()` directory
- I have to manually bind the `get` and `has` methods so as to emulate the node-config behaviour

I suggest to move the Config class into a separate file, and make it accept an optional path as its first parameter. The _index.js_ would only be used to instanciate the aforementioned class (no breaking change that way):

```
import Config from 'config/config';

export default new Config('/tmp/config'); // new Config() would search `process.env.NODE_CONFIG_DIR` or `process.cwd()`
```

Am I missing something?

**Comment by lorenwest** [comment]
Yes you're missing [$NODE_CONFIG_DIR](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir). In your bootstrap .js file:
```
process.env.NODE_CONFIG_DIR="some generated string"
var config = require('config');
```

**Comment by aymericbeaumet** [comment]
The issue is I cannot do it in the global context, as I'm working on a monorepo tested from the root with Jest, like so:

```
/
  packages/
    a/
      config/
    b/
      config/
```

The test process would be the same for both the _a_ and _b_ packages.

**Comment by lorenwest** [comment]
I don't think node-config will ever support loading multiple configs from
multiple locations. You can change the location, but you can't have
multiple locations.

The node-config team feels it's important to have a single, well known
location for configs, so anyone that understands the config library can
quickly find the configs at 3am when the datacenter calls.
ᐧ

**Comment by aymericbeaumet** [comment]
I agree with you having a single source of truth prevents a lot of issues.

In my use-case, the configuration will be loaded from different CWDs in two different situations:
- when running the test with Jest, the CWD will be the project root (to leverage the watch mode on the entire project), in that case each test needs to access the configuration for the package (which is not in CWD)
- when deploying each package, the CWD will be package-X, in that case the source code in library also needs to resolve the configuration for the package (which is in the CWD)

This looks like this:

```
/ # cwd during test
  packages/
    package-a/ # cwd during production
      config/
      src/
        index.js # resolves package-a/config
    package-b/ # cwd during production
      config/
        index.js # resolves package-b/config
```

To address this issue, I did create an _index.js_ in each _config_ folder, and I use this trick to indicate I want to load the configuration from the current folder:

```js
import config from 'config';
import path from 'path';

const loaded = config.util.loadFileConfigs(path.resolve(process.cwd(), __dirname));

export default {
  get: config.constructor.prototype.get.bind(loaded),
  has: config.constructor.prototype.has.bind(loaded),
};
```

This works but has two downsides:
- the `config` package is always required first, which immediately tries to find and load the configuration, but during the test it doesn't exist in the CWD
- the code is redundant amongst the packages

My point is just to separate the `Config` class in a separate file so that it could be required without triggering a config resolution. That way something like this would be possible:

```js
import Config from 'config/config';
import path from 'path';

export default new Config(path.resolve(process.cwd(), __dirname));
```

**Comment by lorenwest** [comment]
You're suggesting an incompatible interface to configurations, which your private modules may understand, but sub-modules using `node-config` won't participate in. There is no reason for `node-config` to support non-standard interfaces, which makes this a perfect candidate for a fork.

**Comment by aymericbeaumet** [comment]
Been looking into it, seems the Config class is coupled to the global context, harder than I thought. Thanks for your time, will fork 👍

**Comment by zanzamar** [comment]
Sharing some thoughts...

We also use a monorepo, with yarn workspaces:
https://yarnpkg.com/lang/en/docs/workspaces/

It is very convenient to be able to define a `config/test.js`... 

We use `jest` as our testing framework.  We need to "help" `config` a little to know which config to bring in based upon which test is being run.  

Both `jest` and `config` already provide all the necessary functionality to do this.  Mocking `config` and then providing a `NODE_CONFIG_DIR` to `config`.

This would allow more complexity if one needed on a "per test" basis...  Since we just want to use the root `config/test.js` per package in the monorepo ours works nicely...  Mileage may vary, it is `module.parent.filename` that enables this to happen.

```
/**
 * ~/__mocks__/config.js
 * 
 * A customization to config, enabling us to use specific config values for test system
 *
 * Looks for the closets `config/test.js` file to this test... traveling up the directory structure until it finds one
 * or stops at process.cwd
 */

const fs = require('fs');
const path = require('path');

const startDir = path.dirname(module.parent.filename);
const rootDir = process.cwd();

// build the node config directory looking for a config directory from here to root.
function findConfig(lookInDirectory) {
	if (fs.existsSync(`${lookInDirectory}/config/test.js`)) {
		return `${lookInDirectory}/config`;
	}

	if (lookInDirectory === rootDir) {
		throw new Error(`Failed to find configuration for test.  Recursive look from [${startDir}] to [${rootDir}]`);
	}

	return findConfig(path.resolve(lookInDirectory, '../'));
}

// set the config directory and require...
process.env.NODE_CONFIG_DIR = findConfig(startDir);
module.exports = require.requireActual('config');
```
