### ISSUE TITLE
Windows - Running as Admin Doesn't Always Work

### ISSUE THREAD

**Issue by flannelJesus** [lorenwest/node-config#417]
I'm using 1.26 on windows 10. I have the following directory structure

    Project/
    ├── index.js
    ├── package.json
    ├── config/
    │   └── default.yml
    ├── bin/
    │   ├── stuff.js
    │   └── otherStuff.js
    └── nodeModules/
        ├── module1/
        ├── module2/
        └── config/    

I 'require' config in stuff.js and otherStuff.js, but I think this problem would exist even if I required it in index.js.

When I run powershell **not** as administrator, I can call `node "C:\Project\index.js"` from anywhere and it will run just fine.

When I run powershell as administrator, calling `node "C:\Project\index.js"` *only* works when I'm in C:\Project in the powershell. I cannot run it from anywhere else, it breaks, it cannot find the config file.

This doesn't seem like expected behaviour to me.

**Comment by markstos** [comment]
node-config is documented to look for the ./config directory relative to $CWD, and or possibly $NODE_CONFIG_DIR if you set that: https://github.com/lorenwest/node-config/wiki/Configuration-Files#config-directory

So the case you say "breaks" is node-config working as documented.

**Comment by flannelJesus** [comment]
but if that is working as documented, then it's *not* working as documented when i run not as administrator

**Comment by markstos** [comment]
@flannelJesus If there's a bug, please submit a test case to the test suite that fails in your environment.
