### ISSUE TITLE
Why Node-config can't set Config values?

### ISSUE THREAD

**Issue by DanielTimLee** [lorenwest/node-config#418]
How about node-config can set config file's value while the node process is running?

such like this.
```js
var cfg = require('config');
cfg.set('Customer.dbConfig',{value:'true'});
```

Is node config can set it's own config value and write it on to the config file?
If not, is there any available ways to achieve it?  
**(Do I have to open config file (while in running process) and write config value on it?)**

**+(ps. can't I raise `WARNING: No configurations found in configuration directory` this to an Error that I can manage with Try catch?)**

**Comment by lorenwest** [comment]
Configurations aren't immutable by design. There's a long history of this issue, available by searching this forum.

As for the 'no configurations found' warning turning into an error, you're going to get an error on your first get() if the configuration isn't loaded.

**Comment by DanielTimLee** [comment]
thanks for solution for occuring Error!

**Comment by mayurbhagwat** [comment]
I want to access config/default.json file from another folder but not able to read using standard process
any suggestions?

**Comment by lorenwest** [comment]
Depends on what you mean by _access_. The standard process for accessing that file from another location is this:
```
let otherLocationDefaultFile = require("../path/to/other/location/default.json");
```
Is that not working for you?

**Comment by lorenwest** [comment]
It's probably best to move this discussion to [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**.

**Comment by markstos** [comment]
Agreed. Support questions should be redirected to StackOverflow.
