### ISSUE TITLE
Enforce definition in later file JSON: setting config values explicitly to undefined

### ISSUE THREAD

**Issue by maikthomas** [lorenwest/node-config#422]
The docs https://github.com/lorenwest/node-config/wiki/Common-Usage#using-config-values
 says that "Additionally, setting config values explicitly to undefined is a helpful way to ensure that they must be defined by a later configuration file."

In my case I define the structure in `default.json` but I want the configuration to fail when certain mandatory values haven't been overwritten. However, this statement of setting config value explicity to undefined I don't understand for JSON. `undefined` is not valid json so how would one do this?
Thanks,
Mike

**Comment by lorenwest** [comment]
Thats a good question. If the file type is .js it's easy. Not so easy if it's a .json file.

Set it to `null` instead of `undefined` and see if you get the results you're looking for. If so, feel free to change the wiki page, or let me know and I'll change it.

Thanks for noticing this.

**Comment by maikthomas** [comment]
I got the desired effect by using `[]` instead of using `undefined` (which is invalid json) or `null` (which is an accepted value and just gives null when you read it). 

I don't particularly like leaving `[]` to enforce mandatory parameters but it does effectively enforce it, not allowing the app to run without it.

**Comment by lorenwest** [comment]
That may be the only option for .json files. I'm going to stick with .js files and actual `undefined` values.
