### ISSUE TITLE
how to set Config Directory? 

### ISSUE THREAD

**Issue by xiehongyang** [lorenwest/node-config#425]
Sorry I am too dull to understand this.
I have already set this:
`"server": "set $NODE_CONFIG_DIR=../&&node src/main.js"`
**but when I start, It doesn't work and error appear:**

```
WARNING: No configurations found in configuration directory:***
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
...\node_modules\config\lib\config.js:181
    throw new Error('Configuration property "' + property + '" is not defined');
    ^
```
**what's wrong with my node? Could anyone told me? Thank u!**

**Comment by mbaroukh** [comment]
you should try 
`NODE_CONFIG_DIR=.. node src/main.js`
or
`export NODE_CONFIG_DIR=.. && node src/main.js`

**Comment by xiehongyang** [comment]
@mbaroukh Ok, I will try Thx for u answer

**Comment by gtramontina** [comment]
If I'm not mistaken, you can also do it from within your `main.js` file by setting:
```
process.env.NODE_CONFIG_DIR = './myCustomDir'
…
const config = require('config');
```
At the very beginning, before requiring `config`.

**Comment by xiehongyang** [comment]
Thx for all 👍

**Comment by EIOTAFRICA** [comment]
WARNING: No configurations found in configuration directory:C:\Users\julien karazo\Desktop\devconnector\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the 
environment.
C:\Users\julien karazo\Desktop\devconnector\node_modules\config\lib\config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "mongoURI" is not defined
    at Config.get (C:\Users\julien karazo\Desktop\devconnector\node_modules\config\lib\config.js:182:11)
    at Object.<anonymous> (C:\Users\julien karazo\Desktop\devconnector\config\db.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)   
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\julien karazo\Desktop\devconnector\server.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)        
[nodemon] app crashed - waiting for file changes before starting...

**Comment by siddharth-synapseindia** [comment]
WARNING: No configurations found in configuration directory:E:\Krishna\Home\node_project\node_crud_auth\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
E:\Krishna\Home\node_project\node_crud_auth\node_modules\config\lib\config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "jwtPrivateKey" is not defined
    at Config.get (E:\Krishna\Home\node_project\node_crud_auth\node_modules\config\lib\config.js:182:11)
    at module.exports (E:\Krishna\Home\node_project\node_crud_auth\startup\config.js:5:15)
    at Object.<anonymous> (E:\Krishna\Home\node_project\node_crud_auth\index.js:10:28)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

**Comment by UtmostCreator** [comment]
> If I'm not mistaken, you can also do it from within your `main.js` file by setting:
> 
> ```
> process.env.NODE_CONFIG_DIR = './myCustomDir'
> …
> const config = require('config');
> ```
> 
> At the very beginning, before requiring `config`.

Also it is possible to do it this way:
```
process.env['NODE_CONFIG_DIR'] = path.join(__dirname, 'config/')
// ...
const config = require('config');
```

**Comment by alannaidon** [comment]
Hi. I know this is kind an old thread, but I couldn't get any help from stackoverflow.  
I'm doing exacly as the doc says but still getting the error. Anyone could help?

code:

My file is at `project/src/config` (Which is the folder I want to use for node-config and will also include other config files)  
This folder holds all the configs from this project
```
process.env['NODE_CONFIG_DIR'] = __dirname;
console.log(process.env['NODE_CONFIG_DIR']); // prints correctly `project/src/config`
import * as config from 'config';

const myConfig = config.get('myConfig')
```

The code produces: 
```
WARNING: No configurations found in configuration directory:/home/user/project/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.

home/user/project/node_modules/config/lib/config.js:179
throw new Error('Configuration property "' + property + '" is not defined');
          ^

Error: Configuration property "myConfig is not defined
``` 

Im using a `default.yaml` file with `js-yaml` already installed.
