### ISSUE TITLE
Error Error: Cannot find module '../raw'

### ISSUE THREAD

**Issue by bennyAG** [lorenwest/node-config#427]
This is solved if config is reinstalled with npm install,
 however the problem returns after each deploy.
Node v 5.
config: 1.26.1
npm: 3.3.6

**Comment by markstos** [comment]
This sounds like an environmental problem of referencing an outdated version of `node-config`. Are you able to add a test to the test suite which reproduces the problem?

**Comment by markstos** [comment]
Never heard back from OP. Closing
