### ISSUE TITLE
 TypeError: config.get is not a function

### ISSUE THREAD

**Issue by mohamedMahran** [lorenwest/node-config#429]
this is error displayed when I try to use config.get to read url from default.json file , I will be appreaciated if anyone have an answer for this problem and below snippet of my code if anyone need any details 

var webdriver =require('selenium-webdriver');
var config = require('../config/default.json');
var driver = new webdriver.Builder().usingServer('http://localhost:4444/wd/hub').withCapabilities( webdriver.Capabilities.chrome() ).build()
 class BasePage {
	constructor( ) {
		global.driver=driver;		
			}
	navigateToTheHomePage() {
		var url = config.get('url');
		driver.get(url);
                }
	}
module.exports =BasePage;
and my config file is a default.json as like below 

{
"Paramters": 
    {
    "URL": 
      { 
        "url": "http://ralphsays.github.io"
       }
    }
}

**Comment by lorenwest** [comment]
That's not how to use config. 

```
var config = require('config')
```

You've put the values of config.json directly into a config object. Those values don't have methods like get().

**Comment by mohamedMahran** [comment]
Thanks very much , I appreciate your help , the problem has been resolved 
1- I installed config-js using npm install config-js
2- these my current config.js
module.exports={
"baseURL": {
    URL: "http://ralphsays.github.io"
  }
}
3- finally I get the URL value through below code 
var Config = require('config-js');
var config = new Config('../config/config.js');
navigateToTheHomePage() 
	{
		var url=config.get('baseURL.URL');
		driver.get(url);
	}
