### ISSUE TITLE
Possibility to use references to sub config parts

### ISSUE THREAD

**Issue by stalniy** [lorenwest/node-config#431]
**Expected Behavior**:

I have several functions which consumes own configuration + logger configuration, so I'd like to reference logger configuration from another configuration (Such behavior exists in Ruby on Rails Yaml parser, [more info](https://stackoverflow.com/questions/6651275/what-do-the-mean-in-this-database-yml-file#answer-6651436))

```js
{
  domainTracker: {
     "logger": {
        "<<":  "*logger",
     }
     "path": "/api"
  },

  "errorHandler": {
     "logger": {
        "<<":  "*logger",
     }
     "debug": true
  },

  "logger": {
     "server": "..."
  }
}
```

afterwards when I do `config.get('domainTracker')` I expect logger configuration to be included as part of `domainTracker` configuration:

```js
const config = config.get('domainTracker');

/*
{
  "domainTracker": {
     "logger": { "server": "...." },
     "path": "/api"
  }
}
*/

callMe(config);
```

**Actual Behavior**:

I need manually pass different configurations into my functions:

```js
callMe(config.get('domainTracker'), config.get('logger'));
```

This is a bit inconvenient in case if you want all your functions to have standardized API (e.g., single argument with `options` object) and configure each function independently. So, this can be called kind of "Config injection" feature :)

**Comment by markstos** [comment]
You can refer to other parts of the configuration when using the JavaScript file format and `defer()` functions as documented here:  https://github.com/lorenwest/node-config/wiki/Configuration-Files#javascript-module---js

If you want to store parts of the configuration in JSON, the JavaScript config file format can read in JSON files. 

Does that address your need?

**Comment by stalniy** [comment]
Actually I would prefer to keep my config simple and not use JS. 

It would be good at least to provide a simple way to register key processor, so I can implement this as a separate extension

**Comment by iMoses** [comment]
@markstos I think it can be closed..
The new `Parser` enables the ability to create such customizable parsers..
