### ISSUE TITLE
If NODE_ENV is not set in the environment, a default value of development is used.

### ISSUE THREAD

**Issue by gmaglio** [lorenwest/node-config#432]
Not true.

The following found in [Configuration Files|https://github.com/lorenwest/node-config/wiki/Configuration-Files] but it is not true.

Default NODE_ENV

If NODE_ENV is not set in the environment, a default value of development is used.

**Comment by markstos** [comment]
See: https://github.com/lorenwest/node-config/blob/master/lib/config.js#L643

If you find it to be not true, submit a failing test for the test suite which demonstrates it's not true and we'll re-open this.
