### ISSUE TITLE
These modules were not found

### ISSUE THREAD

**Issue by skumblue** [lorenwest/node-config#433]
Hi!

When I run my project, it shows me:
<img width="586" alt="screen shot 2017-09-15 at 11 13 58 am" src="https://user-images.githubusercontent.com/3875593/30486365-b51bc8a0-9a06-11e7-9d5e-687748e4fdde.png">

In the **node_modules** folder exist only _json5_ dependence:
<img width="290" alt="screen shot 2017-09-15 at 11 15 56 am" src="https://user-images.githubusercontent.com/3875593/30486448-fb16e97a-9a06-11e7-91c9-7e56ffa438e1.png">

I have to run `npm install --save fs hjson toml cson properties x2js` or is a bug in the library?

Thanks!

**Comment by lorenwest** [comment]
Those are `devDependencies`. Are you trying to run the tests without performing an `npm install` in the config directory?

**Comment by skumblue** [comment]
@lorenwest I think I did not explain myself.

I follow the [Quick Start](https://github.com/lorenwest/node-config#quick-start), and when I run my project `npm run dev`, the console show me:

<img width="586" alt="screen shot 2017-09-15 at 11 13 58 am" src="https://user-images.githubusercontent.com/3875593/30503706-a3e35950-9a41-11e7-8d28-f418b67d8566.png">

My doubt is:

To fix it, do I need to install all those modules (fs, hjson, toml, cson, properties x2js) in my `devDependencies`?

**Comment by lorenwest** [comment]
You may have to put them into your devDependencies. Try it.

I'm suspect of the program that spit out this error statement, because the `fs` module is built-in. Do you have some transpile environment that doesn't know about nodejs?

**Comment by kaizenberg** [comment]
Sorry for my slow response.

I tried your possible solution, I installed the devDependencies, but not work.

I have a React app using Next.js. Could be babel transpile?

**Comment by markstos** [comment]
Yes. Search issue tracker for React.

**Comment by kaizenberg** [comment]
I found the problem:
https://github.com/zeit/next.js/issues/2734

In Next you must import only universal/isomorphic compatible modules. That means they can't use the `fs` module and other non-universal modules (net, http, etc.).

I use the [Universal Configuration provider by Next.js](https://github.com/zeit/next.js/tree/master/examples/with-universal-configuration)

Close it, and thanks @markstos !
