### ISSUE TITLE
Is it possible to mix the extensions files on config directory?

### ISSUE THREAD

**Issue by slim-hmidi** [lorenwest/node-config#436]
In the config directory of my application I have these files:
````
/config
 custom-environment-variables.json
 default.yaml
 production.yaml
 development.yaml
````
I need a configuration of the test of the app so I created a file ````test.json ```` to the config directory. When I build the app I got this error:
````
Configuration property "sqlite" is not defined
````
So I change the extension of the file test.json to  test.yaml and make some change. The build of the project runs successfully. I found [Configuration-Files](https://github.com/lorenwest/node-config/wiki/Configuration-Files) and it mentions different extensions. So my question is why the problem occurs when I create a config file with ````json```` extension and pass with ````yaml```` extension. Is it possible to mix the extensions of files in the config directories or not?

**Comment by markstos** [comment]
Yes, mixing extensions is supported. I have used it for years. Your problem is elsewhere. Confirm that your JSON is valid.

**Comment by slim-hmidi** [comment]
it's mentioned that: 
````
Custom environment variables override all configuration files, including local.json. Only command line options take precedence over them.
````
Does not the ````custom-environment-variables.json```` file override the ````test.json````  however I mention on the npm test script the ````NODE_ENV=test````?

**Comment by markstos** [comment]
If I had to guess, your code does something like this:

```javascript
var config = require('config');
process.env.NODE_ENV="test";
var config = require('config');
```
If that's the the case, it's too late for setting the environment variable to have an effect. You can use something like [import-fresh](https://www.npmjs.com/package/import-fresh) to make sure the second load of config is not-cached. 

If this is *not* your issue, you should create a reduced-test case that illustrates the problem, and submit a bug report if node-config appears not to be following the documentation.

**Comment by slim-hmidi** [comment]
No I mentioned in package.json:
````
test: "NODE_ENV=test node_modules/.bin/jest
````
In the test.json:
````
{
    "sqlite":
      {
          "client": "sqlite3"
          "filename": "../data/backend.db"
     }
}
````
