### ISSUE TITLE
Can NODE_ENV be changed via nodejs code?

### ISSUE THREAD

**Issue by fractalocity** [lorenwest/node-config#440]
by reading the following page,  [NODE_ENV](https://dzone.com/articles/what-you-should-know-about-node-env) , I get the understanding that NODE_ENV can be changed within your node.js code (ie: while the code is running).

However, when i change process.env.NODE_ENV within the code and then check config's NODE_ENV, I see that it did not change.
process.env.NODE_ENV = 'Testing';
console.log('NODE_ENV: ' + config.util.getEnv('NODE_ENV')); // is still development, did Not change to Testing

**Question**: how do you change the config.util.getEnv('NODE_ENV')) variable? Can I change the file which node-config is looking at in the middle of code execution? This is probably not advised for various reasons. However, was still wondering if this was possible.

**Comment by markstos** [comment]
For support questions, please use StackOverflow and tag your question with node-config. 

https://stackoverflow.com/questions/tagged/node-config

**Comment by fractalocity** [comment]
Thanks for the direction. The stackoverflow link you directed me to has a similar question that answered my question: 
[stackoverflow node-config](https://stackoverflow.com/questions/46369745/how-do-i-override-config-values-at-runtime-with-node-config)

Solution: 
`var config = require('config'); // will contain defaults and/or pre-loaded usr-set environment variables`
` // ... doing stuff in code here`

`// now i want to look at a different config file for one reason or another`
`process.env.NODE_ENV = 'Testing';`
`const importFresh = require('import-fresh'); // (npm install import-fresh)`
`var config_testing = importFresh("config");`
`var a_var = config_testing.has('customer.dbName') ? config_testing.get('customer.dbName') : null;`

**Comment by markstos** [comment]
Great-- sending people to StackOverflow is working.

If you searched the issue tracker here, you would have found similar Q&As
already asked here as well.

     Mark

**Comment by markstos** [comment]
I'll note there's another potential issue here:

The cal to  `require('config')` is hoisted.

So you may have a function that appears that it's setting `process.env.NODE_ENV` at a run time and *then* loading the config module.

But In reality, the `require()` is hoisted and run before the function is called and before `process.env()` is set.
