### ISSUE TITLE
config.get is not a function using Webpack

### ISSUE THREAD

**Issue by svyandun** [lorenwest/node-config#441]
### I'm submitting a ... 
  - [x] bug report

### What is the current behavior?
I followed the [wiki for using Webpack](https://github.com/lorenwest/node-config/wiki/Webpack-Usage). When I run the program, I get:
```
TypeError: config.get is not a function
```
because `config` was exported as JSON.

### Please tell us about your environment:

 -  node-config version: 1.26.2
 -  node-version: 8.4.0

**Comment by fantapop** [comment]
I would also prefer to use get() instead of access the bare object because of the existence checks.

**Comment by markstos** [comment]
@svyandun The wiki is explaining that node-config *doesn't* work with Webpack out of the box. The example shows writing out a *JSON* file. You would access the config structure directly as a JavaScript object on the frontend. There is not node-config object with additional methods in the final product and thus no `.get` method. You are welcome to update the wiki to clarify that. 

If someone wants to code support to make `config.get()` work with Webpack, they are welcome to. However, I don't see that this needs to be the node-config core package. A related package could be used to transform a `node-config` structure into something compatible with Webpack.

I'm closing this now assuming this issue can be well-addressed by a third party project. However, if there's a specific, compelling proposal for a better solution built directly into node-config, this could be re-opened.

**Comment by aheuermann** [comment]
I *think* I found a method that works with webpack and still allows for using `get()` using the `NODE_CONFIG` and `webpack.DefinePlugin`. It seems to be working for me on a serverless project I am working on. I haven't tried it on frontend code - but I assume it should work.

```js
const config = require('config');

const webpackConfig = {
  //webpack plugins config
  plugins: [
    new webpack.DefinePlugin({
      //double stringify because node-config expects this to be a string
      'process.env.NODE_CONFIG': JSON.stringify(JSON.stringify(config)),
    }),
  ],
};
```

I added it to the [wiki](https://github.com/lorenwest/node-config/wiki/Webpack-Usage#option-3)

**Comment by lorenwest** [comment]
Thank you for figuring this out! If anyone can verify this works in client, please add a comment to this thread.
