### ISSUE TITLE
Cannot get resolved value of promise

### ISSUE THREAD

**Issue by scottmas** [lorenwest/node-config#445]
### I'm submitting a ... 
  - [X] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
The following script: 
```bash
npm install config
touch config/default.js
echo 'module.exports = {val: Promise.resolve("val")}' > config/default.js
touch test.js
echo 'const config = require("config"); config.val.then(val => console.log(val))' > test.js
node test.js
```

Causes the following runtime exception:
```
TypeError: Method Promise.prototype.then called on incompatible receiver #<Promise>
```

### What is the expected behavior?
You should be able to define Promises in javascript config values. 

### Please tell us about your environment:

 -  node-config version: Latest
 -  node-version: 8.4.0
 -  OS: OSx

**Comment by markstos** [comment]
I'm unable to reproduce with Node.js 4.4.2 or 8.9.0 and node-config 1.21.

I did have to define `Promise` in the config file first. 

If you continue to find what appears to be a bug, submit a failing test for the test suite as a pull request. 

```
 $ at config/default.js
var Promise = require('bluebird')
module.exports = {val: Promise.resolve("val")}
 $ cat test.js
const config = require("config"); config.val.then(val => console.log(val))
 ```

Result:

```
 $  node test.js
WARNING: NODE_ENV value of 'laptop' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
val
```
