### ISSUE TITLE
Possible to list multiple conf in NODE_ENV

### ISSUE THREAD

**Issue by psmod2** [lorenwest/node-config#446]
Hi,

Maybe not an issue - however does node-config support something like:

`set NODE_ENV=[stage, runlocal]`

So basically I some tests I run, and I want to be able to select the base urls as per stage or production, but in addition if i run the tests locally I want them to do so on `localhost`, but otherwise if i say `runcloud` for them to run on elsewhere e.g. saucelabs.

I've understand that there is a file load order, but i want to be specific.

Thanks.

**Comment by leonardovillela** [comment]
See  #481

**Comment by iMoses** [comment]
@markstos can be closed by #481 (just to remove as many irrelevant issues as possible)
