### ISSUE TITLE
Add native Promise support

### ISSUE THREAD

**Issue by lorenwest** [lorenwest/node-config#449]
This thread is for discussion around adding native `Promise` support to `node-config`. The feature will be complete and merged when tests added by @scottmas in #447 pass, and there is thorough documentation on both native Promise usage as well as async/await usage.

If you're interested in adding this core functionality, please add a comment to this thread and we will discuss the issues here.

**Comment by iMoses** [comment]
I've taken a strong interest in helping to improve this library as much as I can, as I'm already familiar with the code and this is one of the few libraries I've been using in every nodejs project I've started for the last 4 years.

This has been a major pain for me as well, and I isolated the issue to these lines of code:
```
if (prop[property].constructor == Object) {
  _iterate(prop[property]);
}
```
And perhaps the `extendDeep` as well (I checked before but can't remember now):
```
if (util.isObject(mergeInto[prop]) && util.isObject(mergeFrom[prop]) && !isDeferredFunc) {
  util.extendDeep(mergeInto[prop], mergeFrom[prop], depth - 1);
}
```

By iterating over a promise we are actively ruining it.
We can add an `isPromise` util which will separate between normal objects and Promises.
The only issue is there's no native support for detecting promises, so the best method today is to check for the existence of a `then` method on the object (and perhaps other must-appear methods according to the specifications).

What do you say about this approach? Should a send a PR to demonstrate the solution?

**Comment by markstos** [comment]
I'm OK with testing for "thenables" as a proxy for promises. In context, we are only testing values that would appear in config code. There should generally be few functions in configuration, with promises being one exception.

**Comment by iMoses** [comment]
> I'm OK with testing for "thenables" as a proxy for promises. In context, we are only testing values that would appear in config code. There should generally be few functions in configuration, with promises being one exception.

@markstos have you noticed my PR? Have a look at the code.
I find this solution to be more stable and it works great..
Also, I'd love to hear your input about my PR for the double defer bug (noticed I pushed new code).
