### ISSUE TITLE
Any plans to add typing support ?

### ISSUE THREAD

**Issue by kolya182** [lorenwest/node-config#450]
I'm new to TypeScript, and just realized it's missing d.ts to support typing. Library-like Axios already implemented it: https://github.com/axios/axios/blob/master/index.d.ts

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki
