### ISSUE TITLE
Node config not able to read property from correct file

### ISSUE THREAD

**Issue by fcb2** [lorenwest/node-config#451]
Hi, I have two config files in `./config` folder, named `local.json` and `server.json`. 
There is a property `port` in both the config files.
But whenever i start my node application, `port` is always picked from `local.json` file.
Command to run node server:

`set NODE_ENV=server
node app.js`

i am simply using config in app.js as:

`var config= require("config")`

`var port=config.get("port")`

**Comment by lorenwest** [comment]
This is the intended behavior - not a bug. See the wiki regarding files, and pay particular attention to a specially named file `local.json`

**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki
