### ISSUE TITLE
Environment files match if they contain another environment name as a substring

### ISSUE THREAD

**Issue by brett-richardson** [lorenwest/node-config#455]
### What is the current behavior?

Create two different environment configs:
```
development.js
local-development.js
```

Set `NODE_ENV` to be `development`.

Config gets picked up from `local-development.js`

### What is the expected behavior?

Only the config in `development.js` should be used.

### Please tell us about your environment:

 -  node-config version: 1.27.0
 -  node-version: 6.11.0

**Comment by brett-richardson** [comment]
I believe it has something to do with this piece of code:

https://github.com/lorenwest/node-config/blob/master/lib/config.js#L1700

**Comment by markstos** [comment]
This is the documented, intended behavior:

https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order

As "local" is reversed for a specific use by node-config, it is not a suitable "environment" name. Choose "laptop" or some other name to avoid a conflict.
