### ISSUE TITLE
Strict mode warning still refers to NODE_ENV variable even if overriding with NODE_CONFIG_ENV is used

### ISSUE THREAD

**Issue by fedulovivan** [lorenwest/node-config#460]
When environment is overwritten via NODE_CONFIG_ENV, warning message should also consider this.

**Given:**
app is launched as 
`NODE_CONFIG_ENV=ut NODE_ENV=production node index.js`
no configuration file at path _config/ut.json_

**Actual message in console:**
`WARNING: NODE_ENV value of 'ut' did not match any deployment config file names.`

**Expected message:**
`WARNING: NODE_CONFIG_ENV value of 'ut' did not match any deployment config file names.`

**Comment by markstos** [comment]
And what is the `version` found in the `./node_modules/node-config/package.json` that you are using? This is a new feature.

**Comment by fedulovivan** [comment]
@markstos, Right I'm using latest version - 1.28.0 (which was actually upgraded namely for this new feature). But the problem is current warning message may confuse user, since in situation when environment is defined via NODE_CONFIG_ENV, warning message still mentions NODE_ENV.

**Comment by jasonwilliams** [comment]
Bump, this is affecting us to.
It shouldn't moan when you're using NODE_CONFIG_ENV !

ping @lorenwest

**Comment by markstos** [comment]
PR welcome.

**Comment by iCodeOkay** [comment]
@markstos @fedulovivan - PR added 🙂

**Comment by lorenwest** [comment]
Published @3.2.3 - thanks!
