### ISSUE TITLE
Multiple config files too complex

### ISSUE THREAD

**Issue by jamesjwarren** [lorenwest/node-config#461]
### I'm submitting a ... 
- [x] feature request

### What is the current behavior?
Loading config from multiple files based on the file name is overly complex for most use-cases. It is prone to confusion over where config values are coming from. I prefer to leave config management up to the deployment management process, as such I normally have one config file mounted into the application container.

### What is the expected behavior?
It would be nice to be able to explicitly specify the name of the config file to load rather than having to pick a name that is constructed from this https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order. Currently I have to use `local.EXT`, `production.EXT` or `default.EXT` but it would be much cleaner if I could elect to skip this resolution and define the name of the config file to load. Perhaps it could just be an env var like `NODE_CONFIG_FILE`.

**Comment by markstos** [comment]
If you just want a single config file, why use `node-config` at all? You can just store a single configuration in a JSON file and do  `var config = require('./config/default.json');

Or why not just use `config/default.js` exclusively?

Of the several years I've been helping with this project, this is the first request I've seen to support disabling the multiple-files feature. While this might be simpler for you, the change adds a bit more complexity to the code and docs for the vast majority of people who aren't interested in this addition.

**Comment by jamesjwarren** [comment]
Fair enough. I was primarily using it for the great file format support and environment variable overrides but you're right a simpler solution would suffice.
