### ISSUE TITLE
config.get() and nested raw

### ISSUE THREAD

**Issue by akaNightmare** [lorenwest/node-config#467]
### I'm submitting a ... 
  - [  ] bug report
  - [x] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
`default.js`
```js
const { raw } = require('config/raw');

module.exports = {
    logger: {
        name: 'test',
        streams: [
            {
                type: 'stream',
                stream: raw(process.stdout),
                level: 'debug',
            },
        ],
    },
};
```
`some-other.js`
```js
const config = require('config');
console.log(config.get('logger'));
// ACTUAL: { name: 'test',
  streams: [ { type: 'stream', stream: [RawConfig], level: 'debug' } ] }
```

### What is the expected behavior?

// EXPECTED: { name: 'test',
  streams: [ { type: 'stream', stream: [__WritableStream__], level: 'debug' } ] }
### Please tell us about your environment:

 -  node-config version: 1.29.4
 -  node-version: 8.9.4

**Comment by markstos** [comment]
@patrickpilch Are you up for helping with this bug in the `raw()` feature you contributed?

The problem comes up when a `raw()` value is not the direct target of a `config.get()` call, but is part of larger object that was requested.

**Comment by patrickpilch** [comment]
@markstos Yes, I will take a look at this as soon as I can. 

@akaNightmare In the meantime, would the following suffice as a solution in your case? You'll treat the whole object as raw, therefore losing some functionality like nested `get()` and immutability, but it could get you moving forward.

```javascript
module.exports = {
    logger: raw({
        name: 'test',
        streams: [
            {
                type: 'stream',
                stream: process.stdout,
                level: 'debug',
            },
        ],
    }),
};
```

**Comment by akaNightmare** [comment]
@patrickpilch Thank you, however `streams` property is dynamic, that means for diff environments `streams` can be different and it is not the option for me. I made some dirty hack for that:
```js
const logger = bunyan.createLogger({
    ...loggerConfig,
    streams: loggerConfig.streams.map(stream => ({
        ...stream,
        stream: stream.stream.resolve(),
    })),
});

```

**Comment by markstos** [comment]
I look forward to these patches. I'm a `bunyan` user also. I happened to dodge the bullet because I only need `stream` set to the default value of `process.stdout`, therefore I don't need to include the default in the config file.

**Comment by akaNightmare** [comment]
@patrickpilch it does not work with nested raw in array:
```js
const { raw } = require('config/raw');

module.exports = {
    logger: {
        name: 'test',
        streams: [
            {
                type: 'stream',
                stream: raw(process.stdout),
                level: 'debug',
            },
        ],
    },
};
```

**Comment by markstos** [comment]
I confirmed that `defer` works in the array case:

# In ./config/default.js

const raw = require('../raw').raw;
const defer = require('../defer').deferConfig;

module.exports = {
    logger: {
        name: 'test',
        streams: [
            {
                //stream: raw(process.stdout),
                "defer": defer(cfg =>  "defer in array"),
                "raw":  raw("raw in array")
            },
        ],
    },
};

# In a test file:
var res = config.get('logger.streams');

console.log(res);

The result is that the deferred value got resolved, but the raw value did
not:

[ { defer: 'defer in array',
    raw: RawConfig { resolve: [Function] } } ]

**Comment by patrickpilch** [comment]
@markstos I resolved this by augmenting `util.makeImmutable` to support Arrays in addition to objects. But that change may come as a surprise to some users that were modifying arrays in their configurations that were meant to be immutable. But perhaps this is okay because the intent and documentation state the configuration will be immutable unless that functionality is disabled. What are your thoughts?

**Comment by markstos** [comment]
@patrickpilch I'm interested to see your patch. 

Arrays end up getting treated a bit differently because there's no clear way to merge arrays in configurations, we don't. We only allow replacing arrays instead.

That said, the intent would be for them to become immutable as well.
