### ISSUE TITLE
Global configuration feature

### ISSUE THREAD

**Issue by georgii-ivanov** [lorenwest/node-config#468]
I'm using latest node-config. Currently, I have a couple of projects with local configs and another project with general config.

This my current structure:

`ProjectA/configs/{production, staging, integration}`
`ProjectB/configs/{production, staging, integration}`
`Common/configs/{production, staging, integration}`

I need to load `Common/configs` files inside ProjectA and ProjectB using locally defined `NODE_ENV`.

Is this feature currently supported? How to implement something like that?

Thanks!

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow]
