### ISSUE TITLE
Unable to parse the correct boolean type in YAML

### ISSUE THREAD

**Issue by zorji** [lorenwest/node-config#470]
### I'm submitting a ... 
  - [x] bug report

### What is the current behavior?

YAML reader returns "no" instead of false.

1. Create a file development.yaml under /config in the current directory with the following content
```yaml
is_enabled_1: no
is_enabled_2: false
```
2. Install the latest node-config and run the following
```js
var config = require('config');
console.log(JSON.stringify(config.get('is_enabled_1'))); // => 'no'
console.log(JSON.stringify(config.get('is_enabled_2'))); // => false
```

### What is the expected behavior?

I expect both returns false. According to the YAML spec, "no" without quotes is an acceptable form of FALSE. See http://yaml.org/type/bool.html

### Please tell us about your environment:

 -  node-config version: 1.29.4
 -  node-version: 8.9.1

**Comment by markstos** [comment]
@zorji Is this an issue if you use js-yaml@3.2.2 directly or is it related to how we use the YAML parser?

**Comment by zorji** [comment]
Hi @markstos I can confirm this is an issue in the latest js-yaml@3.10.0. Should I close this issue?

**Comment by zorji** [comment]
"yes", "no" boolean is a spec in YAML 1.1 only. YAML 1.1 is the current version but js-yaml decided to support the latest 1.2 but not the current 1.1 so the support for "yes", "no" was dropped.

Related Git merge https://github.com/nodeca/js-yaml/issues/266
