### ISSUE TITLE
Feature Request: Getters?

### ISSUE THREAD

**Issue by Jakobud** [lorenwest/node-config#477]
### I'm submitting a ... 
  - [X] feature request

### Please tell us about your environment:

 -  node-config version: 1.30.0
 -  node-version: 8.10.0
 
### Other information

I'm wondering if there is a way to have getters added to this module. An example of why this would be useful:

I have a particular config value that is expected to be an integer greater than 0 (zero) or false otherwise. When I initially read in this config value, I do some basic validation to ensure that it is an integer greater than 0:

```
// Normalize and error check maximum depth option
let depth = parseInt(config.get('depth'))
depth = Number.isInteger(depth) && depth > 0 ? depth : false
```

The code simply checks to see if it's a integer greater than zero. If it isn't then it sets it to `false`.

I use this config value in many modules in my package. For every module, I have to include this "validation" code. It would be nice if I could declare a custom method for getting my `depth` config value. So that everytime the value of `depth` is retried from the config, it would run it through this custom method automatically. That way I don't need to repeat this same validation code in every single module in my project.

Is it possible to do anything like this now? Or is this something that would be a feature request that would be considered?

An alternative would be to add in a `.set()` method. Upon initialization, I would get my config value, validate it, and then set the validated value to the config. That way when the config value is requested in subsequent calls, it has already gone through the validation.

**Comment by lorenwest** [comment]
There's a not-so-well-advertised capability of node-config that allows you to `set` configurations, as long as it's done in your bootstrap after the first `require('config')` and before the first `get()` from that config.

``` javascript
var config = require('config');
config.depth = (your sanitation code);  // This will work
var depth = config.get('depth'); // Gets sanitized value
config.depth = "somebody trying to set it to something else"; // Throws an exception
```

I think that's your best solution, and doesn't poke at the `.set()` pandora's box.

ps: if you need a `get` for your sanitation code, don't call `get()`, but address the config value directly.

**Comment by markstos** [comment]
@Jakobud Did you try to use getters? `node-config` has supposed them in `.js` configuration files since 2014. See #151.    As noted there, they get "flattened" and made immutable on the first `.get()`.

**Comment by Jakobud** [comment]
@markstos Do you mean just setting the value in the `.js` config file equal to a callback?

**Comment by markstos** [comment]
@jaylynch No. `getters` are built into JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by jaylynch** [comment]
@markstos I think you might've been aiming for @Jakobud there, I've not used this in a while... 😅

Good to see it ticking along though!
