### ISSUE TITLE
NODE_CONFIG bug or confusion?

### ISSUE THREAD

**Issue by Jakobud** [lorenwest/node-config#479]
### I'm submitting a ... 
  - [X] bug report (maybe?)

### What is the current behavior?
`process.env.NODE_CONFIG` does not appear to come up when using `getEnv`. Also it doesn't appear to overwrite any values. Here is my code (my configuration has a property called `imagesPerSecond` with a value of `10`):

```
const config = require('config')

console.log(config.get('imagesPerSecond'))
console.log(config.util.getEnv('NODE_CONFIG'))

process.env.NODE_CONFIG = JSON.stringify({
  imagesPerSecond: 100
})

console.log(config.get('imagesPerSecond'))
console.log(config.util.getEnv('NODE_CONFIG'))

console.log(process.env.NODE_CONFIG)
```

output:

```
10
{}
10
{}
{"imagesPerSecond":100}
```

### What is the expected behavior?
Maybe I'm misunderstanding the doc's. But looking at this example:

https://github.com/lorenwest/node-config/wiki/Altering-configuration-values-for-testing-at-runtime

It appears I should be able to override values in the `NODE_CONFIG` variable at runtime. In my example above, it doesn't appear to work. And the `getEnv()` method returns an empty object.

The [wiki here](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config) describes it as this:

> The current value of NODE_CONFIG, mixed from the O/S environment and command line is available in config.util.getEnv():

So I would think in my example it would not give me an empty object but rather it would give me a full object of my current config.

Also my above example I am attempting to override `imagesPerSecond` config value, but obviously it doesn't appear to work.

Also the [wiki page](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config) says

> This allows you to override any configuration from the command line or shell environment.

So maybe you shouldn't be able to alter `NODE_CONFIG` at runtime but the other wiki page clearly says you can. So that is not really clear.

Perhaps I'm just misunderstanding something here.

### Please tell us about your environment:

 -  node-config version: 1.30.0
 -  node-version: 8.10.0
 
### Other information

Just testing this in OSX

**Comment by markstos** [comment]
`node-config` is immutable after the first call to `.get()`.

Try setting your environment variable:

  1. Before `node-config` is required and
  2. After `node-config` is required, but before the first call to `.get()`.

We intentionally don't want the configuration to be mutable after it has started to be used.

**Comment by Jakobud** [comment]
Ah okay I understand now. Thank you
