### ISSUE TITLE
Problem when running tests with node 4.0.0

### ISSUE THREAD

**Issue by leonardovillela** [lorenwest/node-config#487]
### I'm submitting a ... 
  - [x] bug report

### What is the current behavior?
When I am going to execute the "npm test" task the following error occurs:
```
/home/g4nd4lf/dev/nodejs/node-config/lib/config.js:963
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: '/home/g4nd4lf/dev/nodejs/node-config/test/config/default.coffee': Error: Cannot find module 'coffee-script'
```

### What is the expected behavior?
Run the tests normally, in version 6.0.0 of node the tests run successfully.

### Please tell us about your environment:
 -  node-config version: master branch
 -  node-version: 4.0.0
 
### Other information
I encountered this problem while running a project issue

**Comment by lorenwest** [comment]
Hi @leonardovillela, we've moved towards not supporting Node V4 any longer, because our Travis tests are getting harder to pass in that version. Are you submitting this because you are using 4.x, or because you want tests to pass in all environments?

**Comment by leonardovillela** [comment]
Hi @lorenwest, ok makes sense. I'm submitting this, because in other issue when you instructed me to start contributing it spoke for me to ensure it works in version 4.x of the node and `package.json.engine` = 4.0.0, so I thought it was a prerequisite.

**Comment by lorenwest** [comment]
We've had discussion on another thread about dropping support for 4.0, and are keeping an eye out for folks that may still have that requirement.
