### ISSUE TITLE
error TS2688: Cannot find type definition file for 'source-map'/'ts-node'

### ISSUE THREAD

**Issue by envil** [lorenwest/node-config#493]
### I'm submitting a ... 
  - [ x ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
Cannot parse default.ts file.
error TS2688: Cannot find type definition file for 'ts-node'
OR
error TS2688: Cannot find type definition file for 'source-map'

### What is the expected behavior?
Can parse default.ts file without any error.

### Please tell us about your environment:

 -  node-config version: 1.3.0
 -  node-version: 8.9.0
 -  typescript: 2.4.2
 
### Other information
After I'd added ts-node@4.1.0 and source-map@0.7.3 to devDependencies, the problem went away.
Probably related to this issue: https://github.com/TypeStrong/ts-node/issues/385

(e.g. are you using an environment besides Node.js?)

**Comment by markstos** [comment]
TypeScript hinting is maintained externally to this project, which is not written in TypeScript. As far as I'm aware, there's nothing to change in this project, so I'm closing this.

If there's a specific change you'd like in `node-config`, re-open the issue.
