### ISSUE TITLE
config is immutable when setting attributes from dependencies since >1.26.1

### ISSUE THREAD

**Issue by kilianc** [lorenwest/node-config#496]
### I'm submitting a ... 
  - [x] bug report

### What is the current behavior?
Root config is immutable when setting it from a dependency

### What is the expected behavior?
config to me mutable if `ALLOW_CONFIG_MUTATIONS = true`

### Please tell us about your environment:

 -  node-config version: >1.26.1
 -  node-version: 10.6
 
### Other information

```js
// dep.js in node_modules
const config = require('config')
config.example = false
config.log(config) // example === false
```

```js
// server.js in root
const dep = require('dep')
const config = require('config')
config.log(config) // example === true
```

This behavior broke after 1.26.2 release

**Comment by markstos** [comment]
In both your modules, can you run `console.log(require.resolve('config'))`  and confirm `config` is being loaded from the same paths?

**Comment by kilianc** [comment]
@markstos yes. The issue arises when the app and the deps require two different versions of config. Def counterintuitive. I ended up marking config as `peerDependency`

**Comment by markstos** [comment]
@kilianc Ah, so if the main app and the sub-dependency happened to require the same version of `config`, then the behavior would be different?  Yes, I can see how that would be confusing.

Thanks for the tip about using `peerDependency` to resolve this.
