### ISSUE TITLE
Make default config override undefined values

### ISSUE THREAD

**Issue by Telokis** [lorenwest/node-config#503]
### I'm submitting a ... 
  - [  ] bug report
  - [x] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
Given this config:

```js
// default.js

require("dotenv").config();

module.exports = {
    port: 8080,
};
```

```js
// development.js

module.exports = {
    port: process.env.PORT,
};
```

I get `undefined` for `config.port` when the env variable is not set.

### What is the expected behavior?
I would expect to get `8080`.

I don't want values to be overridable by `undefined` (`null` is fine, though).  
To have this behavior, I would have to do

```js
    process.env.PORT || 8080,
```

which is very inconvenient since I would have to put it in all of my config files.

### Please tell us about your environment:

 -  node-config version: 1.30.0
 -  node-version: 10.10.0

**Comment by markstos** [comment]
First, the current behavior is a valuable way to let override configs unset a default config. 

Second, I think if you used the built-in support for custom environment variables, your problem would go away, correct?

https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables

**Comment by Telokis** [comment]
Thanks for answering, @markstos !
Will this file take my `.env` into account given the fact I load it inside my `default.js` config?
If yes, it's definitely a good solution to my problem. Otherwise, do you have a suggestion to make it load it?

**Comment by markstos** [comment]
> Will this file take my .env into account given the fact I load it inside my default.js config?

Test it.

**Comment by Telokis** [comment]
Ok, it works like a charm. Thank you very much. It has the exact behavior I was looking for.
