### ISSUE TITLE
config.get returns a reference, instead of a copy

### ISSUE THREAD

**Issue by fgheorghe** [lorenwest/node-config#505]
Not sure if this is a bug or not, but the 'get' method call for a config value which is an object returns a reference rather than a copy. 

This means that any changes to the returned config value, would update the config value - this behaviour not being expected for a READ method and is inconsistent with get calls for non object values.

### What is the current behavior?
let value = config.get('test') -> where test is an object.
value.testKey = 'test'
console.log(config.get('test')) -> the config 'test' value has been updated with a new key: 'testKey'.

### What is the expected behavior?
If a config value is an object, a copy of it should be returned, such that value.testKey does not affect subsequent calls to .get(). Instead of the user making a copy using Object.assign or something else, this is what I would expect .get to do.

### Lib version:
^1.26.x

**Comment by markstos** [comment]
@fgheorghe Please re-test with the current version and report your findings.

**Comment by markstos** [comment]
@fgheorghe We intend to make the config structure immutable after the first call to `get()`: https://github.com/lorenwest/node-config/wiki/Common-Usage  So call `.get()` twice in twice to see if you get the same result the second call.

**Comment by markstos** [comment]
@lorenwest Our docs are not quite right here. We say "immutable *after* the first call to get()", but that's not quite right. The code shows we make it immutable *during* the first call to `.get()`.

The current docs imply that the first call to `.get()` could return a mutable structure, while the code shows that the  *first* call to  `.get()` returns an immutable structure. 

Ref: https://github.com/lorenwest/node-config/wiki/Common-Usage

**Comment by fgheorghe** [comment]
@markstos thank you for your reply, I will test it asap, and get back to you with my findings. An immutable structure, on first / subsequent calls is perfect.

**Comment by lorenwest** [comment]
Thank you @fgheorghe for bringing this up and testing in your environment. Our intention is to make the entire config structure immutable during the first call, and we need to know if there's a condition that allows mutation of the returned object. This approach is much preferred to copying on every read.

**Comment by fgheorghe** [comment]
Hmm, with version 2.0.1, it seems like this is still happening:

`const config = require('config')

let test = config.get('Customer')
console.log(test)
test.FIND_ME = 'FIND ME'
console.log(config.get('Customer'))`

Results in:
`{ dbConfig: { host: 'localhost', port: 5984, dbName: 'customers' },
  credit: { initialLimit: 100, initialDays: 1 } }
{ dbConfig: { host: 'localhost', port: 5984, dbName: 'customers' },
  credit: { initialLimit: 100, initialDays: 1 },
  FIND_ME: 'FIND ME' }
`

Where default.json is:
`{
  // Customer module configs
  "Customer": {
    "dbConfig": {
      "host": "localhost",
      "port": 5984,
      "dbName": "customers"
    },
    "credit": {
      "initialLimit": 100,
      // Set low for development
      "initialDays": 1
    }
  }
}
`

**Comment by markstos** [comment]
So the properties returned are immutable, but the object has not been *sealed* against adding new properties, as [`Object.seal()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal) would do.

@lorenwest Can you think of any drawbacks to adding this extra level of immutability?

**Comment by lorenwest** [comment]
I could imagine this introducing work for people that took advantage of an un-sealed config object. It would need to be associated with a major version bump, but I'm in favor.

**Comment by fgheorghe** [comment]
Correct re immutable, but not sealed.

Thank you for looking into this issue! I suppose this being included in a major version bump would be the safer approach.

**Comment by markstos** [comment]
I'm in favor as well. @fgheorghe Do you want look at a PR and tests?  It may end up being a bit more complex than one line change, because we recursively make the object immutable.

**Comment by lorenwest** [comment]
Also - not sure when this was introduced, but if it's not available in all
versions of Node that we support, a check for existence of the Object.seal
should be made.

**Comment by markstos** [comment]
@lorenwest Object.seal() was introduced in Node.js 4.9.1. The oldest LTS release we support is Node.js 6.x, so no check should be necessary. 

Ref: https://node.green/

**Comment by fgheorghe** [comment]
@markstos I shall look into one asap, will get back to you once done

**Comment by fernandocanizo** [comment]
This breaks with [meddleware](https://github.com/krakenjs/meddleware), while it's meddleware responsibility to update its code, I'd like to ask what would be the suggested work around?

I'm currently fixing it by not using `config` in the part of the code where I use `meddleware`, I just require my config file, which is JS, and pass `meddleware` a copy of the desired object.

I'd like to know if config provides a cleaner way to solve this without needing `meddleware` to fix this.

**Comment by fgheorghe** [comment]
@joshghent I think this issue can be closed, as the fix is in place, and the discussion has now moved here: https://github.com/lorenwest/node-config/issues/514

@fernandocanizo I am not familiar with meddleware, but I am wondering if ALLOW_CONFIG_MUTATIONS would fix the issue - essentially this would allow for object mutation and would enable the old behavior. More details here:
https://github.com/lorenwest/node-config/issues/514

**Comment by fernandocanizo** [comment]
Beautiful @fgheorghe :D It workedThank you.

Out of curiosity, right a minute before reading your answer I tried this:
```
'use strict';

const config = require('config');

const t = config.get('testIssue505');
console.log('>>> before: ', t.one);
t.one = 666;
console.log('>>> after:', t.one);
```
And got the expected error:
```
$ node test.js 
>>> before:  1
/home/flc/soft/webgis/map-server/cosa.js:7
t.one = 666;
      ^
TypeError: Cannot assign to read only property 'one' of object '#<Object>'
```

So I tried this:
```
'use strict';

const config = require('config');

const t = config.get('testIssue505');
console.log('>>> before: ', t.one);
const tCopy = {...t};
tCopy.one = 666;
console.log('>>> after:', tCopy.one);
```
And it worked ok:

 $ node test.js 
>>> before:  1
>>> after: 666
```

However when I tried this solution with `meddleware` I kept getting the same error. I was pretty puzzled, still I am.

**Comment by fgheorghe** [comment]
No worries!

Not sure about meddlware tho :/

**Comment by fernandocanizo** [comment]
Just for completeness, `meddleware` keeps barking because my solution only copies the first level, while `meddleware` goes inside the object to its full deep. That's why the simple experiment works but not when I pass a shallow copy to `meddleware`.

**Comment by markstos** [comment]
From the thread, sounds like this can be closed now.
