### ISSUE TITLE
No configurations found in configuration directory(with gulp-develop-server)

### ISSUE THREAD

**Issue by Devang142** [lorenwest/node-config#506]
### I'm submitting a ... 
  - [  ] bug report

### What is the current behavior?
My current directory structure is:
sample-node-app(root folder)
  - build
     - config
     - app.js
  - node_modules
  - src
     - config
     - app.ts

So my config  is inside src folder. So when I try to create build with gulp, it copies config folder from src to build. And when gulp start the server, config is referenced from the root directory('/sample-node-app'), instead of '/sample-node-app/src/build'. That's why I am getting fatal error:
 **throw new Error('Configuration property "' + property + '" is not defined');**

Here is the screenshot:
![image](https://user-images.githubusercontent.com/42429844/46142549-f9ef3b00-c274-11e8-805b-71573f167b01.png)

Code inside gulpfile.js to start server :
`gulp.task('server:start', ['build'], function() {
    server.listen({path: 'build/src/app.js'}, function(error) {
    });
});`

### What is the expected behavior?
Config should be referenced from build dir instead of root dir.

### Please tell us about your environment:

 -  node-config version: 2.0.1
 -  node-version: 8.9.4

**Comment by markstos** [comment]
You need to set process.env.NODE_CONFIG_DIR in Gulp.

https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir

**Comment by tuannguyenhoangit** [comment]
In my case, 
app
      |node_module
      |config/production.json
                  /development.json

I know that, default folder is config under root project folder. But no configuration generated.
I'm facing that case and stucking here.
