### ISSUE TITLE
Hostname configuration file with dots in name doesn't work

### ISSUE THREAD

**Issue by arkadyan** [lorenwest/node-config#51]
If the hostname includes dots, (e.g. foo.example.com), the hostname configuration file (foo.example.com.json) does not get picked up by node-config. Instead it is looking for foo.json.

**Comment by tamlyn** [comment]
Have added a note to the wiki about this.

**Comment by lorenwest** [comment]
Thanks!

**Comment by tamlyn** [comment]
Any plans to change the behaviour in v2?

**Comment by lorenwest** [comment]
Would this pull request solve your needs: https://github.com/lorenwest/node-config/pull/237/files

I haven't had the time to analyze the impact to make sure it doesn't break existing installs, and want to get it merged in.

**Comment by tamlyn** [comment]
Perfect. Haven't tested it but from reading it, it looks safe to merge.

**Comment by lorenwest** [comment]
Thanks for taking a look.  I'll get this in asap (probably today).

**Comment by lorenwest** [comment]
Merged.
