### ISSUE TITLE
Add support for secret/secret-{env}.json

### ISSUE THREAD

**Issue by vivek241** [lorenwest/node-config#513]
### I'm submitting a ... 
  - [ X ] feature request

### What is the current behavior?
No support for secret configs i.e. secret.json OR secret-{env}.json
Consider the following file structure and running with NODE_ENV=dev
- default.json
- dev.json
- secret-dev.json

### What is the expected behavior?
The final config value should be from secret-dev.json

### Please tell us about your environment:

 -  node-config version: 2.0.1
 -  node-version: 6.14.4
 
### Other information
We have two types of configs - application configs and environment specific secret configs
Each of them are managed separately and get put into a common folder during deployment.
We are currently achieving the desired functionality using local-{env}.json but the file name is misleading.
I was wondering if this qualifies for a requirement.

**Comment by lorenwest** [comment]
`local.[ext]` is the place to put secrets. Our deployment scripts generate this file as our applications are deployed.

**Comment by vivek241** [comment]
@lorenwest - Thanks! I will close the issue.
