### ISSUE TITLE
Feature Request: Improve custom environment variable support for [.js] configs

### ISSUE THREAD

**Issue by CodyEakins** [lorenwest/node-config#522]
### I'm submitting a ... 
Feature Request

### What is the current behavior?
https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables
(Enabled using an external, statically-named file in the current config directory)

### What is the expected behavior?
For javascript config files, custom environment variables should be read directly from the current environment during initialization.
 
### Other information
I think we should expand the current `config.util.getEnv()` method to do something like this:
```js
/**
 * Dynamically obtains the value of an environment variable
 */
const getEnv = (key: string): string => {
  const env = process.env[key];

  if (env) {
    if (key.toLowerCase().endsWith('_file')) {
      try {
        return fs.readFileSync(env, 'utf8').trim();
      } catch (error) {
        throw new Error(`File system error! ${key} could not be read: ${error}`);
      }
    } else {
      return env;
    }
  } else {
    throw new Error(`Environment error! An environment variable does not exist for a key: ${key}`);
  }
};
```

So that `.js` configs can be structured like this:
```js
const config = {
  database: {
    mongodb: {
      host: getEnv('DB_HOST'),
      port: getEnv('DB_PORT'),
      database: getEnv('DB_DATABASE'),
      options: {
        user: getEnv('DB_USER'),
        password: getEnv('DB_PASSWORD_FILE'), // read from file instead
        useNewUrlParser: true,
      },
    },
  },
});
```

I suppose you can just manually implement this yourself based on your use case, but I don't think this is outside of the scope of this library.

**Comment by markstos** [comment]
Could you say more about the problem the current handling of environment variables?

What do you see as the benefits of the proposed handling of environment variables? 

This proposal is weird in that uses a function calls `getEnv()` which sometimes reads from the environment and sometimes reads from a file. 

If you want to read from the environment, why not just use `process.env` directly?

If you want to read from a file, which not just call `fs.readFileSync()` directly?

**Comment by CodyEakins** [comment]
I'll try to address your questions as best as I can:

**Could you say more about the problem the current handling of environment variables?**
It's not really problematic; it's just that it feels a little clunky for `.js` stored configs. The custom environment variable mapping file is only really necessary for `.json` and other non-compiled file types. In a `.js` config, I can simply state that a configuration option's value is the result of the `getEnv()` function.

**What do you see as the benefits of the proposed handling of environment variables?**

Mostly just simplification (as shown at the end of question 1's answer), though what you mention about `process.env` and `fs.readFIleSync()` is also valid. I think the need for a wrapper function arises when errors occur (an environment variable is not found, or a file cannot be read); it would be very verbose to setup fall backs at each call site otherwise. I think consuming environment variables in config is a common enough practice that we could justify addressing this use case.

It's great that this library is flexible in that it supports multiple config file formats, but treating them all equally seems like a mistake, and not indicative of "true" library support.

**If you want to read from the environment, why not just use `process.env` directly?**  
**If you want to read from a file, which not just call `fs.readFileSync()` directly?**

See question 2's answer; my wrapper function is used as a fall back, and to flag early failures.

---

My `getEnv()` function comes in handy when dealing with Docker Secrets (where sensitive configuration options and secrets are stored in an in-memory file system mounted to a container).

For `.js` configs, this library is most useful for its use of dot notation and basic immutability, though I question if it would be better to interact with a config export directly/natively...

**Comment by CodyEakins** [comment]
I ended up using a custom helper function for my use-case.

There are situations where reading an environment variable's filepath can be valuable, though this may be out-of-scope for this library.
