### ISSUE TITLE
Incorrect handling of typescript config files

### ISSUE THREAD

**Issue by gpaglia** [lorenwest/node-config#524]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [ x ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
The current implementation for ts config files is incompatible with the handling of js config files, as the ts handling foresees a 'default' named export. This has the consequence that, for a nodejs project, the very same code cannot be made to run both in a typical development setup (where the application is executed with ts-node) and in a production setup where the ts files (including the ts config files) would be compiled to js and the resulting compiled sw is run with node.

### What is the expected behavior?
I think the correct approach would be to use the typescript 'export =' instead of the 'export default' schema in the ts config files. In this case the generated js would be exactly equivalent to that of hand-written js files.
The config.js implementation should, in my view, be modified at line 787 from
`configObject = require(fullFilename).default;`
to
`configObject = require(fullFilename)`

In this way, there would be perfect alignment between typescript config files compiled on the fly within config.js, typescript config files compiled offline and read by config.js as plain js config files, and hand-written js config files

### Please tell us about your environment:

 -  node-config version: 3.0.1
 -  node-version: 10.12.0
 
### Other information
I tested the proposed setup in my environment by changing line 787 as indicated above.
exampe of a typescript config file I used:

`
import { IConfig } from './config.interface';

const DEV_CONFIG: Partial<IConfig> = {
    server: {
        host: 'aHost',
        port: 3000,
        rootPath: 'alfa/beta/gamma'
    }
};

export = DEV_CONFIG;
`

This here below is the generated js from offline tsc compilation:

`
"use strict";
const DEV_CONFIG = {
    server: {
        host: 'aHost',
        port: 3000,
        rootPath: 'alfa/beta/gamma'
    }
};
module.exports = DEV_CONFIG;

`

As shown, this way the generated js is exactly the same as one would use if the js file had been hand-written according to the documentation of config.js, therefore there is no need to have typescript config files handled differently with the default export.

**Comment by lorenwest** [comment]
This sounds reasonable, and I would like to hear some discussion from others using typescript.

If this change is made, does it break backwards compatibility?

**Comment by mbovahqo** [comment]
Running into this issue as well.  Only work around I can see is to run the local dev environment like prod, which will likely be quite a bit slower for us since we're using nodemon.

**Comment by keenondrums** [comment]
+1
Current workaround:
```ts
const config = {}

module.exports = {
  ...config,
  default: config
}
```

**Comment by keenondrums** [comment]
@lorenwest this kind of change would not be backwards compatible, but could we handle both cases at first? And then remove the default handler in the next major release?

**Comment by lorenwest** [comment]
With regards to TS support, I'm going to defer any value judgements to the folks in the TS community. As for compatibility, the rules are well established and those aren't value judgements.

**Comment by lorenwest** [comment]
One day I'm hoping JS is extended to include TS so transpilation isn't necessary. Until then, especially with every TS project consuming a TB or so of babel and other support under node_modules, I stay at arms length from it. 

I hope TS fares better than CoffeeScript because there is some value to it.

**Comment by keenondrums** [comment]
@lorenwest ultimately it's you, who makes the decision to merge, isn't it? :)
Anyway, I've come up with a PR. It doesn't break the existing functionality, yet allows us to have consistent exports across `.js` and `.ts` files.
Thank you for your time spent maintaining this super-useful library!
