### ISSUE TITLE
Cannot add property auth_pass, object is not extensible

### ISSUE THREAD

**Issue by wzkun** [lorenwest/node-config#528]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [  ] bug report
 
### What is the current behavior?
I use  valueObj=require('config').get('key'), then it results an error while valueObj.auth_pass='true'.That means  valueObj is not extensible.

### Please tell us about your environment:

 -  node-config version: 3.0.1
 -  node-version: v11.3.0
 
### Other information

(e.g. are you using an environment besides Node.js?)

**Comment by markstos** [comment]
Working as intended. To address this, you can either:

 * Set `auth_pass` in your configuration
 * Clone or copy `valueObj` to get an extensible copy. Modify your copy. 

node-config makes the configuration immutable to avoid problems caused by mutability.

**Comment by wzkun** [comment]
Thanks for your response.
