### ISSUE TITLE
Remove field in production environment

### ISSUE THREAD

**Issue by amitdhawan** [lorenwest/node-config#532]
Can i remove the field in production.js rather than overriding the key or taking the default.js key.
The use case is im running on local env. using aws localstack endpoint but when i run on production i don't need the endpoint key as aws-sdk will handle that.

**Comment by lorenwest** [comment]
Interesting use case. I don't think this is possible, unless you could get access to the global config object and `delete thatConfigObject.property`.

**Comment by markstos** [comment]
You can try setting it to `undefined` or `null`.

With `undefined`, `config.has()` would return false, while with `null`,
`config.has()` would return true, in case the distinction is useful.

**Comment by KidkArolis** [comment]
In this case I usually don't put it into default.js, and only in development.js. This way it's not gonna be there in production, only in development.

**Comment by croraf** [comment]
If there is no such capability it should be added to the library!

**Comment by markstos** [comment]
Closing, as the solutions by @markstos and @KidkArolis seem sufficient.
