### ISSUE TITLE
incorrect loading of the configuration file

### ISSUE THREAD

**Issue by siarheidudko** [lorenwest/node-config#534]
I'm submitting a bug report

 -  node-config version: 2.0.1
 -  node-version: 10.15.0
 -  os: Windows Server 2008 R2

If the hostname is "fitobel" and in the config folder there is a file fitobel.properties. At the same time, NODE_ENV is set as "neska" (the variable is assigned correctly and is visible from process.env.NODE_ENV). It still loads the fitobel.properties. The change in NODE_ENV does not give any results, as well as NODE_CONFIG_ENV.

However, if the fitobel.properties file is not in the config folder, then everything loads correctly.

**Comment by lorenwest** [comment]
@siarheidudko something doesn't seem right about this. If this were a problem, and with millions of downloads, I would have thought it would be uncovered years ago. Maybe something specific about the properties parser on your machine.

The npm package has a test folder. Would you be able to create and post a failing test that we could run in that directory from a clean install?

**Comment by markstos** [comment]
@siarheidudko That's correct. Please refer to the documentation on file load order:

https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order

As documented there, we load a file based on the host name.
