### ISSUE TITLE
Suggestion – env.yml

### ISSUE THREAD

**Issue by KidkArolis** [lorenwest/node-config#538]
Been using this library for probably >7 years now in many many projects. Big thank you! ❤

I've been ocassionally using the `custom-environment-variables.json` feature, it's convenient in a lot of modern deployment environments. And actually I kinda like the separation of these env variables, which I usually only use for secrets, from my main config files that are usually richer and are checked into the repo.

The only thing that bothers me about this is the name of this file. Why couldn't it just be `env.json` / `env.yml`. Right now, I have to look at the docs every time I want to use this, because the name is just not very intuitive (well, it's intuitive, but a bit long and difficult to remember).

I hope you consider this, as it seems to be inline with the minimalistic approach and ergonomics of this library and is still pretty explicit and apt name. This would have to be a major release, since people might have env.yml in their config dir, but I'd think that's fine.

**Comment by KidkArolis** [comment]
With this we could deprecate `custom-environment-variables.json`, but keep supporting it indefinitely. And start prefering `env.json`.

It would have to be a new major release (which is not nice..) in case people have such a file in their config dir, which could cause unexpected issues.

**Comment by markstos** [comment]
This might help in some cases, but we would need to continue maintain docs about "custom-environment-variables.json" vs "env.json", as there could be confusion about the difference. 

Since you are the first person in 5+ years to suggest this was an issue, I'm not included to make the change.

**Comment by lorenwest** [comment]
Our mid-term approach is to do away with `environment-variables.json` in favor of supporting `${env_var}` text templating in all config files, including yml in #536.

I prefer this approach to requiring a separate file for inserting environment variables.

**Comment by KidkArolis** [comment]
Yes! I think that's even better, keeps all the things in one place.

As long as overriding is not confusing. With separate env file, it was overriding all the other config files. I guess now you'd put env var templates into default.yml if they're the same for prod and staging, etc. And then you would use development.yml + local.yml to configure development defaults/settings.

**Comment by KidkArolis** [comment]
I see there was a bit more discussion on the #536. It's not very conclusive. But in any case, no rush with this env.yml thing.

Not sure how to respond to "Since you are the first person in 5+ years to suggest this was an issue, I'm not included to make the change.", that doesn't sound very welcoming to possible improvements? I've also been using this library for 5+ years, so I perhaps bring some experience?
