### ISSUE TITLE
Plugin: AWS secrets

### ISSUE THREAD

**Issue by leonprou** [lorenwest/node-config#539]
I wrote a plugin that taking configurations from AWS Secretes Manager and merging them into the config object: you can see an initial version [here](https://github.com/leonprou/config-aws-secrets). An Example of the usage will follow soon.

I copied some code from the source, so the solution is a little ad-hoc. The best way to generalise it is by a little refactor to separate some functionality to independent methods. Will you be interested in such refactor? I think it's a great project, and it can be improved by user customised plugins.

### I'm submitting a ... 
  - [x] plugin
  - [x] feature request

**Comment by lorenwest** [comment]
We don't really have a plugin mechanism, but that could be a good feature to add.

In the category of merging configs from other locations, the way to do it is to set those values into environment variables, and use the [Custom Environment Variables](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables) logic already built-in.

We may be upgrading that in the future to allow for `${env_var}` template variables, but the above solution already works without changing any code.

**Comment by markstos** [comment]
With the current functionality, this pattern would be possible:

 1. Create a tiny, private module: `my-config`.
 2. With this module, first load the AWS secrets and set them in environment variables as needed.
 3. Load `node-config`, using the secrets found in the environment variables, via custom-environment-variables.json
 4. Export `config` from `my-config` to the caller
 5. In your project code, refer to `my-config`, which will contain a `node-config` object which includes the AWS secrets as well. 

With this approach, it would also be easy to add a bit of custom code to some something like using the AWS secrets only in production, with static values for local development and testing. 

What is the specific plugin API that's being proposed here?

**Comment by leonprou** [comment]
@markstos @markstos That's interesting I did it differently:

1. Loaded the config.
2. Passed the config object to my plugin
3. the plugin loaded the secrets from AWS and updated the config using:

```
      const environmentSubstitutions = config.util.substituteDeep(configObject, secretVariables)
      config.util.extendDeep(config, environmentSubstitutions)
```

I chose to do it that way reading this wiki [page](https://github.com/lorenwest/node-config/wiki/Configuring-from-an-External-Source). Also, I use the config params to load the AWS secrets, so I needed to require the config module first.

**Comment by leonprou** [comment]
@lorenwest @markstos I did a quick PR to show API changes I want to make: https://github.com/lorenwest/node-config/pull/541.

This is how my plugin will look with these changes: https://github.com/leonprou/config-aws-secrets/blob/with_new_config/index.js. It's much simpler now and can work for everyone.

**Comment by lorenwest** [comment]
This is an example of augmenting config values from an external source. It appears the example alters an existing config object after creation. 

While this works in some cases, it doesn't give the user of the config object any notice that the value has arrived, or any way of waiting around until it arrives. I believe this is an anti-pattern.

I prefer storing asynchronous config values as promises vs. the value itself. It makes it clear to the client that the value has to be awaited, how to wait for it, and it's fast for subsequent requests once the promise has resolved.

The alternative is to load all asynchronous config data at bootstrap, pausing the bootstrap until all asynchronous config data has been resolved, then passing the resolved configs along to the first invocation of `require(config)` as environment variables. That way all clients can be assured that all config data is resolved.

In my opinion you don't mix synchronous data with asynchronous data. You either make it all synchronous, or you make it clear that some data is a promise.

**Comment by markstos** [comment]
I agree with @lorenwest and am closing this issue. The pattern I recommend instead is to read the secrets from AWS and write them to an .env file just before the app boots up. This would be about 10 lines of code and someone has already made a tool which does just this: https://github.com/supersoniko/aws-secrets-dotenv   If you are using systemd, this could happen with an `ExecStartPre=` directive before `ExecStart=` fires.   This simple and doesn't mix sync and async config.

**Comment by leonprou** [comment]
Hey everyone,
Thanks for re reviewing this!
I agree that this approach is problematic. Actually I've found out that this is already supported with AWS containerization.
