### ISSUE TITLE
Nobody could grasp the lack of config reloading...

### ISSUE THREAD

**Issue by remon-nashid** [lorenwest/node-config#540]
I know that's a core design decision that was nailed SEVEN years ago. But given the myriad of issues around that counter-intuitive design decision, and maintainers' continuous attempts to redirect people to old issues, shouldn't mutability be considered just one more time?

At least please put a large warning in README.txt to indicate that config is not writable after require('config').

**Comment by lorenwest** [comment]
You'd think after seven years someone would have thought about that. Maybe [$ALLOW_CONFIG_MUTATIONS](https://github.com/lorenwest/node-config/wiki/Environment-Variables#allow_config_mutations)?

Opinionated doesn't have to mean inflexible :)

**Comment by lorenwest** [comment]
Hey - you made it to this issue, so it got you thinking. 

With everything that *can* change within a NodeJS app, it sure is nice to be able to look at a file checked into your source code system, and be confident of the running state of a deployed server.

If that's not your bag, there's ($ALLOW_CONFIG_MUTATIONS)[https://github.com/lorenwest/node-config/wiki/Environment-Variables#allow_config_mutations)

**Comment by remon-nashid** [comment]
I had tried that but `config.util.getEnv('ALLOW_CONFIG_MUTATIONS')` returns `undefined`. Time to consider an alternative npm package such as [nconf](https://github.com/indexzero/nconf). 
Thanks!

**Comment by lorenwest** [comment]
For everyone else that hasn't bailed, and to prevent misinformation, environment variables are set and exported in the shell environment before calling the NodeJS process. 

Alternately you can set `process.env.ALLOW_CONFIG_MUTATIONS="y"` in your bootstrap before calling `require("config")` the first time.

It's possible this feature has gathered dust and no longer works. I noticed there were no tests submitted when the feature was introduced, so if you think you've set the right variable and it's not allowing mutations, submit a test that fails and we'll get it working again.
