### ISSUE TITLE
require('config') loaded nothing in debug

### ISSUE THREAD

**Issue by emclab** [lorenwest/node-config#544]
My nodejs app config = require('config') (3.0.1) returns nothing in debug with VS code. Here is the console output:

     config: 
     Config {}

NODE_ENV is only defined in development.json and loading in development has no problem. 

Here is the files under ./config:

![Capture](https://user-images.githubusercontent.com/946013/54849126-97fe1400-4ca0-11e9-859c-26f3850db3cd.JPG)

What could cause the config module failed to load in debug?

**Comment by markstos** [comment]
Ffor support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

If you believe you've found a bug, please add test case to the test suite which reproduces it.
