### ISSUE TITLE
try-catch in util.parseFile() catches too many exceptions

### ISSUE THREAD

**Issue by aspotashev** [lorenwest/node-config#548]
### I'm submitting a ... 
  - [  ] bug report

### What is the current behavior?

util.parseFile silently returns null when FileSystem.statSync is undefined. Something must be broken in my configuration, but still the failure to parse a file without error logging is misleading: it made me think something was broken in my config/default.yaml which wasn't the case.

### What is the expected behavior?
The try-catch for FileSystem.statSync() should rethrow exception if FileSystem.statSync is undefined. Or better only catch a limited number of exceptions.

### Please tell us about your environment:

 -  node-config version: 3.0.1
 -  node-version: 10.15.0
 
### Other information
-

**Comment by aspotashev** [comment]
Same problem in this code:

```
  try {
    fileContent = FileSystem.readFileSync(fullFilename, 'UTF-8');
    fileContent = fileContent.replace(/^\uFEFF/, '');
  }
  catch (e2) {
    throw new Error('Config file ' + fullFilename + ' cannot be read');
  }
```

If replace() fails, it does not imply that "Config file ... cannot be read". Please move the call to replace() outside of try-catch.

**Comment by lorenwest** [comment]
There may be a world where the `fs` package doesn't include `statSync`.  And in that world, I could imagine the string returned from `fs.readFileSync` wouldn't be a string at all, and doesn't have a `replace` method, or that `replace` method fails with the above syntax. That may be the same world that doesn't understand the meaning of `UTF-8`.

If that's the world you live in and you need finer grained messages than `Config file ... cannot be read`, I'd be happy to merge your pull request.

**Comment by markstos** [comment]
Closing. See https://github.com/lorenwest/node-config/issues/560#issuecomment-506999027 for rationale.
