### ISSUE TITLE
Can't Load configuration for Serverless.

### ISSUE THREAD

**Issue by shankarregmi** [lorenwest/node-config#550]
I have a Serverless project with Nodejs(8.10)
I am using  [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack) that bundles my code.
Everything is working perfect except that my configurations are not loaded with node-config

my project structure looks something like this
```├── README.md
├── __test__
├── config // development.json, staging.json, production.json
├── functions
├── node_modules
├── package.json
├── serverless.yml
└── webpack.config.js
```
my `NODE_ENV` is correctly set from `serverless.yml` and the corresponding config file is inside my config/ directory.

When I deploy my app, `node-config` warns me that it couldn't load the environment specific config. 

**WARNING: NODE_ENV value of 'staging' did not match any deployment config file names.**
**WARNING: No configurations found in configuration directory:/var/task/config**

I tried different approaches to setting `NODE_CONFIG_DIR` explicitly to /var/task/config and it didn't event worked.

I even tried setting value of `NODE_CONFIG` in plugin section of webpack.
```
const config = require('config');
///
plugins: [
    new webpack.DefinePlugin({
      //double stringify because node-config expects this to be a string
      'process.env.NODE_CONFIG': JSON.stringify(JSON.stringify(config)),
    }),
  ],
```
Is there anyway I can fix it or make work with my serverless app?

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki
