### ISSUE TITLE
How can I get item from an array?

### ISSUE THREAD

**Issue by WeihanLi** [lorenwest/node-config#551]
### I'm submitting a ... 
  - [x] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

I can not get item from an array in the configuration file.

``` json
{ 
 "crawlerConfigurations":{
        "ClickDelay": 100,
        "TypeDelay": 200,
        "Selectors": {
            "Search": [
                {
                    "SearchInitUrl": "https://www.wukong.com"
                 }
          ]
  }
}

```

I'm trying to get the `SearchInitUrl` prop of  first Search item, and I'm using 

```
config.get(`crawlerConfigurations:Selectors.Search[0].SearchInitUrl`)
config.get(`crawlerConfigurations:Selectors.Search.[0].SearchInitUrl`)
```

did not work

the error are like this:

![image](https://user-images.githubusercontent.com/7604648/57618962-4fcfe380-75b7-11e9-8837-e8f469a6ddb4.png)

### What is the expected behavior?

return `https://www.wukong.com`

### Please tell us about your environment:

 -  node-config version: 3.1.0
 -  node-version: 10.8.0

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

** closing - wrong forum

**Comment by WeihanLi** [comment]
I've searched on stackoverflow with tag `node-config` before this issue, but nothing useful found

**Comment by WeihanLi** [comment]
StackOverflow question [here](https://stackoverflow.com/questions/56115538/how-can-i-get-item-property-from-an-array-with-node-config)
