### ISSUE TITLE
_substituteVars does not allow numbers and booleans

### ISSUE THREAD

**Issue by Billos** [lorenwest/node-config#553]
The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [ X ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
The [_substituteVars function](https://github.com/lorenwest/node-config/blob/master/lib/config.js#L1182) prevents from using numbers or booleans in the custom-environment-variables.EXT file and throws an error : __Illegal key type for substitution map at : number__

### What is the expected behavior?
Not throwing an error when detecting something else than a string or an object, simply ignoring it, or logging a warning maybe ?

### Please tell us about your environment:
 -  node-config version: 3.1.0
 -  node-version: 12.2.0

**Comment by lorenwest** [comment]
Environment variables are strings. 

See if #272 answers your question.

**Comment by Billos** [comment]
Yes I know, but I mean for other values in the configuration file that we don't want to substitute with a environment variable.

**Comment by sudosoul** [comment]
@Billos

Your custom-environment-variables.json should only contain entries for the values that you _do_ want to override (which are set in the regular config file naming convention - default.json, debug.json - where ${NODE_ENV} maps to the config file). 

If NODE_ENV = debug, then your debug.json config file will be loaded. Else if there is no match, default.json will be loaded. 

Here’s an example of overriding a database password with an environment variable....

production.json
```
{
  “database”: { 
     “username”: “root”,
     “password”: “This will be overridden”
   }
}
```

custom-environment-variables.json
```
{
  “database”: { 
     “password”: “DATABASE_PASSWORD”
   }
}
```

The the usage would be like so:
```
NODE_ENV=production DATABASE_PASSWORD=mySecretDbPassword node app.js
```

When your app executes, printing `Config.get(‘database’)` would print
```
{
  username: root
  password: mySecretDbPassword
}
```

So as you can see, custom-environment-variables.json maps to the property in production.json that we want to override with an environment variable. The name of the environment variable to use is set at the value in custom-environment-variables.json

When I executed the app, I was simply setting two environment variables
1. NODE_ENV = production (so config Module knows to load the config from production.json)
2. DATABASE_PASSWORD = mySecretDbPassword (to override the value that is set for database.password in production.json)

Hope this makes sense!

**Comment by Billos** [comment]
Oh okay, I didn't get that the files would be merged in the end.
That's all for me then, thanks a lot !
