### ISSUE TITLE
object returned from config.get() will not accept properties

### ISSUE THREAD

**Issue by livelong-007** [lorenwest/node-config#558]
This is a bug report or explanation request:

I recently updated from 

    "config": "^1.29.4",

to

    "config": "^3.1.0",

Oddly my Google Strategy using Passport stopped working.  I stepped through the code and found that Google Strategy adds property values to the 'options' object passed to it from the API.

Stepping through the code I see that the options are not added b.c. for whatever reason the object returned from config.get() will not accept new properties.

I found this odd and possibly a bug.  Please help / advise.

I am surprised with so many people using the config and passport packages that this has not been an issue yet.

Also, it is very "hidden" the object looks the same when you console.log it and it looks the same when stepping through the code.  If this is not explicitly documented some where ... where is this documented  .... once again could not find changelog

Here is the issue posted on SO with screenshots ...

https://stackoverflow.com/questions/56802275/ghost-line-does-nothing-even-when-viewing-through-the-node-debugger

Temporary solution is to create a "mutable" object and add properties to it and then pass that to Passport - Google.   Does not look pretty.  Please advise.

    let obj = config.get('Passport').Google;
    let ret = {};
    ret.clientID = obj.clientID;
    ret.clientSecret = obj.clientSecret;
    ret.callbackURL = obj.callbackURL;
    return ret;

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

**Comment by markstos** [comment]
The Changelog is found in the root of the project as History.md:

https://github.com/lorenwest/node-config/blob/master/History.md

**Comment by livelong-007** [comment]
I don't know if this is a bug or a feature but it breaks my code ...

https://github.com/lorenwest/node-config/blob/master/History.md#300--2018-11-20

Is what config.get() returns supposed to be immutable?  I input this return value to Passport and it breaks with a non-relevant error message.  Very annoying.

**Comment by markstos** [comment]
Getting a subset of object properties doesn't have to be so verbose. You could use Lodash `.pick`:

```javascript
"use strict"
const _ = require('lodash');
const config = {
 a: 'b',
 other: 'foo',
 clientID : 2,
 clientSecret: 'SEC',
 callbackURL: 'http://localhost',
}

function before () {
  let obj = config;
  let ret = {};
  ret.clientID = obj.clientID;
  ret.clientSecret = obj.clientSecret;
  ret.callbackURL = obj.callbackURL;
  return ret;
}

function after () {
  return _.pick(config, ['clientID', 'clientSecret', 'callbackURL'])
}

console.log("before", before());
console.log("after", after());
```

It's also clearer for debugging to pass through exactly the properties you need.
