### ISSUE TITLE
Reconsider default profile names

### ISSUE THREAD

**Issue by jashatton** [lorenwest/node-config#563]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [  ] bug report
  - [ X ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

Node-Config has official naming conventions for development, stage, production, and local.  Local is restricted in a way that you shouldn't commit it to your repository.  

### What is the expected behavior?

At a minimum, I would like to see the local profile be opened up to be kept in source control.  

I think in actuality these names shouldn't matter to node-config at all.  These are very implementation specific and different teams and organization may have standard names for their different environments. 

It seems reasonable to have node-config not care about these details and allow teams to chose how they manage their config names for their different environments.  As an example, we use `local` as a shared set of local developer settings and commit that to source control for our other, non-Node.js, projects that way we don't have to share it through other methods outside of source control.  When we tried doing that with node-config we were stunned by the restriction and had to work around it when it didn't seem necessary.  The work around then caused an inconsistency across our other projects that use `local` profiles for running projects locally on developer machines. 

### Please tell us about your environment:

 -  node-config version: x.x.x
 -  node-version: x.x.x
 
### Other information

(e.g. are you using an environment besides Node.js?)
No

**Comment by markstos** [comment]
@jashatton Do you have a specific proposal to address this? How would you handle backwards compatible during the change to the scheme you propose?

**Comment by lorenwest** [comment]
Names matter in configs - otherwise you'll have configs for configs, with hardcoded names for those configs, and proposals to change the names of those configs.

It's turtles all the way down...

**Comment by markstos** [comment]
I agree with @lorenwest. Our config system is already rather configurable. 

Personally, my team wanted to use "local" for something else as well, and other issues here have been opened here with the same interest. We resolved the issue by using "laptop" as the name as the name of a configuration that we commit, leaving "local" for the reserved use by node-config.

I'm leaving this open for now to wait and hear proposals to address this desired change.

**Comment by markstos** [comment]
Related issues:

  * [local.json config bug](https://github.com/lorenwest/node-config/issues/421)
  * [Disabling local-* configs via an env var #337](https://github.com/lorenwest/node-config/issues/337)

**Comment by sudosoul** [comment]
I use ‘debug’ instead of local - even on AWS some resources prefixed with ‘debug’, hints that I’m doing some sort of integration test on a new feature or something

**Comment by jashatton** [comment]
> Names matter in configs - otherwise you'll have configs for configs, with hardcoded names for those configs, and proposals to change the names of those configs.
> 
> It's turtles all the way down...

**Comment by jashatton** [comment]
> Names matter in configs - otherwise you'll have configs for configs, with hardcoded names for those configs, and proposals to change the names of those configs.
> 
> It's turtles all the way down...

I have seen other configuration libraries that do something like what you speak of, it can be useful for shared configurations to support DRY, I will say that it should be something chosen critically.  Because it can be a bad practice for sure.

**Comment by jashatton** [comment]
> @jashatton Do you have a specific proposal to address this? How would you handle backwards compatible during the change to the scheme you propose?

@markstos Just removing the restriction would be enough to support what I think would work.  Full flexibility on naming, and users can use local if they want to use it.  

My question why does local have to be the reserved one.  Technically I could, in an incredibly naive way, flip all the names of the environment and use development for prod.   My point is the restriction is naive because it doesn't really prevent anything anyway.  So why have it? ¯\_(ツ)_/¯

**Comment by jashatton** [comment]
> I use ‘debug’ instead of local - even on AWS some resources prefixed with ‘debug’, hints that I’m doing some sort of integration test on a new feature or something
> […](#)
> On Jul 8, 2019, at 1:23 PM, Mark Stosberg ***@***.***> wrote: Related issues: local.json config bug Disabling local-* configs via an env var #337 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

That is certainly valid.  In my OP I described that we have already standardized, nearly across our dev organization, that local means config for the developer's environment.  It would be nice to maintain this without a seemingly arbitrary restriction preventing it.

**Comment by markstos** [comment]
> Just removing the restriction would be enough to support what I think would work. Full flexibility on naming, and users can use local if they want to use it.

This is not a specific proposal, this just restates your original feature request without addressing how the current functionality of "local-only" configurations would continue to work if "local" was not reserved for this use, nor does it address concerns without backwards compatibility.

**Comment by jashatton** [comment]
> > Just removing the restriction would be enough to support what I think would work. Full flexibility on naming, and users can use local if they want to use it.
> 
> This is not a specific proposal, this just restates your original feature request without addressing how the current functionality of "local-only" configurations would continue to work if "local" was not reserved for this use, nor does it address concerns without backwards compatibility.

Where is backwards compatible needed?  if the configs aren't checked in where is the the breaking change?  

I actually think that having local in the load order is the flaw.  If it isn't intended for consumption by services in a 12 factor way, why even have it codified.

**Comment by markstos** [comment]
> Where is backwards compatible needed? if the configs aren't checked in where is the the breaking change?

"local.js" can't appear twice in the [load order](https://github.com/lorenwest/node-config/wiki/Configuration-Files).  If it starts being loaded before the hostname files instead of after, that's a breaking change. 

Multiple members of my team have absolutely experienced a need to test some configurations locally that *must not* be submitted to source control. The "local" files are perfect for that. Our .gitignore file keeps them from being committed.

**Comment by jashatton** [comment]
I can see that you all are pretty passionate about keeping it this way.  I think the flexibility would be a great enhancement to the library.  We will use it as is, but this inflexibility leads me to believe that the project is tunneled on certain approaches and that is concerning.

**Comment by markstos** [comment]
This project is opinionated, but also open to change. 

Several significant changes are in the process of being bundled for a new major version. You can review recently closed PRs for details.  You'll see that in those successful PRs, ideas for change were backed up with concrete details of how to implement and how backwards compatibility might be addressed (or not).

**Comment by jashatton** [comment]
You aren't wrong that I haven't been clear on the proposal so here is my stab at it. 

**Proposal:** 
The proposal is remove the **local** config name from the predefined load order.  **Local** should be treated like any other environment config, there can be only one in the load order.   Any source commits to a local profile can be code reviewed by teams or even potentially unit tested to prevent unintentional changes.  For environment specific values that shouldn't be committed they can be injected in as environment variables which I believe is supported already.

I would also suggest removing the default for a missing NODE_ENV.  We have had that sort of default and accidentally have had production environments pointing to development environments.  Not cool man, not cool.

**Backwards compatibility:**
Since it is nearly last in the load list then it shouldn't affect deployed environment which is the preferred behavior by the project contributors anyway.  If local isn't truly a dependent part of the load order except in local environments then backwards compatibility should not be an issue in pipeline environments. 

Hopefully that is what you are looking for.

**Comment by lorenwest** [comment]
Removing `local` from the predefined load order would require users of the config library to move their CI generated configurations from the local.json file into environment variables. This manual step is the definition of non-backward compatibility. It would require a major version bump, and downstream work for existing installations. And for what reason? Purity?

I'd be happy to entertain a proposal for `local.json` or `NODE_ENV` that doesn't break existing installations.

**Comment by jashatton** [comment]
@lorenwest What is being generated in the CI?  We use environment variables, pretty standard, for things like secrets.  is that what is being generated?

**Comment by lorenwest** [comment]
I could tell you the things our CI generates into a file and could be re-written to use environment variables to be more like your installation, but that's not the point. The point is - this is a library with over a million monthly downloads. It's impossible for me to make a representation of usage, but I can say with absolute certainty this would break backward compatibility.

**Comment by jashatton** [comment]
I appreciate the chance to talk try to talk it through.  Hopefully, with this form of communication I haven't seemed argumentative.  It certainly isn't intended.

**Comment by markstos** [comment]
Something that could be backwards compatible would to add an option in the code to disable it. 

I'm not sure if we would want to expose the option in the core module because it continues to have feature-creep with more options being added, but perhaps is something a plugin or extension could use to alter behavior.

If you are interested, dig into the code and look for a creative way to propose a backwards-compatible solution.

**Comment by jashatton** [comment]
@markstos Yeah, that would be an interesting idea.  I did fork the project.  I am not sure yet if and where the bandwidth would come from for that sort of thing.  It isn't my passion per-say 🤣.
