### ISSUE TITLE
Configuration files loading error on Windows

### ISSUE THREAD

**Issue by iyudincev** [lorenwest/node-config#567]
https://github.com/lorenwest/node-config/blob/ced8854a4bbf2ec09536d1db804d5cd5b60bb1ab/lib/config.js#L669
The hardcoded path delimiter (:) breaks handling of Windows file paths. OS dependent require('path').delimiter should be used.

**Comment by lorenwest** [comment]
In what way does this break the handling of Windows file paths? We're not talking about %PATH% here, we're talking about an environment variable used in the config library with a delimiter we chose to separate multiple config directories. We're the ones parsing that string, so I can't see how it has anything to do with breaking Windows.

**Comment by iMoses** [comment]
@iyudincev Is it because the use of absolute paths contains the partion letter with a column sign?

**Comment by iyudincev** [comment]
@iMoses yes, the code treats the volume letter in an actual path as a separate config directory.

**Comment by markstos** [comment]
Example:

      C:\Code\Project\Config

Gets parsed to:

     C
      \Code\Project\Config

The proposal was to use the `delimiter` method of the `path` module. From reading [the docs](https://nodejs.org/docs/latest-v8.x/api/path.html#path_path_delimiter) it sounds like this method exists for exactly this purpose.

**Comment by lorenwest** [comment]
Got it - this makes sense. It's for a new feature so the bug doesn't break existing installs. `pr-welcome`

**Comment by iMoses** [comment]
> Got it - this makes sense. It's for a new feature so the bug doesn't break existing installs. `pr-welcome`

@lorenwest This is incorrect. The new feature is part of `util.loadFileConfigs` so it does break installations on windows machine that use absolute config paths.

**Comment by lorenwest** [comment]
Oh right - of course it would. I'll merge and push asap.
