### ISSUE TITLE
Extend error message with env var's name on parse error

### ISSUE THREAD

**Issue by bankyadam** [lorenwest/node-config#570]
This is a _Feature Request_.
 
For now, if an env var is set to parse as JSON, but it's parse fails, the expection that is thrown has no information about where the error was found.

Example:
```
/app/node_modules/config/parser.js:154
throw e;
^

SyntaxError: Unexpected token } in JSON at position 1837
…
```

It would be nice if the exception should contain the env var's name which caused the parse error.

Example:
```
/app/node_modules/config/parser.js:154
throw e;
^

SyntaxError in ENV_VAR_NAME: Unexpected token } in JSON at position 1837
…
```

**Comment by markstos** [comment]
From reading https://github.com/lorenwest/node-config/wiki/Environment-Variables I only see one environment variable that supports being parsed as JSON, which is NODE_CONFIG. 

Did I miss any others?

**Comment by bankyadam** [comment]
@markstos: check the page you referred to for `ADMIN_ACCS` And you’ll see what I’m talking about.

**Comment by markstos** [comment]
@bankyadam Thanks. I agree a better error message would be helpful here. PR welcome. 

Also see #569, which proposes to overhaul how files like custom-environment-variables.json are processed in a future major version.

**Comment by leonardovillela** [comment]
Can i take this issue?

**Comment by leonardovillela** [comment]
I guess that should be handle in all supported formats

**Comment by leonardovillela** [comment]
Can we close this?
