### ISSUE TITLE
TOML error when using array of tables

### ISSUE THREAD

**Issue by dsbert** [lorenwest/node-config#574]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [ X ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

I am using a toml configuration that includes an array of tables:

```toml
[[messages]]
bodyDelimiter = "^"
```

When I attempt to load this configuration file and run nothing else - 

```ts
console.log("test 1");

import config from "config";

console.log("test 2");

config.get("messages");

console.log("test 3");
```

I never make it past the import statement. Instead I am treated to the following error.

```
/mnt/d/projects/src/node_modules/config/lib/config.js:700
      if (prop.hasOwnProperty(property) && prop[property] != null) {
               ^

TypeError: prop.hasOwnProperty is not a function
    at _iterate (/mnt/d/projects/src/translator/node_modules/config/lib/config.js
:700:16)
    at /mnt/d/projects/src/translator/node_modules/config/lib/config.js:715:13
    at Array.forEach (<anonymous>)
    at _iterate (/mnt/d/projects/src/translator/node_modules/config/lib/config.js
:706:24)
    at Config.util.resolveDeferredConfigs (/mnt/d/projects/src/translator/node_mo
dules/config/lib/config.js:727:3)
    at Config.util.loadFileConfigs (/mnt/d/projects/src/translator/node_modules/c
onfig/lib/config.js:651:8)
    at new Config (/mnt/d/projects/src/translator/node_modules/config/lib/config.
js:116:27)
    at Object.<anonymous> (/mnt/d/projects/src/translator/node_modules/config/lib
/config.js:1432:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
```

### What is the expected behavior?

The TOML library used by config follows version 4 of the spec, which does include arrays of tables, so I don't think I am doing anything out of scope and config should not crash.

### Please tell us about your environment:

 -  node-config version: 3.2.2
 -  node-version: 10.15.3
 -  typescript 3.5.3

**Comment by lorenwest** [comment]
It appears the TOML library creates something that looks like an Object:
```javascript
prop[property].constructor === Object
```
but unlike an Object it has no `hasOwnProperty` method on it.

**Comment by iMoses** [comment]
> It appears the TOML library creates something that looks like an Object:
> 
> ```js
> prop[property].constructor === Object
> ```
> 
> but unlike an Object it has no `hasOwnProperty` method on it.

It's the same issue we had with `isPromise` using `toString` on an object. 
The library clear the object's prototype so none of these methods are available.

**Comment by markstos** [comment]
Maybe we could move TOML support from core to a plugin a future major release? :slightly_smiling_face:

**Comment by dsbert** [comment]
It seems like the suggestion to to use `Object.hasOwnProperty.call(prop, property)` is the correct way to handle unknown values. If you use eslint in any projects, this is one of the recommended rules [no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins).

That said, I am not familiar with this code base so I'm not sure what kind of effort that requires or if there are other issues related to this.

Maybe the least that can be done is to add a warning in the docs explaining arrays of tables are not supported.

**Comment by jnordberg** [comment]
I get this error when using TOML 3.x, 2.x works fine

**Comment by markstos** [comment]
@dsbert @jnordberg A patch to use "Object.hasOwnProperty.call(prop, property)" where appropriate would be we.come.

**Comment by dsbert** [comment]
@markstos Done
