### ISSUE TITLE
Incorrect warning of missing config files when actually loaded properly

### ISSUE THREAD

**Issue by rjhilgefort** [lorenwest/node-config#580]
### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?

I'm following [this blog post on using typescript config files](https://itnext.io/node-config-made-type-safe-5be0a08ad5ba) and `node-config` is complaining that it can't find the config files, but the config is being loaded and working as expected.

I put modified the files in my local `node_modules` and logged out what `Parser` was finding and it saw that my config was loaded properly, and the warnings were still there. See screen shot below.

### What is the expected behavior?

`node-config` should not complain about missing config files when it actually did find them and loaded them properly.

### Please tell us about your environment:

 -  node-config version: 3.2.4
 -  node-version: ^10.15.3
 
### Other information

<img width="1260" alt="Screen Shot 2019-11-03 at 3 54 16 PM" src="https://user-images.githubusercontent.com/2034823/68093500-4da65d80-fe53-11e9-95f8-4adc5b26bcbc.png">

**Comment by lorenwest** [comment]
This is the first I've heard of this kind of problem. Could you provide a directory listing w/file permissions of 

`/Users/rhilgetfort001/Dropbox/Code/pwc/dcf-platform/projects/assessments-server/config`

**Comment by rjhilgefort** [comment]
Sure thing:

```
  rw-r--r--  rhilgefort001  staff  1020 B    Sun Nov  3 16:39:35 2019    README.md 
  rw-r--r--  rhilgefort001  staff  523 B    Sun Nov  3 16:40:14 2019    ci.ts 
  rw-r--r--  rhilgefort001  staff    1 KiB  Sun Nov  3 16:40:25 2019    default.ts 
  rw-r--r--  rhilgefort001  staff  908 B    Sun Nov  3 16:39:45 2019    demo.ts 
  rw-r--r--  rhilgefort001  staff  702 B    Sun Nov  3 16:39:43 2019    dev.ts 
  rw-r--r--  rhilgefort001  staff  983 B    Sun Nov  3 16:40:12 2019    production.ts 
  rw-r--r--  rhilgefort001  staff  364 B    Sun Nov  3 17:03:09 2019    qa.ts 
  rw-r--r--  rhilgefort001  staff  911 B    Sun Nov  3 16:40:57 2019    stage.ts 
  rw-r--r--  rhilgefort001  staff  365 B    Sun Nov  3 16:41:23 2019    test.ts 
  rw-r--r--  rhilgefort001  staff  924 B    Sun Nov  3 16:42:04 2019    training.ts 
  rw-r--r--  rhilgefort001  staff  678 B    Sun Nov  3 16:39:38 2019    types.ts 
```

**Comment by lorenwest** [comment]
It sure looks like everything is in order, and you're saying that the contents of qa.ts are actually being loaded, so this looks legit. I'm marking as a bug for someone to pick up, starting with building a test that fails.

**Comment by rjhilgefort** [comment]
I briefly tried to debug what was wrong but I couldn't quite figure it out. If I get some spare time, I'll see if I can look into a fix, but it won't be for a month or so with what I have for work coming up.

**Comment by rjhilgefort** [comment]
I figured out what was going on here. I'm running in a monorepo and I neglected to updated one of my side packages that was also using `config`. It wasn't able to find the `.ts` files because it was running an old version that didn't support TS. Sorry for the noise and thanks for the package and replies!
