### ISSUE TITLE
Config is `undefined` in typescript jest context?

### ISSUE THREAD

**Issue by kevzettler** [lorenwest/node-config#588]
#384 # I'm submitting a ... 
  - [x] bug report
  - [  ] feature request

### What is the current behavior?
I have a typescript module that works in dev and production. I am trying to import it into jest to write tests against and it throws an error that indicates the `config` object is undefined

```
    TypeError: Cannot read property 'get' of undefined
      at Object.<anonymous> (src/email/email.service.ts:1877:43)
```

```
import config from 'config'
console.log('**********CONFIG GET*********', config); // undefined
const sendgridToken: string = config.get('socialApi.value')
```

### What is the expected behavior?
I'd expect `config` to be defined its the default export of the `config` module

### Please tell us about your environment:

 -  node-config version: config@3.2.4
 -  node-version: 12.13.1
 
### Other information
```
tsc -v
Version 3.7.4
```

```
ts-jest@24.3.0
```

(e.g. are you using an environment besides Node.js?)

**Comment by Mualig** [comment]
I'm using config with jest (in a nestjs project) and it's working.
The only difference I see from your code is the import, I'm importing config with
```
import * as config from 'config';
```
I also have "@types/config" package in devDependencies.

**Comment by markstos** [comment]
Based on @Mualig's reply, this appears to be an environment issue.  Submit a failing test if it can be confirmed as a bug in config.

**Comment by farzadso** [comment]
@Mualig 's answer solves the issue for me.
