### ISSUE TITLE
empty environment variables don't read default

### ISSUE THREAD

**Issue by poyaz** [lorenwest/node-config#593]
### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?

In node-config before 3.3.0 if environment variables is empty read from default but in 3.3.0 if environment variables is empty (like: `MY_ENV= node index.js`) don't read default

### What is the expected behavior?

In version 3.2.6:

```bash
SERVER_HOST= HTTP_PORT= node index.js

### Output
### { host: '0.0.0.0', http: { port: 3000 }, https: { port: 3443 } }
```

In version 3.3.0:

```bash
SERVER_HOST= HTTP_PORT= node index.js

### Output
### { host: '', http: { port: '' }, https: { port: 3443 } }
```

My config dir info:

- config/default.json

```json
{
  "server": {
    "host": "0.0.0.0",
    "http": {
      "port": 3000
    },
    "https": {
      "port": 3443
    }
  }
}
```

- config/custom-environment-variables.json

```json
{
  "server": {
    "host": "SERVER_HOST",
    "http": {
      "port": "HTTP_PORT"
    },
    "https": {
      "port": "HTTPS_PORT"
    }
  }
}
```

### Please tell us about your environment:

 -  node-config version: 3.3.0
 -  node-version: 12.13.1

**Comment by markstos** [comment]
Thanks for the report. Would you be willing to contribute a failing test to the test suite which illustrates what you've shown above?

**Comment by poyaz** [comment]
https://github.com/lorenwest/node-config/pull/582/files

Did need write test for above files change or write test for my case?

**Comment by fostyfost** [comment]
@poyaz  hello,
SERVER_HOST= HTTP_PORT= 
This is equivalent to setting the environment variable to an empty string as a value.
I am sure that the code behaves correctly in this situation. Because you explicitly set the value of the environment variable.

**Comment by poyaz** [comment]
Yes  i know this code is correct but in version 3.2.6 this part of code have another behavior

**Comment by SkeLLLa** [comment]
I can confirm that this is regression in 3.3.X and it's breaking change.

**Comment by katsanva** [comment]
@fostyfost please see https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables:
>  Empty environment variables are ignored, and their mappings have no effect on your config.

**Comment by SkeLLLa** [comment]
@lorenwest could this PR be reverted at least for config-3.X.X and probably published as a part of major version update?

**Comment by lorenwest** [comment]
This being a regression we have two options

1. Revert the changes
2. Add code that makes it compatible

Does anyone want to submit a PR for #2 before I revert?

**Comment by SkeLLLa** [comment]
@lorenwest any updates?

**Comment by markstos** [comment]
I reviewed this, I agree with the proposal to revert for the 3.3.x series, as the behavior change seems desirable (per #582), re-introduce the change in a new major version.

**Comment by markstos** [comment]
@lorenwest This has been a regression since February. Let's revert it.

**Comment by lorenwest** [comment]
Go for it. My thought is reverting it will have the same negative effect,
but it's the right thing to do.

**Comment by airdrummingfool** [comment]
This regression causes a crash if you use parsed environment variables, e.g.:
```
{
  settings: {
    location: {
      '__name': 'SETTINGS_LOCATION',
      '__format': 'json',
    },
}
```

```
$ SETTINGS_LOCATION= node index.js

/app/node_modules/config/parser.js:148
    return JSON.parse(content);
                ^
SyntaxError: __format parser error in SETTINGS_LOCATION: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Parser.jsonParser (/app/node_modules/config/parser.js:148:17)
    at Config.util.parseString (/app/node_modules/config/lib/config.js:889:12)
    at _substituteVars (/app/node_modules/config/lib/config.js:1094:36)
    at _substituteVars (/app/node_modules/config/lib/config.js:1101:11)
    at Config.util.substituteDeep (/app/node_modules/config/lib/config.js:1111:3)
    at /app/node_modules/config/lib/config.js:1136:43
    at Array.forEach (<anonymous>)
    at Config.util.getCustomEnvVars (/app/node_modules/config/lib/config.js:1133:16)
    at Config.util.loadFileConfigs (/app/node_modules/config/lib/config.js:693:28)
```

**Comment by katsanva** [comment]
@lorenwest any way to revert the change that is causing this?

**Comment by markstos** [comment]
@katsanva A PR to revert the bad change is welcome.

**Comment by SkeLLLa** [comment]
@markstos I think new PR is not needed, there's an option to revert the PR, I've mentioned above https://github.com/lorenwest/node-config/pull/582 with "revert" button.

**Comment by airdrummingfool** [comment]
@markstos I've created a first-attempt PR #649, which adds tests and fixes the issue discussed without fully reverting #582. Please let me know what you think!
