### ISSUE TITLE
Cannot find module: 'config' but only when building production bundle

### ISSUE THREAD

**Issue by bobber205** [lorenwest/node-config#595]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [ X ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
I ended up trying all options found here: https://github.com/lorenwest/node-config/wiki/Webpack-Usage
Only option 3 worked with my VERY recently created create-react-app project.

Things are working great in dev mode after making those changes to webpack.config.js

But when I run `yarn build` I get 

```
Cannot find module: 'config'. Make sure this package is installed.

You can install this package by running: yarn add config.
```

Is Option 3 not valid anymore? Like I said I options 1,2 4 didn't work (same error about not being able to read the file at run time)

### Please tell us about your environment:

 -  node-config version: latest
 -  node-version: 10.16.0
 
### Other information

(e.g. are you using an environment besides Node.js?) No

**Comment by bobber205** [comment]
FIXED!

Instead of copying the json file to `build/client.json`, copy it to `src`

Recent changes to create-react-app make this necessary. (Check out jsconfig.json and make sure `"baseUrl": "src",` is set)

**Comment by bobber205** [comment]
Would it be appropriate to add this to the instructions?

**Comment by lorenwest** [comment]
Web crawlers will find this issue and it's more likely someone discovers this solution due to a web search than the RTFM method.

**Comment by bobber205** [comment]
@lorenwest Por que no los dos?

**Comment by lorenwest** [comment]
Exactly!  I'll accept your offer to add this to the instructions.

**Comment by bobber205** [comment]
@lorenwest I've added it to the instructions.
