### ISSUE TITLE
Why you guys make variable readonly after use config.get?

### ISSUE THREAD

**Issue by duncup** [lorenwest/node-config#596]
I got a case,  i pass the Object too a module from config, and module run code like that:
```
config.number = config.number | 0;
```
So i got an error for readonly. Why you guys do this to me, not just make a deep copy?
I don't think make a PR to change other Module is a good idea.

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please **search the issue tracker the wiki first**. Many issues have already been discussed.
