### ISSUE TITLE
Load configuration doesn't work properly with NODE_CONFIG_DIR for ESM case 

### ISSUE THREAD

**Issue by YuriyTigiev** [lorenwest/node-config#601]
### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
The module config doesn't load a config file from the NODE_CONFIG_DIR (C:\Users\yuriy\Documents\Projects\srvr\srvrapi\server\config) for ESM case. It loads the config from the C:\Users\yuriy\Documents\Projects\srvr\srvrapi\config 

### What is the expected behavior?
Load the configuration from the custom directory C:\Users\yuriy\Documents\Projects\srvr\srvrapi\server\config

### Please tell us about your environment:

 -  node-config version: 3.3.1
 -  node-version: v13.7.0
 
### Other information
```
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));

process.env['NODE_CONFIG_DIR'] = path.join(__dirname,'config');
console.log(process.env['NODE_CONFIG_DIR']);

import config from 'config';
console.log(config);

```
Error

```
[nodemon] restarting due to changes...
[nodemon] starting `node --experimental-modules --experimental-json-modules --es-module-specifier-resolution=node server/app.mjs`
(node:7304) ExperimentalWarning: The ESM module loader is experimental.
WARNING: No configurations found in configuration directory:C:\Users\yuriy\Documents\Projects\srvr\srvrapi\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
Config {}


C:\Users\yuriy\Documents\Projects\srvr\srvrapi\node_modules\config\lib\config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
          ^

Error: Configuration property "Customer.dbConfig.port" is not defined
    at Config.get (C:\Users\yuriy\Documents\Projects\srvr\srvrapi\node_modules\config\lib\config.js:182:11)
    at file:///C:/Users/yuriy/Documents/Projects/srvr/srvrapi/server/app.mjs:47:21
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:164:24)
```

default.json (sample file from documentation)

```
{
  "Customer": {
    "dbConfig": {
      "host": "localhost",
      "port": 5984,
      "dbName": "customers"
    },
    "credit": {
      "initialLimit": 100,
      "initialDays": 1
    }
  }
}

```

**Comment by lorenwest** [comment]
The output doesn't show the `console.log` from
```
console.log(process.env['NODE_CONFIG_DIR']);
```
before the `WARNING:` output is produced.  This tells me that `node-config` is loaded in a different module before this module was loaded, and didn't get the chance to have the `NODE_CONFIG_DIR` set.

**Comment by ToAnuranjans** [comment]
try setting 
NODE_CONFIG_DIR='server/config';  in main.js at first line before any other module access the config value.

assuming main.js and config folder are in server folder.

**Comment by markstos** [comment]
@ToAnuranjans Please add a failing test to the test suite which demonstrates this problem.

**Comment by ToAnuranjans** [comment]
@markstos I had suggested the solution. I have uploaded the code with similar implementation which works.
[github](https://github.com/ToAnuranjans/nodejs-starter-project.git)

**Comment by markstos** [comment]
I'm closing this because it's not clear what bug is being reported and no failing test for the test suite was contributed to clearly demonstrated. If there's a related bug, please contribute a failing test for the test suite which triggers it.

**Comment by cj-christoph-gysin** [comment]
I just ran into the same issue. When loading ESM modules, imports are resolved before any other code is executed:
```
process.env['NODE_CONFIG_DIR'] = myConfigDir // This is executed last
import config from 'config'; // This is executed first!
```
Unfortunately it's not possible to add a test case for this, as `vows` does not seem to support running ESM modules (*.test.mjs) AFAIK.

The only way to support ESM would be a different interface, e.g.:
```
import { load } from 'config'
process.env['NODE_CONFIG_DIR'] = myConfigDir
const config = load()
