### ISSUE TITLE
Loading many folders

### ISSUE THREAD

**Issue by younesherlock** [lorenwest/node-config#603]
### I'm submitting a ... 
  - [ x ] bug report

### What is the current behavior?
I have 2 config directories : `config/creds` and `config/setup`, each of these folders have a file `development.yaml`. The idea is to separate credentials config and app setup. I followed the instructions described [here](https://github.com/lorenwest/node-config/wiki/Configuration-Files#config-directory) but I get the following error :

```
c:\dev\project\node_modules\config\lib\config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
          ^ Error: Configuration property "ENV.types.dev" is not defined
```

### What is the expected behavior?
Load all files together in one `config` object 

### Please tell us about your environment:

 -  node-config version: 3.3.1
 -  node-version: 12.14.1

**Comment by lorenwest** [comment]
Many things could be happening from filename misspellings to bugs in the code. Would you mind submitting a failing test in this repository, or posting a sample repository with a config setup that exhibits this behavior?

**Comment by younesherlock** [comment]
@lorenwest I have pushed a mini [project ](https://github.com/younesherlock/config_test) that triggers the issue

**Comment by lorenwest** [comment]
Thank you - I'll take a look.  On first glance, however, it appears that you don't have a YAML parser. That could be the reason things aren't working. If you're using YAML, your project must have access to a YAML parser.

See the section section in the [Configuration Files](https://github.com/lorenwest/node-config/wiki/Configuration-Files) wiki page labelled _YAML Ain't Markup Language_. 

Is this the issue?

**Comment by younesherlock** [comment]
The issue was due to the fact that I had to update the value of `process.env.NODE_CONFIG_DIR` before anything else.
