### ISSUE TITLE
Any actual sub module config examples?

### ISSUE THREAD

**Issue by ScottChapman** [lorenwest/node-config#604]
Sorry, a little stumped (my usual state). I am not understanding how to implement config for my module that I plan to publish.  I've read the wiki, but I am having difficulty understanding how that all gets stitched together.

I'm sure I could figure it out if someone could point me to an existing example that implemented what is described there.

Thanks in advance!

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*
