### ISSUE TITLE
Setting NODE_CONFIG_DIR to multiple paths causes OS level ENAMETOOLONG error

### ISSUE THREAD

**Issue by alubchuk** [lorenwest/node-config#614]
### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
While using `NODE_CONFIG_DIR` variable with multiple configuration subfolders, which are quite deeply nested in the filesystem, I'm getting `ENAMETOOLONG` error, as follows:
```bash
{ paths:
   [ 'environment-000',
     'environment-001',
     'environment-002',
     'environment-003',
     'environment-04',
     'environment-05',
     'environment-06',
     'environment-07',
     'environment-08',
     'environment-09',
     'environment-10',
     'environment-11' ] }

Error: Config file /Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-000:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-001:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-002:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-003:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-04:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-05:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-06:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-07:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-08:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-09:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-10:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-11/runtime.json cannot be read. Error code is: ENAMETOOLONG. Error message is: ENAMETOOLONG: name too long, open '/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-000:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-001:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-002:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-003:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-04:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-05:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-06:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-07:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-08:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-09:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-10:/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/environment-11/runtime.json'
    at Config.util.parseFile (/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/node_modules/config/lib/config.js:771:13)
    at Config.util.loadFileConfigs (/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/node_modules/config/lib/config.js:648:26)
    at new Config (/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/node_modules/config/lib/config.js:116:27)
    at Object.<anonymous> (/Users/alexlubchuk/open-source/issues/node-config-enametoolong-issue/node_modules/config/lib/config.js:1441:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

### What is the expected behavior?
No error, library correctly loads and merges all config files found in subfolders from `NODE_CONFIG_DIR` variable.

### Please tell us about your environment:

 -  node-config version: 3.3.1
 -  node-version: 12.6.1
 
### Other information

While investigating this issue I figured out that it depends on the `PATH_MAX` OS variable, which has different value depending on the system:
- for OS X it's 1024 bytes
- for Linux it's usually 4096 bytes

The thing is that when all these paths have been concatenated using `NODE_CONFIG_DIR` variable, the final value, which exceeds PATH_MAX value, is being set first to `CONFIG_DIR` var ([here](https://github.com/lorenwest/node-config/blob/master/lib/config.js#L525)), and then to `RUNTIME_JSON_FILENAME` ([here](https://github.com/lorenwest/node-config/blob/master/lib/config.js#L536)), which library reads afterwards ([here](https://github.com/lorenwest/node-config/blob/master/lib/config.js#L651)) and fails in `util.parseFile` with error described before. The problem occurs while `fs.readFileSync` method is called ([here](https://github.com/lorenwest/node-config/blob/7a440f93440ca074deb55ff220c3998fc67be4d8/lib/config.js#L769)).

- I created a [demo project to showcase the error](https://github.com/alubchuk/node-config-enametoolong-demo). Pls check it out.

**Comment by alubchuk** [comment]
I think the main problem is at this line: https://github.com/lorenwest/node-config/blob/master/lib/config.js#L536
Why `runtime.json` has been appended to my list of configs? Because what I'm getting in the end is this:
```bash
my-configuration.json/runtime.json
```
which looks weird and incorrect.

**Comment by markstos** [comment]
What do you recommend as a resolution? Considering exactly one person has reported this issue despite having many module users, I'm inclined to wonder if there's not a better way to organize you configuration.

I can understand loading different environment for different customers or different instances, but why load a dozen different environment configurations at the same time? Doesn't the app only run a single environment at one time?

**Comment by alubchuk** [comment]
@markstos You're right, it was inefficiency on our side which was easily addressed though. Closing it as not relevant any more, thanks for the asnwer!
