### ISSUE TITLE
Undefined Configuration property error

### ISSUE THREAD

**Issue by Berkmann18** [lorenwest/node-config#617]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behaviour?
*If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:
Using either 
```js
const getConfig = require('config').get;
getConfig('db');
``` or
```js
const { get } = require('config')
get('db');
```
to get `db` in `./config/default.json` leads to an `Configuration property "db" is not defined` error which doesn't happen when doing:
```js
const config = require('config');
config.get('db');
```
### What is the expected behaviour?
Being able to only import `get` either by object deconstruction or by "Object getter" approach without having to entirely import `config` (especially when `get` is the only function used). 

### Please tell us about your environment:

 -  node-config version: 3.3.1
 -  node-version: 14.12.0
 
### Other information

(e.g. are you using an environment besides Node.js?) No

**Comment by jonathborg** [comment]
Same here. Works with ```import { get } from 'config'``` but not with ```import config from 'config'```

**Comment by lorenwest** [comment]
This is because `get` isn't a method directly on the object returned from `require('config')`. It's a method of the prototype of that object.  

If you make direct reference to the get method on the prototype, it has no context of `this` to do work.  This should work:

const config = require('config');
const get = config.get.bind(config);

**Comment by jonathborg** [comment]
Yaya, I'm talking about "This is not ideal approach". I think this will not change. Moving for my own solution. Hope the best. Thanks for your explanation.

**Comment by Hedzer** [comment]
This is happening to me as well. In my case it fails regardless of how it's imported. I'm slightly upset with how much time I've spent trying to fix the issue, only to find it's been somewhat dismissed as an actual issue.

**Comment by lorenwest** [comment]
Sorry to hear you spent time trying to fix something, only to find out it doesn't work the way you thought.  I understand your frustration.

It's not that the issue isn't real, it just hasn't caused enough pain to have anyone issue a pull request for the functionality. 

You're welcome to be that contributor!

**Comment by markstos** [comment]
Appears to be duplicate of https://github.com/lorenwest/node-config/issues/657

**Comment by Hedzer** [comment]
> Sorry to hear you spent time trying to fix something, only to find out it doesn't work the way you thought. I understand your frustration.
> 
> It's not that the issue isn't real, it just hasn't caused enough pain to have anyone issue a pull request for the functionality.
> 
> You're welcome to be that contributor!

Oh geez, I really need to refrain from commenting when frustrated. This is a really good project, and it works for literally everyone else. I apologize for my lack of tact. I'll see if I can scrape some time together and contribute.
