### ISSUE TITLE
Update parser.js to support .cjs and .mjs files

### ISSUE THREAD

**Issue by soulofmischief** [lorenwest/node-config#618]
### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
`.cjs` and `.mjs` files are ignored.

### What is the expected behavior?
Files with these extensions should be properly loaded. Otherwise `node-config` is incompatible with projects containing `"type": "module"` in the `package.json`

### Please tell us about your environment:

 -  node-config version: 3.3.2
 -  node-version: 14.13.0

**Comment by koalex** [comment]
When to wait for the update?

**Comment by markstos** [comment]
This is request resolveds by the recently merged support for `.cjs` extension? (Not yet released).

https://github.com/lorenwest/node-config/commit/8acffa795b139c3fd206334678b54b59e7eab6a7

If not, submit a PR for what's missing after checking the open PRs to sees if there's already a related one.

**Comment by soulofmischief** [comment]
I have tried using .cjs files and it does indeed work now. Closing this issue. Thanks!
