### ISSUE TITLE
get() function warning: "Unresolved function or method get()"

### ISSUE THREAD

**Issue by trantoan960** [lorenwest/node-config#627]
<img width="1280" alt="Screen Shot 2020-11-25 at 7 21 45 PM" src="https://user-images.githubusercontent.com/31186688/100227360-9dbafb00-2f53-11eb-8f15-2cf0eff6c45a.png">

Using webstorm and enabled node.js assistance but still warning :(((
Plz help me, I don't like warning that in my project

**Comment by markstos** [comment]
The "new issue" is template is clear that StackOverflow is the place to ask support questions.

https://github.com/lorenwest/node-config/issues/new
