### ISSUE TITLE
Uncaught ReferenceError: node_env_var_name is not defined

### ISSUE THREAD

**Issue by hcharley** [lorenwest/node-config#628]
### What is the current behavior?

I am currently seeing this bug in 3.3.3 in the browser:

```
Uncaught ReferenceError: node_env_var_name is not defined
    at j._.loadFileConfigs
```

<img width="981" alt="Screen Shot 2020-11-30 at 8 19 37 PM" src="https://user-images.githubusercontent.com/1542740/100684955-641a3380-3349-11eb-807a-16f0b49d7aed.png">

It appears it is from this commit:

b4ba63c84ec9b3d86559bca05b34f78833f3f850

In this line:

https://github.com/lorenwest/node-config/commit/b4ba63c84ec9b3d86559bca05b34f78833f3f850#diff-d5109920b34c2b2e141bd41232d8876432a17479c388e142d8a036bb7b36ea62R520

### What is the expected behavior?

Previous versions of node-config would not throw this error.

### Please tell us about your environment:

 -  node-config version: 3.3.3 
 -  node-version: 12.18.3
 
### Other information

Webpack config:

```js
const webpack = require('webpack');
const config = require('config');

const getNodeConfigPlugin = (addPlugin) => {
  const CLIENT_CONFIG = {
    app: {
      gitSha: config.get('app.gitSha'),
    },
    env: {
      nodeEnv: config.get('env.nodeEnv'),
    },
    performance: config.get('performance'),
  };

  console.warn(
    CLIENT_CONFIG,
    'WARNING: THIS CONFIGURATION INFORMATION WILL BE AVAILABLE TO THE CLIENT'
  );

  addPlugin(
    new webpack.DefinePlugin({
      'process.env.NODE_CONFIG': JSON.stringify(JSON.stringify(CLIENT_CONFIG)),
    })
  );
};
exports.getNodeConfigPlugin = getNodeConfigPlugin;
```

**Comment by benkiefer** [comment]
The line causing this is line 521 of config.js. It appears to have been broken by https://github.com/lorenwest/node-config/pull/576.

**Comment by benkiefer** [comment]
We are seeing it in server side code as well.

```
 ReferenceError: node_env_var_name is not defined
 at Config.loadFileConfigs (node_modules/config/lib/config.js:520:8)
      at new Config (node_modules/config/lib/config.js:116:27)
      at Object.<anonymous> (node_modules/config/lib/config.js:1459:31)
```

**Comment by hacknlove** [comment]
this
` for (node_env_var_name of node_env_var_names) {`

Should be `for (const node_env_var_name of node_env_var_names) {`

**Comment by tapsboy** [comment]
For anyone like us, we found the issue occurring where we are using babel to transpile code. In other node apps, where we dont use babel, it doesn't throw any error

**Comment by lorenwest** [comment]
Pushed in v3.3.5 today.  Thank you for the patch!
