### ISSUE TITLE
No configurations found in configuration directory

### ISSUE THREAD

**Issue by MahdiMaarouf2016** [lorenwest/node-config#634]
I am using this tuto :
https://dev.to/dedrevil/manage-multiple-environments-in-node-js-using-node-config-15cj
now , i created a **config folder** in my project root directory and inside it i created a **heroku.json** files as an environment .

My start script is : _cross-env NODE_ENV=heroku && nodemon src/server.js_

My environment:

 -  node-config version: v12.13.0
 -  node-version: ^3.3.3

problem : WARNING: No configurations found in configuration directory:D:\??\??\projectroot\config

**Comment by lorenwest** [comment]
You actually had to **delete** the following to add your support question:

**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*
