### ISSUE TITLE
Add ability to override configuration from command line in dot notation

### ISSUE THREAD

**Issue by eyalroth** [lorenwest/node-config#638]
### I'm submitting a ... 
  - [  ] bug report
  - [ X ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
Can override configuration from the command line only via full blown JSON, as per [the documentation](https://github.com/lorenwest/node-config/wiki/Command-Line-Overrides).

### What is the expected behavior?
I would _extremely_ helpful to be able to override configuration properties via dot notation; for instance:
```
npm run start -- -Cserver.host=localhost -Cserver.port=12345
```

This is similar to the ability to override configuration via command line when using Java's [lightbend/config](https://github.com/lightbend/config/blob/master/README.md):
```
java ... -Dmyapp.foo.bar=10
```

### Please tell us about your environment:

 -  node-config version: 3.2.2
 -  node-version: 10.16.3

**Comment by iangregsondev** [comment]
Not a bad idea. I prefer the format

-something -something.else -another -another.thig

**Comment by markstos** [comment]
We currently offer the option of using environment variables. This requires the extra step of mapping them in a `custom-environment-variables.json` file. 

I can see how it might be nice to override values directly without using an environment variable.

**Comment by markstos** [comment]
I'm closing this because setting environment variables using `custom-environment-variables.json` is a sufficiently good alternative.

**Comment by eyalroth** [comment]
@markstos I understand that this may not be the most prioritized issue, but I believe that the custom environment variables to not satisfy this feature request, since they require considering and pre-defining each potential option that could be overridden. The motivation behind this feature is to allow to _easily_ override _any_ option in the configuration.
