### ISSUE TITLE
development vs production

### ISSUE THREAD

**Issue by tamis-laan** [lorenwest/node-config#639]
Not sure if this is a bug, I have `development.js`, `production.js` and `custom-environment-variables.json` config files. When I run my node application I print `NODE_ENV` which returns `production`. I would expect the `production.json` config file to be loaded however the values from `development.js` are loaded. 

I'm using version 3.3.3 of node-config.

Am I missing something? Or is this a bug?

**Comment by tamis-laan** [comment]
I think my problem is related to:
[https://github.com/lorenwest/node-config/wiki/Webpack-Usage](https://github.com/lorenwest/node-config/wiki/Webpack-Usage)

I'm using webpack to bundle my server side code and apparently node-config doesn't play nice. Is there any way to use webpack for bundeling server side code and keeping node-config functional?? I really need to dynamically read my config file on startup and would like to avoid baking in my config file.

**Comment by markstos** [comment]
Closing because there already other issues about Webpack support: https://github.com/lorenwest/node-config/issues?q=webpack+is%3Aopen

Please comment or subscribe to one of the existing ones.
