### ISSUE TITLE
Outdated util.loadFileConfigs documentation.

### ISSUE THREAD

**Issue by NguyenMatthieu** [lorenwest/node-config#641]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [X] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

Following the changes to issue #517 a new parameter was added to the loadFileConfigs utility function. This flag is not documented on the wiki

### What is the expected behavior?

The flag should be documented on the wiki, in the "Using Config Utilities" page.

### Please tell us about your environment:

 -  node-config version: 3.3.4
 -  node-version: 12 LTS
 
### Other information

I have forked the wiki and prepared an update to the documentation that you can check at

https://github.com/NguyenMatthieu/node-config.wiki.git on a branch called "skipConfigSources"

I don't know how to make a "wiki pull request" but will be happy to submit one if I get a bit of guidance here.

**Comment by lorenwest** [comment]
Do the wiki pages have an [Edit] button for you to update directly?  The wiki should be set up for updates from the community.

**Comment by NguyenMatthieu** [comment]
@lorenwest Now I don't know how I missed that, I kept looking for ways to get it on git and submit pull request. Wiki updated
