### ISSUE TITLE
Isn't config root read only and cloned?

### ISSUE THREAD

**Issue by mashinosatoshi** [lorenwest/node-config#648]
Hi, 

I'm using this library for work, and in api with Express.
When I get config properteis with `config.get('******')`, properties are read only.
But when I get config with `config` for getting all config file, properties are not read only.
And, if I change the value of a property, this change is remained until I restart a process of api.

For example, if I set json file as bellow.
```
{
  "aaa":[
    "111",
    "222"
  ],
  "bbb":[
    "333"
  ]
}
```

And I make a function like this(I know the code is not good),
```
const getConfig = () => {
    const conf = require('config')
    conf.aaa = "poluution"
    return conf
}

export default getConfig;
``` 

If I execute `getConfig()`, json object is changed to bellow at least in standing process.
```
{
  "aaa":"poluution",
  "bbb":[
    "333"
  ]
}
```

I think, config root object  should be read only or cloned.
Is this behavior intended?

Best regards.

### I'm submitting a ... 
  - [  ] bug report
  - [  ] feature request
  - [*] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### Please tell us about your environment:

 -  node-config version: 3.3.6
 -  node-version: v12.10.0

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki
