### ISSUE TITLE
Hot/dynamic load vars from Node's process.env

### ISSUE THREAD

**Issue by gvko** [lorenwest/node-config#650]
### I'm submitting a ...
  - [ X ] feature request

### What is the current behavior?
The env vars (as stated [in the wiki](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables)) are loaded into the config only from the environment of the Node's parent process.

### What is the expected behavior?
Could we have them loaded also from Node's internal `process.env` environment? This way one can load secrets on demand, on app start, say from a 3rd party secret manager, w/o having to rebuild the app.

This is mostly valid with containerized apps. F.e. right now, if I want to provide new env vars for `node-config` to load into the config at app start, I have to rebuild the container image, or change some configuration in the container-orchestrating tool. This always requires code changes. 

It would be awesome if the lib can also load from Node's `process.env`, so one can pull the secrets from "wherever" at app start, load them into `process.env` and then `node-config` takes care of them to be loaded into the config.

**Comment by markstos** [comment]
The config IS precisely set from `process.env`.    You are asking for "hot reloading" which has been discussed many times and is not a feature that desired for `node-config`. Fork it or use a different package if you want that.

A sample of past discussions:

https://github.com/lorenwest/node-config/issues/357
https://github.com/lorenwest/node-config/issues/224
https://github.com/lorenwest/node-config/pull/621
https://github.com/lorenwest/node-config/issues/540

Restarting the app should not be a huge deal. You should have a redundant production environment, so automate restarting one copy of the app, then restart the redundant copy, and it's a zero-downtime operation without the problems that come with having global configuration that is mutable.
