### ISSUE TITLE
get with default value

### ISSUE THREAD

**Issue by orcas-mgleich** [lorenwest/node-config#653]
Can you insert a default value parameter for get() e.g.
```javascript
let minLength = config.get("minLength", {}, 10);
```
This could be replacing:
```javascript
let minLength = config.has("minLength") ? config.get("minLength") : 10;
```

**Comment by lorenwest** [comment]
This has been discussed at length [searching issues: "defaults for config.get"](https://github.com/lorenwest/node-config/issues?q=defaults+for+config.get)

**Comment by markstos** [comment]
In particular: https://github.com/lorenwest/node-config/issues/504#issuecomment-422057179
