### ISSUE TITLE
Async Example Documentation

### ISSUE THREAD

**Issue by Ryan8765** [lorenwest/node-config#655]
Is there any examples for async operations?  I'm specifically interested in being able to call an external source and populate configs with this source (looking to call AWS Secrets Manager and inject values into the configuration):

```javascript


const async = require('config/async').asyncConfig;

const promisefunction = async ()=>{
  var secret = await Promise.resolve("lskjflksjfdsklfjslkfljslfjsdklfdsjd");
  return secret;
};

module.exports = {
  host: "localhost",
  port: 3030,
  public: "../public/",
  testing: async(promisefunction()),
  paginate: {
    default: 10,
    max: 50
  },
  authentication: {
    entity: "user",
    service: "users",
    secret: "9pKAfA/aJR0eMtp9P3nURwkuopg=",
    authStrategies: [
      "jwt",
      "local"
    ],
    jwtOptions: {
      header: {
        typ: "access"
      },
      audience: "https://yourdomain.com",
      issuer: "feathers",
      algorithm: "HS256",
      expiresIn: "1d"
    },
    local: {
      usernameField: "email",
      passwordField: "password"
    }
  },
  nedb: "../data"
};
```

Response when accessing this config:
{ async: Symbol(asyncSymbol), prepare: [Function (anonymous)] }

**Comment by markstos** [comment]
According to the PR which added async config support #554, there is a related wiki page: https://github.com/lorenwest/node-config/wiki/Asynchronous-Configurations I have not checked to see if it's linked from the main wiki page.
