### ISSUE TITLE
WebStorm cannot resolve 'get', 'has'

### ISSUE THREAD

**Issue by pplmx** [lorenwest/node-config#656]
### I'm submitting a ... 
  - [x] bug report
  - [x] feature request

### What is the current behavior?
It will throw a warning "Unresolved function or method get() "
```js
const config = require('config')
const params = config.get('params')
```

### What is the expected behavior?
IDE can resolve it.

### Please tell us about your environment:

 -  node-config version: 3.3.6
 -  node-version: 16.8.0

**Comment by dsf3449** [comment]
I'm experiencing the same issue

**Comment by fostyfost** [comment]
Try `npm install --save-dev @types/config`

**Comment by dsf3449** [comment]
It worked, thanks :)
