### ISSUE TITLE
wiki ref to env var `CONFIG_DIR` should probably be `NODE_CONFIG_DIR`

### ISSUE THREAD

**Issue by EvaLok** [lorenwest/node-config#658]
### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
ref: https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities#getenvvarname

in current documentation, the wiki makes reference to `CONFIG_DIR` but this seems to be incorrect (i would guess it actually means `NODE_CONFIG_DIR`)

the reason this seems likely is that `config.util.getEnv('NODE_CONFIG_DIR')` is defined by default while `config.util.getEnv('CONFIG_DIR')` is undefined and also unmentioned here: https://github.com/lorenwest/node-config/wiki/Environment-Variables

### What is the expected behavior?
documentation probably should reference `NODE_CONFIG_DIR` instead of `CONFIG_DIR`

### Please tell us about your environment:

 -  node-config version: 3.3.6
 -  node-version: v16.2.0
 
### Other information

n/a

**Comment by lorenwest** [comment]
Thank you for discovering this.  It has been changed.

**Comment by EvaLok** [comment]
@lorenwest i reviewed and noticed the original part that threw me off (the js example) was still referencing the incorrect variable name, so i went ahead and edited the wiki - hope it's OK
