### ISSUE TITLE
Create .env file in the api folder and fill it with values and put down JWT secret for JWT token 

### ISSUE THREAD

**Issue by Mohammed-alzuharey** [lorenwest/node-config#665]
Hello everyone 
I used hyperledger fabric application connected with IPFS. when I need run application , I go into the API folder and install the dependency :
$ cd api/
$ npm install
After that To Connect to mongodb instance to save data about transactions for filtering, searching and paginating. it require  Created .env file in the api folder to fill it with values and put down JWT secret for JWT token and enter preffered port for the server.as follow 
APP_PORT=
JWT_SECRET=
DB_USERNAME=
DB_PASSWORD=
DB_HOST=
DB_PORT=
DB_NAME=
**my question is how I can fill these values and JWT,I don't know,  any one can help me please ?**

**Comment by lorenwest** [comment]
Closed for deleting the issue template, and for not actually reading the firs paragraph:

**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*
