### ISSUE TITLE
19 Months and counting....

### ISSUE THREAD

**Issue by rcollette** [lorenwest/node-config#666]
19 Months and counting waiting for a fix to be published.  4 Months of that waiting for an already merged PR to be published in an NPM patch release.

See: #593

**Comment by markstos** [comment]
? Looks the history shows a fix was merged in September, 2021 and released in November 2021 in v3.3.6:

https://github.com/lorenwest/node-config/releases

I do see that npmjs.com shows conflicting information, showing v3.3.6 as being published in March of 2021:

https://www.npmjs.com/package/config

I also see there is no 3.3.5 release on NPM. Looks like a versioning mix up. I'll publish a new release now to address this.

**Comment by markstos** [comment]
Published as 3.3.7. Thanks for the nudge.

@lorenwest I used `gh release create v3.3.7` for this. I recommend using this instead of `History.md` going forward. It's both more common for projects and easier to maintain.
