### ISSUE TITLE
NODE_ENV warrning

### ISSUE THREAD

**Issue by lukasa1993** [lorenwest/node-config#669]
```
NODE_CONFIG={"app":{"port":"7702"}}
NODE_ENV=dev
```

how i suppress

```
WARNING: NODE_ENV value of 'dev' did not match any deployment config file names.
```

this warning ?

**Comment by lorenwest** [comment]
You may want to read the instructions that you had to delete to enter this issue

-------

**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

**Comment by lukasa1993** [comment]
i am not stackoverflow user but i guess i wont use this anymore ty anyway
