### ISSUE TITLE
Disable runtime.json writing & reading.

### ISSUE THREAD

**Issue by thomas-riccardi** [lorenwest/node-config#91]
Since PR #76 we can disable the writing of runtime.json, but only from environment variables, and runtime.json is still written to disk, containing '{}'.

I have a use-case where the config object is sometimes modified, but the modification is only relevant for the current process, so writing to runtime.json is an issue.

This should be possible to disable it from the application itself.

Also, when disabling runtime.json writing, it should not write a file containing '{}': just don't do anything at all.

Finally, I haven't found a way to easily disable the reading of runtime.json:
we can use getOriginalConfig(), but we need to do that on each require('config') in the application.
Ideally the server.js would just have to do something like: require('config').disableRuntime(); and it would be settled for the whole application.

**Comment by akloeber** [comment]
As for v1.0.0 and current v1.10.0 `runtime.json` still gets generated containing `{}` if it is not present. Setting `process.env.NODE_CONFIG_PERSIST_ON_CHANGE = 'N'` has no influence at all.

Moreover in our case the config location is not writable by the user running the application which provokes EACCES errors.

**Comment by akloeber** [comment]
Sorry my fault, there was a dependency to node-config v0.4 in a nested module.
